### ISSUE TITLE
Getting error on adding service in AndroidManifest.xml file

### ISSUE THREAD

**Issue by nidhi-singh02** [heremaps/here-android-sdk-examples#119]
Hi,

I am getting error while adding service in Manifest file. My service name is "android:name="com.here.android.mpa.service.MapService" as shown in HERE-API documents. But I am getting error of Unresolved package name.

Can someone please help me.

Thanks,
Nidhi

**Comment by JH-YVR** [comment]
Hi Nidhi, can you please confirm if you are using an isolated map disk cache and clarify where in the steps described in the section 'Embedding the Map Service' in the developer guide you are encountering a problem.

**Comment by nidhi-singh02** [comment]
Hi, 
Yes, i am using isolated disk cache.

I am facing issue at the first step to use an isolated disk cache,which is to edit the AndroidManifest.xml with the following, providing the service label and intent name with your custom values.

<service
  android:name="com.here.android.mpa.service.MapService"
  android:label="{YOUR_LABEL_NAME}"
  android:exported="false">
  <intent-filter>
    <action android:name="{YOUR_INTENT_NAME}">
    </action>
  </intent-filter>
</service>
