### ISSUE TITLE
App Size Increased after adding Here maps SDK 

### ISSUE THREAD

**Issue by MohammedFayaj** [heremaps/here-android-sdk-examples#126]
here Maps latest SDK is 64 Mb after adding that app size increased a lot, checked the Size management docs dint help much .can you please help.

**Comment by NazarKacharaba** [comment]
Here SDK library supports different ABIs, therefore app size is increased. You can create multiple APKs for multiple ABIs - [configure abi split](https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split ).

**Comment by NazarKacharaba** [comment]
>Apart from doing Abi Split does here maps provide aar of different features like routing/position etc separately?

No, it does not. You can check HERE Starter SDK that has smaller size footprint if that is critical for you.

**Comment by tlushney** [comment]
Hope we can close the issue.
