### ISSUE TITLE
Basic Postioning

### ISSUE THREAD

**Issue by MohammedFayaj** [heremaps/here-android-sdk-examples#127]
Non-premium SDK basic positioning is way faster than the premium basic positioning why?

I have two samples running one with premium and non-premium the app, with non-premium version, loads the current location smoother and faster, while premium I need to use position manager to load current location and its too slow any idea?

**Comment by JH-YVR** [comment]
@MohammedFayaj , thanks for asking the question. Can you provide some more details on what are the steps you are doing and what you are seeing? Is the delay you are referring to the time to get a GPS fix or the time to render the map with your current position? If the latter, is this only a problem the first time you load the map or always?

**Comment by rpadma** [comment]
@JH-YVR With Android Starter SDKs we are able to load the current position directly once the map is render but when we use the Premium SDKs the map renders with Berlin as default location and it waits for 1 to 3 seconds (Depends on the mobile devices ) to move the camera position over the map to the current location.

**Comment by JH-YVR** [comment]
@MohammedFayaj and @rpadma, the Starter and Premium Editions should deliver the same performance. Where you may see a slight delay to get an initial position when using the Premium Edition is when you set the location data source to HERE Positioning. See https://developer.here.com/documentation/android-premium/dev_guide/topics/advanced-positioning.html for more details on setting the location data source to HERE Positioning.
