### ISSUE TITLE
Unresolved class MapService when adding Service to AndroidManifest.xml

### ISSUE THREAD

**Issue by arturschwarz** [heremaps/here-android-sdk-examples#129]
``<service
            android:name="com.here.android.mpa.service.MapService"
            android:label="<myLabel>"
            android:exported="false">
            <intent-filter>
                <action android:name="<myIntent">
                </action>
            </intent-filter>
        </service>``

Getting the error which is described in the title, when adding this to the AndroidManifest.xml.
Found [here](https://developer.here.com/documentation/android-premium/topics/app-simple-android-studio.html)

**Comment by NazarKacharaba** [comment]
Make sure you correctly included AAR, if so, you will be able to navigate to `MapService .class` in the AS using e.g. Cmd + Shift + O or double Shift (search everywhere).

What version of android plugin for gradle do you use?
