### ISSUE TITLE
Cannot create map: Failed to read configuration file: /storage/0DCB-2441/.here-maps/6e03e327a6a7294380fd04a73f75524c/mwconfig_client

### ISSUE THREAD

**Issue by freedom9900** [heremaps/here-android-sdk-examples#134]
Process: com.app.app, PID: 247 java.lang.RuntimeException: Cannot create map: Failed to read configuration file: /storage/0DCB-2441/.here-maps/6e03e327a6a7294380fd04a73f75524c/mwconfig_client at com.nokia.maps.MapImpl.(MapImpl.java:451) at com.here.android.mpa.mapping.Map.(Map.java:710) at com.nokia.maps.bw.m(MapFragmentImpl.java:546) at com.nokia.maps.bw.a(MapFragmentImpl.java:583) at com.nokia.maps.bw.a(MapFragmentImpl.java:85) at com.nokia.maps.bw$1.onEngineInitializationCompleted(MapFragmentImpl.java:135) at com.nokia.maps.MapsEngine$10.run(MapsEngine.java:2471) at android.os.Handler.handleCallback(Handler.java:808) at android.os.Handler.dispatchMessage(Handler.java:101) at android.os.Looper.loop(Looper.java:166) at android.app.ActivityThread.main(ActivityThread.java:7425) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by starand** [comment]
Hi @freedom9900,
The issue happens when you delete cache folder during runtime. Probably you use isolated disc cache feature. You should not set it to any cache folder. It is recommended to use application private folders.

**Comment by freedom9900** [comment]
Give me more details...

**Comment by freedom9900** [comment]
I have a device with SD card (default storage selected)...This error appears in that case. Hints?

**Comment by starand** [comment]
@freedom9900 could you please provide code how you initialize engine? Do you use isolated disc cache? What is your device?

**Comment by freedom9900** [comment]
AndroidManifest.xml

<service
            android:name="com.here.android.mpa.service.MapService"
            android:exported="false"
            android:label="HereMapService"
            android:process="global.Here.Map.Service.v3">
            <intent-filter>
                <action android:name="com.here.android.mpa.service.MapService.v3" />
            </intent-filter>
        </service>

CodeFileActivity.class

private final static int REQUEST_CODE_ASK_PERMISSIONS = 1;
private static final String[] REQUIRED_SDK_PERMISSIONS = new String[] {
            android.Manifest.permission.ACCESS_FINE_LOCATION, android.Manifest.permission.WRITE_EXTERNAL_STORAGE };

private com.here.android.mpa.mapping.Map map = null;
private MapFragment mapFragment = null;




protected void checkPermissions() {
        final List<String> missingPermissions = new ArrayList<String>();
        // check all required dynamic permissions
        for (final String permission : REQUIRED_SDK_PERMISSIONS) {
            final int result = ContextCompat.checkSelfPermission(this, permission);
            if (result != PackageManager.PERMISSION_GRANTED) {
                missingPermissions.add(permission);
            }
        }
        if (!missingPermissions.isEmpty()) {
            // request all missing permissions
            final String[] permissions = missingPermissions
                    .toArray(new String[missingPermissions.size()]);
            ActivityCompat.requestPermissions(this, permissions, REQUEST_CODE_ASK_PERMISSIONS);
        } else {
            final int[] grantResults = new int[REQUIRED_SDK_PERMISSIONS.length];
            Arrays.fill(grantResults, PackageManager.PERMISSION_GRANTED);
            onRequestPermissionsResult(REQUEST_CODE_ASK_PERMISSIONS, REQUIRED_SDK_PERMISSIONS,
                    grantResults);
        }
    }

private void initialize() {
        mapFragment = (MapFragment)getFragmentManager().findFragmentById(
                R.id.mapaFragmentPK);

        mapFragment.init(new OnEngineInitListener() {
            @Override
            public void onEngineInitializationCompleted(
                    OnEngineInitListener.Error error)
            {
                if (error == OnEngineInitListener.Error.NONE) {

                    map = mapFragment.getMap();
                    map.setMapScheme(Map.Scheme.SATELLITE_DAY);
                    addMarkerOnMap(listK.get(viewPager.getCurrentItem()));

                } else {
                    System.out.println("ERROR: Cannot initialize Map Fragment");
                    Globals.getErrorDialog(PregledKamera.this, "Map not available!").show();
                }
            }
        });
    }

@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String permissions[],
                                           @NonNull int[] grantResults) {
        switch (requestCode) {
            case REQUEST_CODE_ASK_PERMISSIONS:
                for (int index = permissions.length - 1; index >= 0; --index) {
                    if (grantResults[index] != PackageManager.PERMISSION_GRANTED) {
                        // exit the app if one permission is not granted
                        Toast.makeText(this, "Enable permission for memory and location.", Toast.LENGTH_LONG).show();

                        finish();

                        return;
                    }
                }
                // all permissions were granted
                initialize();
                break;
        }
    }

    private void setIcon(MapMarker mapMarker, int imgResourceId) {
        Image marker_img = new Image();

        try {
            Bitmap bitmap = getBitmapFromVectorDrawable(this, imgResourceId);
            marker_img.setBitmap(bitmap);
            mapMarker.setIcon(marker_img);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

public static Bitmap getBitmapFromVectorDrawable(Context context, int drawableId) {
        Drawable drawable = ContextCompat.getDrawable(context, drawableId);

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            drawable = (DrawableCompat.wrap(drawable)).mutate();
        }

        Bitmap bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
        drawable.draw(canvas);

        return bitmap;
    }

**Comment by starand** [comment]
@freedom9900 
That issue can happen when user partially deletes map data cache (e.g. some assets were deleted).
If that happens, you have to clear the cache completely and reinit SDK. Unfortunately, SDK does not support cases with partially corrupted disk cache.
Is this still a case for you? Sorry for late response.
