### ISSUE TITLE
Stopping/restarting voice navigation

### ISSUE THREAD

**Issue by akaraali** [heremaps/here-android-sdk-examples#135]
I have been able to set the voice skin and it is working correctly. I just want to know if there is any way to pause/mute it mid navigation. Also how to get the voice directions to stop when the navigation manager is stopped because it continues to speak afterwards.

**Comment by Merlin1stHere** [comment]
Currently the SDK doesn't support pause/mute of the voice commands during navigation.
You can stop playing the audio immediately by calling of NavigationManager.getAudioPlayer().stop().
