### ISSUE TITLE
Can we set interval at which heremaps positioning manager class send location updates?

### ISSUE THREAD

**Issue by Jenishgithub** [heremaps/here-android-sdk-examples#137]
I'm trying to use heremaps positioning sdk to fetch location updates, right now it seems as it fetches location info depending upon whether the device is at motion or stationary. Can we set the interval (say every 2 secconds or 3 seconds) at which location info is fetched? I cannot find any method to set interval to heremaps positioning manager.

**Comment by NazarKacharaba** [comment]
Hi @Jenishgithub 
There is no such API.
Sorry for the late answer.

**Comment by starand** [comment]
@Jenishgithub that behavior can be easily implemented on app side.
