### ISSUE TITLE
Android Here Maps - changing keys issue

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [heremaps/here-android-sdk-examples#144]
Hi there I got an issue, it goes like this:

Have a fully working app with Here Maps integrated, everything works as intended.
After the Keys expired, we replaced them with a new set of keys for the same package name.
A full clean (deleted generated files), build and reinstall of the app was done.

We have this code snippet:

```java 
    @Override
    public void init(@Nullable OnMapLoadedCallback onMapLoadedCallback) {
        MapEngine.getInstance().init(new ApplicationContext(context), error -> {
            if (error == OnEngineInitListener.Error.NONE) {
                if (getMap() != null) {
                    setMap(new Map());
                    map = getMap();
                    onMapReady(getMap());
                    if (onMapLoadedCallback != null) {
                        onMapLoadedCallback.onMapLoaded();
                    }
                } else {
                    Logger.debug(getClass(), "ERROR: Cannot initialize Map - getMap() is null");
                }
            } else {
                Logger.debug(getClass(), "ERROR: Cannot initialize Map Fragment error " + error.getDetails());
            }
        });
    }

```

Running this code, we can observe:
 1.     (error == OnEngineInitListener.Error.NONE) is true
 2.     getMap() != null is false
 3.     Logger.debug(getClass(), "ERROR: Cannot initialize Map - getMap() is null"); is called

Expected result:
**error** should not be **OnEngineInitListener.Error.NONE** or **getMap()** to not be null

**Comment by LaurentiuSimionescu** [comment]
error.name() is NONE
error.getDetails() is null
error.getStackTrace() is null

**Comment by NazarKacharaba** [comment]
Hi @LaurentiuSimionescu 

Do you use `MapFragment`? If so, why do you call `MapEngine.getInstance().init(...)`? `MapFragment` has [`init`](https://github.com/heremaps/here-android-sdk-examples/blob/master/map-customization/app/src/main/java/com/here/android/example/map/customization/MapFragmentView.java#L92) method that you should use.

If possible, share your whole activity/fragment/class code where you do map initialization.

**Comment by LaurentiuSimionescu** [comment]
This was my mistake.

I was checking **getMap() != null** of the fragment before setting it using **setMap(new Map())**.

Changed this part:
```java
if (getMap() != null) {
    setMap(new Map());
    map = getMap();
    ....
```
To this part;
```java
 Map map = getMap();
 if (map == null) {
     map = new Map();
 }
 setMap(map);
```
