### ISSUE TITLE
Fragment not supported 

### ISSUE THREAD

**Issue by rsd96** [heremaps/here-android-sdk-examples#148]
I am trying to integrate here maps in an app with viewpager fragments but since I am using support fragment and the SDK still uses deprecated fragment class, "findfragmentbyid" always returns null. Any help to solve this issue would be greatly appreciated.

**Comment by NazarKacharaba** [comment]
You are right, HERE SDK does have `SupportMapFragment`, but instead you can use `MapView`(from `com.here.android.mpa.mapping` package) in your support fragment, follow _Developer’s Guide_, it should not be too complicated compare to `MapFragment`.

`SupportMapFragment` should be added in the next release, but for now I suggest you to use `MapView`.

**Comment by SzymonGrochowiak** [comment]
Are you going to release AndroidX and Android Support Library compatible versions? Or just for one of them?

**Comment by starand** [comment]
Hi @SzymonGrochowiak,
SupportMapFragment will included in 3.10 release (estimated date of release is about 17th of Dec).

**Comment by xsveda** [comment]
Any plans to AndroidX fragments directly? HERE SDK is the only dependency using old Support Libraries in our project so we must run Jetifier as a part of our build pipeline that consumes resources and slowers our builds.
