### ISSUE TITLE
Access Denied On LocationDataSourceHERE

### ISSUE THREAD

**Issue by boopathydreams** [heremaps/here-android-sdk-examples#151]
Hi,
I'm using the Premium SDK downloaded using my freemium account.
When I'm trying to access LocationDataSourceHERE, I get the following error message
`java.security.AccessControlException: Access to this operation is denied. Contact your HERE representative for more information.`.
I searched everywhere but I couldn't find a solution to that. Anyone around here, could you please assist me?

**Comment by JH-YVR** [comment]
Thanks @boopathydreams for posting this. We are investigating and will get back to you quickly.

**Comment by starand** [comment]
@boopathydreams,
An issue was fixed at the beginning of October which may have addressed the seen problem. If this is the case, registering a new application and obtaining new credentials would have fixed the problem.
Was your problem solved?

**Comment by boopathydreams** [comment]
It was solved actually. Sorry for the delayed response :(
