### ISSUE TITLE
How to reset Map or remove the MapRoute from Here Map in Android Here API

### ISSUE THREAD

**Issue by arorayogita** [heremaps/here-android-sdk-examples#152]
I am not able to remove the old route from map 
                           if (currentRoute != null) {
                             m_map.removeMapObject(currentRoute);
                            }// remove old route before showing new one
                           currentRoute = new MapRoute(routeResults.get(0).getRoute());
                            currentRoute.setColor(ContextCompat.getColor(m_activity, R.color.colorBlue));
                            m_map.addMapObject(currentRoute);

**Comment by arorayogita** [comment]
I am using Premium.
every time it just concat the route with the previous one

**Comment by NazarKacharaba** [comment]
Can you see the same issue in this [sample app](https://github.com/heremaps/here-android-sdk-examples/blob/d805c2335d68dad0ddb8c0aea26cfd06c0d1ed9e/routing/app/src/main/java/com/here/android/example/routing/MapFragmentView.java#L137)?

**Comment by starand** [comment]
Hi @arorayogita Was your issue solved?
