### ISSUE TITLE
Incorrect license key

### ISSUE THREAD

**Issue by vicky-droid** [heremaps/here-android-sdk-examples#153]
i imported example.guidance from the sample
replaced all the three keys in manifest
downloaded and added here.arr in library folder.
when i run the app i got error **Incorrect license key** 
i created 3 projects in console with correct package name.
suggest me workarounds.
thanks in advance for the support.
` <meta-data
            android:name="com.here.android.maps.appid"
            android:value="{******}" />
        <meta-data
            android:name="com.here.android.maps.apptoken"
            android:value="{***-tA}" />
        <meta-data
            android:name="com.here.android.maps.license.key"
            android:value="{****" />
`
i use freemium account and Premium SDKs.
`repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation(name: 'HERE-sdk', ext: 'aar')
    implementation 'com.google.code.gson:gson:2.2.4'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v13:28.0.0'
}`

**Comment by starand** [comment]
Hi @vicky-droid, that error is returned if LK is empty or corrupted. Please take a look on github samples and double check your manifest whether it's properly written. Please double check whether you copied full LK string. If that does not help, try to regenerate new LK.

**Comment by vicky-droid** [comment]
thank you @starand .
i have created a sample project and followed the documentation. i got the same error.so i downloaded the sample project from git. created a project in console with the sample project package name.and use that keys here still same error.
i double checked the LK. still have error how to regenerate LK?

**Comment by starand** [comment]
Go to https://developer.here.com/, press Get Started For Free, agree Terms and Conditions, and then Generate App Id and App Code for Android Premium SDK. If that does not help, try to change your package name.

**Comment by starand** [comment]
Hi @vicky-droid,
Can you share your sample app and appId to check?

**Comment by starand** [comment]
@vicky-droid was your issue solved?
If there is no feedback we will close the issue.
