### ISSUE TITLE
Reroute listener is not working properly

### ISSUE THREAD

**Issue by arorayogita** [heremaps/here-android-sdk-examples#154]
I am getting route results in routeEnd method but this method is called again and again .
 private NavigationManager.RerouteListener m_rerouteListener = new NavigationManager.RerouteListener() {
        @Override
        public void onRerouteBegin() {
            super.onRerouteBegin();
            Toast.makeText(getApplicationContext(), "routeStarted", Toast.LENGTH_SHORT).show();

        }

        @Override
        public void onRerouteEnd(RouteResult routeResult) {
            super.onRerouteEnd(routeResult);
            clearRoute();
            Toast.makeText(getApplicationContext(), "routeEnd" + routeResult.getRoute(), Toast.LENGTH_SHORT).show();
            mapReRoute = new MapRoute(routeResult.getRoute());
            if (m_navigationManager.getRunningState() == NavigationManager.NavigationState.RUNNING) {
                m_navigationManager.removePositionListener(m_positionListener);
                m_navigationManager.removeNewInstructionEventListener(instructionHandler);
                m_navigationManager.removeRerouteListener(m_rerouteListener);
                m_navigationManager.stop();
            }
            showRoute(mapReRoute);
        }

        @Override
        public void onRerouteFailed() {
            super.onRerouteFailed();
            Toast.makeText(getApplicationContext(), "routeFailed", Toast.LENGTH_SHORT).show();

        }
    };

**Comment by manishpatelgt** [comment]
Re Routing happened again and again until you're in correct Route. Check your Route first

**Comment by starand** [comment]
Duplicates https://github.com/heremaps/here-android-sdk-examples/issues/156
