### ISSUE TITLE
Navigation instruction voice turn off/on not working

### ISSUE THREAD

**Issue by manishpatelgt** [heremaps/here-android-sdk-examples#157]
I am trying to turn **OFF** navigation instruction voice 

  ```
    m_audioFlags = m_navigationManager.getEnabledAudioEvents();

   // Disable navigation sounds
    m_navigationManager.setEnabledAudioEvents(EnumSet.noneOf(NavigationManager.AudioEvent.class));

   // Disable traffic avoidance mode as we use pedestrian guidance
    m_navigationManager.setTrafficAvoidanceMode(TrafficAvoidanceMode.DISABLE);
```

And turn is **ON** by using below code
```
// Restore navigation sounds
 if (m_navigationManager != null && m_audioFlags != null) {
     m_navigationManager.setEnabledAudioEvents(m_audioFlags);
     m_audioFlags = null;
  }
```

Sometimes it worked sometimes not. So is there any clear solution for this ?

I am using Here Maps Android Premium SDK v3.8.0.104.

**Comment by Merlin1stHere** [comment]
We can't reproduce this issue. Could you provide an example of an application in which the error is reproduced?

**Comment by manishpatelgt** [comment]
@Merlin1stHere Ignore this. It worked very well. There is minor issue at my end. You can close this issue or i can delete.

BTW is this right solution ?

**Comment by Merlin1stHere** [comment]
@manishpatelgt Yes. This is the right approach.

**Comment by manishpatelgt** [comment]
@Merlin1stHere ok Thanks
