### ISSUE TITLE
Route Manager Class Not found in Freemium Sdk 

### ISSUE THREAD

**Issue by Shruti-Mahajan** [heremaps/here-android-sdk-examples#159]
Hi 
I am using Freemium SDK and wants to draw the route in android. But Route Manager Class not found

Thanks
Please help me.

**Comment by Shruti-Mahajan** [comment]
Thanks For reply I have also used Core Router class 
I am able to import CoreRouter class in the project. When I compiled the project in android studio I  found issues
error: cannot find symbol class core router

**Comment by starand** [comment]
Did you try to compile github sample? Did you copy HERE-sdk.aar into app/libs/ folder?
Which version of Android Studio do you use?

**Comment by Shruti-Mahajan** [comment]
3.1.3 version 
Yes, I have compiled GitHub sample it also giving me same error in GitHub sample.

**Comment by starand** [comment]
Could you please run "./gradlew assemble" command under routing folder and provide output?
Thank you!

**Comment by Shruti-Mahajan** [comment]
new Router.Listener<List<RouteResult>, RoutingError>() {
                          ^
/home/shruti/Downloads/here-android-sdk-examples-master/routing/app/src/main/java/com/here/android/example/routing/MapFragmentView.java:192: error: cannot find symbol
                new Router.Listener<List<RouteResult>, RoutingError>() {
                                                       ^
  symbol:   class RoutingError
  location: class MapFragmentView


Showing Error

**Comment by starand** [comment]
Looks like you are missing import RoutingError class.
Please see whether you have 'import com.here.android.mpa.routing.RoutingError;' at line 34 or add it.

**Comment by Shruti-Mahajan** [comment]
I already have imported all the classes. and I am able to views all the routing classes
But when I compile my code 
It gives errror
not found router manager class

**Comment by Shruti-Mahajan** [comment]
I used starter sdk

**Comment by starand** [comment]
Ok, Starter SDK does have RouteManager (and does not have CoreRouter). Therefore you cannot build routing sample with Starter SDK.
But there is SimpleRoutingSolution sample delivered with Starter SDK package. Please try to build it.

**Comment by Shruti-Mahajan** [comment]
ok Thanks

**Comment by Shruti-Mahajan** [comment]
Can you provide me any link for Simple Routing Sample

**Comment by starand** [comment]
@Shruti-Mahajan,

There is no such github sample app. But it is packed into the same archive as HERE-sdk.aar (you download it from developer portal).

**Comment by Shruti-Mahajan** [comment]
okay, Thanks
