### ISSUE TITLE
Simulation icon is not tied to the map view

### ISSUE THREAD

**Issue by kasparyan** [heremaps/here-android-sdk-examples#160]
When the user starts to simulate the navigation, the gps icon's orientation is changed when the map is rotated by two-finger gesture instead of being tied to the map. The gps icon should react only to the device movements.
Note: the issue is not visible in showcase app, since the gps icon is round.

**Comment by Merlin1stHere** [comment]
Currently, the Android implementation doesn't support orientation for images used as a position indicator. You can use MapLocalModel object as a position indicator and change its position and orientation in the callback OnPositionChangedListener.onPositionUpdated from the PositioningManager. The default position indicator should be hidden (PositionIndicator.setVisible(false)).

**Comment by Merlin1stHere** [comment]
@kasparyan Here is an example how to create 3D object on the map.
https://github.com/heremaps/here-android-sdk-examples/tree/master/3DModel/

**Comment by binod-techindustan** [comment]
@starand we have been using 3D object, but the icon starts flickering when we zoom in or out the map during navigation. After re-centering the map it works normally.
