### ISSUE TITLE
can you provide and example navigation mini overlay like google

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#169]
Google maps has a overlay feature. 
When app minimized appears a maps mini overlay window.

**Comment by silvestrpredko** [comment]
@Xgamefactory Hello, this feature is related to Android SDK. It isn't the capability of Google Maps or Here Maps SDK. I have prepared a rough example with pip usage, here is it - [Picture In Picture sample](https://gist.github.com/silvestrpredko/0d974a94531eacdb1f8bc4c973a36cac)

**Comment by Xgamefactory** [comment]
thanks @silvestrpredko for example.
