### ISSUE TITLE
undocumented Bootreceiver in examples

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#171]
Here we can see a bootreceiver and referenced to docs but search result gives no result on official docs.

![bootsd](https://user-images.githubusercontent.com/22529051/47957901-f23b5880-dfcf-11e8-839f-00207e36b33f.png)

https://github.com/heremaps/here-android-sdk-examples/blob/f0fb5a3999695a9e82e292e90c7953df8665ee39/positioning-venues-and-logging/app/src/main/AndroidManifest.xml

![herebootreceivernotfound](https://user-images.githubusercontent.com/22529051/47957889-a8eb0900-dfcf-11e8-8a5d-2be65b00532e.png)

is there any updated documentation ?

**Comment by starand** [comment]
BootReceiver is used to listen to **onBootCompleted()** callback.
Is used by positioning component to rescan available WiFi.
