### ISSUE TITLE
force mapview render

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#175]
Hi,
We are reusing MapView instance in our application
mapview has different size on different activities we are doing resizing with codes below

```
ViewGroup.LayoutParams params = v.getLayoutParams();
        if(params==null){
            params = new ViewGroup.LayoutParams(w,h);
        }else {
            params.width = w;
            params.height = h;
        }

        v.setX(x);
        v.setY(y);
        v.setLayoutParams(params);

        v.invalidate();//calling invalidate for force view render with new screen sizes
```

But mapview tiles not immediately renders in new size (appears a streched mapview content for small time)

Is there a way to trigger MapView instance to force immediately refresh tiles ?

Thanks.

**Comment by Merlin1stHere** [comment]
@Xgamefactory This behavior will be changed from the version 3.10 of HERE SDK. MapView will be immediately redrawn after resizing.

**Comment by Xgamefactory** [comment]
great news we are actively using old version now after 3.9 you have removed auto offline cache routing and currently we dont have such time for migration. we will make a test and feedback result. 
Thanks.

**Comment by starand** [comment]
Hi @Xgamefactory,
Planned date is about mid of Dec.
