### ISSUE TITLE
please add mapview padding like on mapbox

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#176]
it would be nice to have a mapview padding like mapbox did.

> Sets the distance from the edges of the map view.

this is really usefull especially for set mapbox bounding box with markers. 
here is their opensource mapview.java

https://github.com/mapbox/mapbox-gl-native/blob/1ceea72e6da786537cf3f4038ce56b602c12bfa8/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

**Comment by nsurgeon** [comment]
Hi
could you please provide more detailed description of functionality you want.
It will be nice to see screenshots (or some UI Mocks) as example.

**Comment by Xgamefactory** [comment]
mapbox has a padding feature for mapview. it helps to set bounds with padding smaller to include all markers size. Currently here sdk set bounds method just includes latlngs and markers are not visible in that regiount i mean marker image padding helps to decrease the bounds.

**Comment by nsurgeon** [comment]
Seems I can't understand grasp an idea of improvement. I'll rise this question upper: to Product owner and Architects, etc and hopefully we will be able to implement this in a manner you'd like

If you could provide reference to HERE sample code which implements this feature or if you can build simple example - it would be great and, definitely, speed up process and clarify your requirement.

best regards 
-Andriy

**Comment by starand** [comment]
@Xgamefactory, could you please provide a screenshot of the needed feature?

**Comment by Xgamefactory** [comment]
are you serious ? )

it first screenshot you can see markers not completely visible the mapview bounding box is larger
with setting padding like mapbox does bounding box is reduced and all markers are visible as on second screenshot.

I Hope you will not ask to describe the bounding box heremaps already has it. Also i gave stackoverflow link with similar issues.

![image 001](https://user-images.githubusercontent.com/22529051/48955509-49917080-ef5f-11e8-98f2-92458ea58445.png)


![image 002](https://user-images.githubusercontent.com/22529051/48955508-49917080-ef5f-11e8-892d-04e6289da291.png)

**Comment by nsurgeon** [comment]
thank you for suggesting improvement, we will proceed this with our product manager.

best regards
-andriy

**Comment by Xgamefactory** [comment]
hm. that is very bad (

**Comment by starand** [comment]
@Xgamefactory, right place to ask for new features is TCS. Please talk to them.
Thank you!

**Comment by starand** [comment]
ok, management was informed and in case it is approved, we will add the feature in 3.11.
Closing as this is a feature, not an issue.

**Comment by starand** [comment]
@Xgamefactory,
The feature will be implemented in scope of 3.11 release.

**Comment by NazarKacharaba** [comment]
@Xgamefactory it is possible to navigate to a set of `MapMarker`s with predefined viewport size even in pre 3.11 release. See sample [here](https://github.com/heremaps/here-android-sdk-examples/blob/master/map-objects/app/src/main/java/com/here/android/example/map/objects/MapFragmentView.java#L296L320)

Method `Map.setPadding(...)` is added in 3.11, but it should not be used for `MapMarker`s padding, but rather to define invisible area of the map around `MapView`(e.g. custom user views that obscure `MapView` etc.)

**Comment by Xgamefactory** [comment]
@NazarKacharaba  we will try this example looks like a solution. thanks.

**Comment by Xgamefactory** [comment]
it would be nice to have zoomTo method with viewrect in starter sdk too
