### ISSUE TITLE
 Custom InfoWindow on top of Marker using MapOverlay issue in premium pack.

### ISSUE THREAD

**Issue by parmarravi** [heremaps/here-android-sdk-examples#180]
I am trying to display custom info window on top of the marker using map overlay but i am not able to put it on top of the marker.

 There is one  more issue while using map overlay. if i turn the visibility of infoWindow view off , while   zooming the  map info window appears .I tried to invisible the infoView when user is zooming but its not working.

The info window animates when zooming the map .I Dont want this thing too happen . How to prevent this also?
```

 @Override
        public boolean onMapObjectsSelected(List<ViewObject> objects) {
            for (ViewObject object : objects) {
                if (object.getBaseType() == ViewObject.Type.USER_OBJECT && ((MapObject) object).getType() == MapObject.Type.MARKER) {
                    MapMarker mapMarker = (MapMarker) object;
                    if (!isMapMarkerViewVisible()) {
                        if (mapMarker.getTitle() != null) {
                            if (!mapMarker.getTitle().equals(""))
                                new Handler(Looper.getMainLooper()).post(new Runnable() {
                                    @Override
                                    public void run() {
                                        setInfoWindow(mapMarker);
                                    }
                                });
                        }
                    } else {

                        new Handler(Looper.getMainLooper()).post(new Runnable() {
                            @Override
                            public void run() {
                                removeInfoWindow();
                            }
                        });
                    }
                    return true;
                }        }

            return false;
        }

        @Override
        public boolean onTapEvent(PointF pointF) {
            for (MapObject mapObject : mapObjects) {
                if (mapObject.getType() == MapObject.Type.MARKER) {
                    //((MapMarker) mapObject).hideInfoBubble();
                    new Handler(Looper.getMainLooper()).post(new Runnable() {
                        @Override
                        public void run() {
                            removeInfoWindow();
                        }
                    });
                }
            }
            return super.onTapEvent(pointF);
        }

        @Override
        public boolean onPinchZoomEvent(float v, PointF pointF) {
            new Handler(Looper.getMainLooper()).post(new Runnable() {
                @Override
                public void run() {
                    if (infoWindowView.getVisibility() == View.VISIBLE) {
                        infoWindowView.setVisibility(View.VISIBLE);
                    } else {
                        infoWindowView.setVisibility(View.GONE);
                    }
                }
            });
            return false;
        }
    };
private void setInfoWindow(MapMarker mMark) {
        if(mapOverlay!=null) {
            hereMap.removeMapOverlay(mapOverlay);
            mapOverlay = null;
        }
        infoWindowText.setText(mMark.getTitle());
        infoWindowText.setTag(mMark.getTitle());
        mapOverlay = new MapOverlay(infoWindowView, mMark.getCoordinate());
        mapOverlay.setAnchorPoint(new PointF(80.0f, 150.0f));
        hereMap.addMapOverlay(mapOverlay);
    }

    private boolean isMapMarkerViewVisible() {
        return infoWindowView.getVisibility() == View.VISIBLE;
    }

    private void removeInfoWindow() {
        if (infoWindowView != null) {
            if (infoWindowView.getVisibility() == View.VISIBLE) {
                infoWindowView.setVisibility(View.GONE);
            }
        }


```

**Comment by Merlin1stHere** [comment]
Hello, @parmarravi 
I can't reproduce the issue with position of MapOverlay object. Looks like setAnchorPoint API works fine, but you should take to account height of your MapOverlay view.
SDK turns on/off visibility of MapOverlay view during map panning. It hides views if they gone from the visible map area and shows they if that is needed. This behaviour by design. If you want to hide a MapOverlay object just remove it from the map.
I not fully understand what do you mean when you tell about animation of view. Do you mean flickering? Try to remove code from onPinchZoomEvent.

**Comment by parmarravi** [comment]
Thank you for replying @**Merlin1stHere**  .
Yes i mean **flickering**  and also the position of anchor is not constant in all the mobile display .
It is **moved** to  **left** or **right** slightly depending on  **Screen size** and i am **not able** to put it in the **centre** of the **marker** 
i have tried this code that converts dpi to ppi but its not giving the results that i was able to achieve with showInfoBubble.

There is a strange effect on the view too .if i remove the code from onPinchZoomEvent . it looks like when zooming on the view ,the mapOverlay is redrawed on the map this makes  the mapOverlay visible again.


 ```
public static int dpToPx(int dp) {
        return (int) (dp * Resources.getSystem().getDisplayMetrics().density);
    }

  private void setInfoWindow(MapMarker mMark) {
        if (mapOverlay != null) {
            hereMap.removeMapOverlay(mapOverlay);
            mapOverlay = null;
        }

        infoWindowText.setText(mMark.getTitle());
        infoWindowText.setTag(mMark.getTitle());
        mapOverlay = new MapOverlay(infoWindowView, mMark.getCoordinate());
        //dp to pixel
        int paddingX = dpToPx(35);
        int paddingY = dpToPx(50);

        PointF pointF = new PointF(mMark.getAnchorPoint().x + paddingX, mMark.getAnchorPoint().y + paddingY);
        mapOverlay.setAnchorPoint(pointF);
        hereMap.addMapOverlay(mapOverlay);
    }
```

**Comment by Merlin1stHere** [comment]
@parmarravi 
You should take to account your view width and height (getMeasuredHeight/getMeasuredHeight) to place your MapOverlay on right place.
You shouldn't use view's visibility status to manage visibility of the MapOverlay object. If you wan't hide MapOverlay from map you should use Map.removeMapOverlay method.

**Comment by parmarravi** [comment]
Thank you for the reply .

**Comment by parmarravi** [comment]
I still have doubt in placing the  custom marker window on the marker. It behaves differently on different  screen . 
```
 mapOverlay = new MapOverlay(infoWindowView, mMark.getCoordinate());
        int paddingX = Miscellaneous.dpToPx(35);
        int paddingY = Miscellaneous.dpToPx(50);
        PointF pointF = new PointF(mMark.getAnchorPoint().x + paddingX, mMark.getAnchorPoint().y + paddingY);
        mapOverlay.setAnchorPoint(pointF);
```
Where dp to px is 
```

    public static int dpToPx(int dp) {
        return (int) (dp * Resources.getSystem().getDisplayMetrics().density);
    }
```
Can you  please suggest how to achieve the results same as infoBubble that was deprecated .

**Comment by parmarravi** [comment]
The Custom info window position with respect to marker is different with respect to different display's.
In Google pixel it show's the position of Info Window more above to marker while in mobile phone that has smaller display shows info window on top of marker or over the  marker . It looks like Vertical spacing is different for different screen and is not been maintained . The InfoBubble that was present previously always had proper spacing with respect to marker in map across all the devices.

**Comment by Merlin1stHere** [comment]
@parmarravi As I mentioned before, if you want to place your view above the marker you have to take to account dimensions of your view. Pixel dimensions of android views depend on pixel density of the device.

**Comment by parmarravi** [comment]
okay @Merlin1stHere  can you please let me know how could i solve this issue?

**Comment by Merlin1stHere** [comment]
paddingX = infoWindowView.getMeasuredWidth() + Miscellaneous.dpToPx(35);
paddingY = infoWindowView.getMeasuredHeight() + Miscellaneous.dpToPx(50);

**Comment by parmarravi** [comment]
Thank you
