### ISSUE TITLE
android sdk 3.9 getTtaIncludingTraffic is same as getTtaExcludingTraffic

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#184]
`getTtaIncludingTraffic(Route.WHOLE_ROUTE).getDuration()`
is same as 
`getTtaExcludingTraffic(Route.WHOLE_ROUTE).getDuration()`

on ios this works correctly even on old versions.

what is the catch ? is it a bug ?

**Comment by Xgamefactory** [comment]
need to add Dynamic penalty to coreRouter

why  is  routeType is not enough ? does it for traffic data ?

`routeOptions.setRouteType(RouteOptions.Type.BALANCED);`

**Comment by Merlin1stHere** [comment]
RouteType just selects algorithm is used for route calculation on an existing data (speed limit, distances, traffic penalty if it is set). If you want to take into account traffic conditions you should set Dynamic penalty for CoreRouter.

**Comment by starand** [comment]
@Xgamefactory did you get answer? Was your issue solved?

**Comment by Xgamefactory** [comment]
yes i have already commented that need to add Dynamic penalty for traffic data.
closing the issue.
