### ISSUE TITLE
Why MapView is not working

### ISSUE THREAD

**Issue by TostF** [heremaps/here-android-sdk-examples#185]
Hi! 
Can anyone tell me why I need to set Map on MapView in order to set Map parameters like zoom or center?

```
private fun initMap() {
         MapEngine.getInstance().init(context) { error ->`
            when (error) {
                NONE -> {
                    map = Map()
                    mapView.map = map
                    map.setCenter(GeoCoordinate(51.919438, 19.145136), Animation.NONE)
                    map.zoomLevel = map.minZoomLevel + map.maxZoomLevel / 2
                }
                else -> context?.showToast(R.string.error_map_init)
            }
        }
    }
```
When I switch position of `mapView.map = map` and move it below `map.zoomLevel` my init is crashing with `Attempt to invoke interface method 'void com.here.android.mpa.internal.br.c()' on a null object reference`. Can you explain me how this is the case? Is setting map on MapView makes MapEngine somehow load data? Unfortunately the code is obfuscated and I cannot reverse-engineer it :C 

Thanks for help!

**Comment by Merlin1stHere** [comment]
Hi, @TostF 
I can't reproduce the issue. Which version of SDK do you use?

**Comment by TostF** [comment]
Hio It's 3.9_18 according to file name.

**Comment by Merlin1stHere** [comment]
I still can't reproduce the issue. Could you check the latest release of SDK (3.9.0_99)? If the issue is still reproduced, could you provide a full example that reproduces it?

**Comment by TostF** [comment]
Where I can download this SDK? I've downloaded mine from project management page and I can't find any other source.

**Comment by Merlin1stHere** [comment]
Try to download again. I'm not sure, but I think this page always provides url to the latest available version.

**Comment by starand** [comment]
@TostF, you can download it from https://developer.here.com/develop/mobile-sdks

**Comment by TostF** [comment]
Oh, ok version 3.9.0_99 is hidden under "premium" SDK. That was not obvious :P

**Comment by TostF** [comment]
It stopped working at all. According to this lib there is not `ApplicationContext` class in it and yet it requires `ApplicationContext` to create `MapEngine` instance.

`Type mismatch: inferred type is Context but ApplicationContext! was expected`

**Comment by Merlin1stHere** [comment]
@TostF 

import com.here.android.mpa.common.ApplicationContext;

and

ApplicationContext context = new ApplicationContext(getApplicationContext());
MapEngine.getInstance().init(context ....

**Comment by TostF** [comment]
I did just that and got info about "Unresolved inport" as if there was no `ApplicationContext` class to refer to.
![Like this](https://user-images.githubusercontent.com/7777787/49582286-d3284180-f954-11e8-998c-f5771eeda23d.png)

**Comment by Merlin1stHere** [comment]
It seems like you still use old library. Not premium SDK.

**Comment by TostF** [comment]
Free library is around 4mb while premium is almost 64mb. I do have the right library. I've also cleaned and rebuilt the project multiple times.
![image](https://user-images.githubusercontent.com/7777787/49583428-7c246b80-f958-11e8-849b-aaa58c915fa7.png)

**Comment by TostF** [comment]
@Merlin1stHere crazy.... AndroidStudio did not clear data at all. Had to remove gradle import, file ect. Then clean -> rebuild and now I do have it. Thanks for help, I will try to run it now.

**Comment by TostF** [comment]
Conversion to offline map is too big of a hassle as of now. Seems like I'm getting locked by lots of errors to features I don't need at all. Closing this thread because it became to big waste of time to dig into this.
Thanks for help @Merlin1stHere
