### ISSUE TITLE
Markers disappear

### ISSUE THREAD

**Issue by TostF** [heremaps/here-android-sdk-examples#186]
I've added `MapLabeledMarker` to map and as long there are no nearby names of roads, cities, countries then the markers stays visible. But the moment one of the above get in the way of the marker it disappears. 
Is that HERE SDK issue or is it implementation problem?
Is there a way to increase prio on markers so that they won't disappear?

How I add markers at the moment:
```
 override fun showMarkers(markers: List<Marker>) {
        val mapObjects = arrayListOf<MapObject>()
        val coordinates = arrayListOf<GeoCoordinate>()
        markers.forEach { marker ->

            val geoCoordinate = GeoCoordinate(marker.getLatLng().latitude, marker.getLatLng().longitude)
            val mapMarker = MapLabeledMarker(geoCoordinate, selectMarkerIcon(marker.getType()))
            mapMarker.setLabelText("pol", marker.getMarkerId())
            mapMarker.isOverlappingEnabled = true
            mapMarker.isDeclutteringEnabled = false
            mapMarker.isVisible = true

            mapObjects.add(mapMarker)
            coordinates.add(geoCoordinate)
        }
        map.addMapObjects(mapObjects)
        focusOnCoordinates(coordinates)
    }
```

**Comment by TostF** [comment]
**UPDATE**
I've managed to make markers not disappear by switching `reserveOverlayType` to `BACKGROUND_OVERLAY` - I don't know if that is proper way.
The labels however are still disappearing all the time (just like I wrote in previous post).
Any Idea how to fix that?

**Comment by Merlin1stHere** [comment]
This is default behavior by design. Drawing of MapLabeledMarker has the same logic as POI. Names of roads, cities, countries always have higher priority. Please consider to use the MapOverlay object.

**Comment by TostF** [comment]
No, thanks. I will close the issue.
