### ISSUE TITLE
here gives long routing

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#188]
![herelongdistance_routing_2](https://user-images.githubusercontent.com/22529051/49700022-2f57c380-fbea-11e8-9be8-6c86c93b0f9b.png)

there is 10km difference between heres offered road.
After driver ignores and conitnues drive on right image you can see 10km shorter road with only 3minutes longer routing.

**Comment by Merlin1stHere** [comment]
What the route type has been set in the RouteOptions? Default value is FASTEST.

**Comment by starand** [comment]
@Xgamefactory, did you get the answer to your problem?

**Comment by askarali** [comment]
Even I too found the issue in my application. RouteOptions is FASTEST only

**Comment by starand** [comment]
@askarali that is not a problem. That is default behavior. If you want to can use SHORTEST route type as well:
```
        RoutePlan routePlan = new RoutePlan();
        
        RouteOptions routeOptions = new RouteOptions();
        routeOptions.setRouteType(RouteOptions.Type.SHORTEST);
        
        routePlan.setRouteOptions(routeOptions);
```

**Comment by starand** [comment]
Does it work for you? If no updates, I will close the issue.

**Comment by starand** [comment]
@Xgamefactory did you solve the original problem?

**Comment by starand** [comment]
ok, looks like the original problem was solved. Closing this issue.
