### ISSUE TITLE
MapView not redrawing when fragment gets replaced

### ISSUE THREAD

**Issue by TostF** [heremaps/here-android-sdk-examples#191]
I've `MapView` in `FragmentWithMap` that is a part of `ViewPager`. When I replace `FragmentWithViewPager` that holds `ViewPager` with some other `FragmentReplacer` and return via `PopBackstack` my map does not get redrawn.
Why is this happening?

I am triggering `mapView.onPause()` and `mapView.onResume()` in fragment lifecycle methods but it does not help. I've read that I should check if `MapEngine` is initialised and trigger `onResume()` only then but it did not help either.

What am I doing wrong?

I was looking for example of `MapView` being used in samples repository but all all of them includes `MapFragment` (which I would rather not use).

**Comment by TostF** [comment]
I would be great if you could provide a sample code of `MapView` implementation so I can check if I'm properly managing `MapEngine`.

**Comment by NazarKacharaba** [comment]
This issue is fixed in 3.10 release which will be out soon, probably next week.

**Comment by TostF** [comment]
Is `MapView` example possible tough? I have major performance issues when adding another map instance on view stack.
