### ISSUE TITLE
NavigationManager.RerouteListener()  Not Calling

### ISSUE THREAD

**Issue by askaralic** [heremaps/here-android-sdk-examples#193]
I want to redraw the route once i deviated from the planned route .I have added RerouteListener as below but it is not triggering 
I have used new PositioningManager.OnPositionChangedListener() also to update the current location marker 
```
NavigationManager.getInstance().addRerouteListener(new WeakReference<>(new NavigationManager.RerouteListener() {
            @Override
            public void onRerouteBegin() {
                Toast.makeText(getApplicationContext(), "reroute begin", Toast.LENGTH_SHORT).show();
                super.onRerouteBegin();
            }

            @Override
            public void onRerouteEnd(RouteResult route){
                Toast.makeText(getApplicationContext(), "reroute end", Toast.LENGTH_SHORT).show();
                super.onRerouteEnd(route);
            }
            @Override
            public void onRerouteFailed() {
                Toast.makeText(getApplicationContext(), "routeFailed", Toast.LENGTH_SHORT).show();
                super.onRerouteFailed();

            }
        }));
```

**Comment by askarali** [comment]
But here in your documents, you mentioned as a weak reference only. In fact, I have many listeners which is calling as weak references how GC will kill only this listener?

**Comment by starand** [comment]
Ok, we added a note about that issue in Developer's Guide 3.10 (check for it tomorrow).
In fact, that is common Java problem - you have to hold a reference on object to keep from being deleted by GC. That is not an SDK issue.

**Comment by askarali** [comment]
Noted !. But everywhere in your document as well as sample code has used the same weak reference. That's why we used weak references. I will try with the strong reference and let you know

**Comment by starand** [comment]
@askarali, ok, please let us know whether you fixed your issue.

**Comment by starand** [comment]
Was your issue solved?
