### ISSUE TITLE
import com.here.android.mpa.mapping.SupportMapFragment; Not found in SDK version 3.10

### ISSUE THREAD

**Issue by askarali** [heremaps/here-android-sdk-examples#197]
I have replaced my HERE-sdk.aar in libfile but i couldnt find out the
 import com.here.android.mpa.mapping.SupportMapFragment this class .
Downloaded SDK version 3.10

**Comment by starand** [comment]
How did you download? Could you provide a link?
We did update HERE-sdk.aar two days ago, and verified whether github samples are buildable. All github samples were updated yesterday. They refer to SupportMapFragment, and there are no compilation issues. Please double check.

**Comment by askarali** [comment]
Downloaded from : https://developer.here.com/delivery-service/product/2/app/96EhaIzRfNDLSUI99QPM/download

Version.getSdkVersion() = 3.10.0.85

**Comment by starand** [comment]
I just double checked - BasicMapSolution (tutorial app included in the package) compiles without errors.
Try to compile BasicMapSolution and make sure you copy HERE-sdk.aar into proper place. Copy HERE-sdk.aar from sdk/HERE-sdk/libs/ folder into sdk/HERE-sdk/tutorial/BasicMapSolution/app/libs/ folder (create libs folder under BasicMapSolution/app/libs/ if not exists).

**Comment by askarali** [comment]
after i run my application i printed this value : Version.getSdkVersion() = 3.10.0.85 . If SDK is not updated this new version wont come right ?Could you please provide  SDK URL which you are using now so i can download and try directly

**Comment by starand** [comment]
Looks like you have the proper one. The only way to get is to download from Developers Portal.
The archive size should be about 112.4 Mb.

**Comment by askarali** [comment]
![here size](https://user-images.githubusercontent.com/3763280/50208695-4be2c100-038b-11e9-936c-18b7297a7d0e.PNG)

It is in different size

**Comment by starand** [comment]
ok, seems you did not download the whole archive. Try to download once again and double check.

**Comment by askarali** [comment]
Still the package size showing as 107 MB

**Comment by starand** [comment]
Did you try to build BasicMapSolution from this archive?

**Comment by askarali** [comment]
No i am using my application

**Comment by starand** [comment]
Please do that. We do not see such issue with all github samples, with tutorial apps and our test apps.
It is more likely you did not replace HERE-sdk.aar, or did not clean previous build, or put HERE-sdk.aar into wrong place.
What I can recommend is - clean your project. Find and delete all versions of HERE-sdk.aar. Then take new one from dowbloaded archive and put it under <YOUR_APP>/app/libs/ folder. Then recompile.
If this does not help, please prepare sample app, where the problem is easily reproduced and shre code with us.

**Comment by askarali** [comment]
I did clean project and rebuild also . even in code level it shows the new SDK version, it means the new SDK is linked to the app. But when I have closed all the project and restarted the application it started working fine

**Comment by natvar97** [comment]
You should use :

class="com.here.android.mpa.mapping.AndroidXMapFragment" in fragment 

it work for me and error gone in xml file
