### ISSUE TITLE
Is there a limit on number of waypoints that can be added in Route Plan?

### ISSUE THREAD

**Issue by paramtrivedi** [heremaps/here-android-sdk-examples#20]
While creating the Route Plan, Does the SDK has a limit on number of waypoints that a route can have? We are working on an application which will be creating the route with approximately 1000 waypoints in a 28 KM. Is it feasible?

**Comment by JH-YVR** [comment]
The maximum number of waypoints supported is 128.

**Comment by paramtrivedi** [comment]
Is there a way to increase this limit?

**Comment by JH-YVR** [comment]
Unfortunately not. This limit is enforced in the SDK. Of course, the limit may be increased in future releases but currently no change is planned.

**Comment by sschuberth** [comment]
Closing as this seems to answer the question. Thanks @JH-YVR!
