### ISSUE TITLE
java.net.SocketTimeoutException: failed to connect to static.bundles.hybrid.cc.api.here.com/23.207.89.23 (port 443) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by askarali** [heremaps/here-android-sdk-examples#201]
I am getting this error sometimes. After I exit the application many times this error got disappearing. We cannot reproduce it but most of the time it is happening. I am trying on Android Pie

**Comment by starand** [comment]
Thank you! We are looking on this. The issue happens because of network problem.

**Comment by askarali** [comment]
I would like to add one more things to my question that I was tested in a stable wifi connection. the chances of network interruption are 0.1 %.

**Comment by starand** [comment]
@askarali we use standard Android classes to work with network. Therefore if SocketTimeoutException happens it is generated by Android library and is not related to SDK sources. This should be network issue (or Android which is very unlikely).
Any way, we updated the message for the case. As we can do nothing on our side with the issue we are going to close it.
