### ISSUE TITLE
lastest sdk not initialized with MapFragment not SupportFragment.

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#204]
Hi,
is it possible to use sdk 3.10 without Supportfragment ?
but OnEngineInitListener just not called with no errors.
it declared as deprecated but shouldnt't it work ?

where can we download old sdk releases ? we have found documentations but no download link.

https://developer.here.com/documentation/versions#ios-hybrid-plus

**Comment by NazarKacharaba** [comment]
Hi @Xgamefactory 
Please explain what exactly does not work, `SupportMapFragment` or `MapFragment`? Share yours code that shows bug.
`MapFragment` is now deprecated but it should receive `onEngineInitializationCompleted` callback and it actually does in my test app.

**Comment by Xgamefactory** [comment]
hi the problem was on our side we forget to include  libanalytics_jni.so
the name sound like just analytics note a core map library )
