### ISSUE TITLE
Voice Instruction Audio not Playing

### ISSUE THREAD

**Issue by Asma-Yasin** [heremaps/here-android-sdk-examples#206]
As per the user guide for having voice instructions while navigation, I'm downloading the voice catalog and then I'm downloading the voice skin I want.

To optimize my code, first I check if the catalog is already downloaded using `VoiceCatalog.isLocalCatalogAvailable()`. Then I check if the voice skin is there using `VoiceCatalog.isLocalVoiceSkin(id)` and if the voice package is locally installed using `VoicePackage.isLocal()`. Whenever the value returns false, I go download the missing files as mentioned in the guide.

This is working fine for me and the voice instructions are playing normally in most cases. However, sometimes when I wait for these files to download and then kill the application midway (about 30 second after the start of this process), all the above methods return true but the voice instructions don't really come.

I even checked the files physically and found them all in the device. This behavior happens if the download process was interrupted in its final stages. Killing the process when it's just started (0-15 secs) will work fine and the methods will return false as expected.

Please let me know if I'm doing something wrong and tell me why these methods return true when the voice packages are not installed correctly.

**Comment by starand** [comment]
Hi @Asma-Yasin,
Thank you for the issue report! We did reproduce and looking into it.

**Comment by starand** [comment]
Hi @Asma-Yasin,
The issue is already fixed and the fix should be included in SDK 3.11. Estimated release day is 1st of Apr.
