### ISSUE TITLE
onEngineInitializationCompleted throws UNKNOWN error randomly.

### ISSUE THREAD

**Issue by rsd96** [heremaps/here-android-sdk-examples#207]
The mapview seems to load perfectly in most cases but at rare times it throws UNKNOWN error. Not sure if this is sdk issue or caused by something else but better error reporting would be very helpful nonetheless.

**Comment by starand** [comment]
Hi @rsd96,

That error can happen when you try to init map from background. If you need more details, in void onEngineInitializationCompleted(Error error), try error.getDetails() and error.getStackTrace().

Does it help?

**Comment by rsd96** [comment]
Thanks for the quick reply. The map is not loaded in background and error.getDetails() says "unknown error occurred during engine init" which isn't all that helpful either.

**Comment by starand** [comment]
Hi @rsd96 was your issue solved?

**Comment by IRTCareonTime** [comment]
yes, thanks for your help. The error was caused by initializing map engine at two different locations and at times they happened to be at the same time.

**Comment by rsd96** [comment]
yes, thanks for your help. The error was caused by initializing map engine at two different locations and at times they happened to be at the same time.
