### ISSUE TITLE
Voice Navigation in different languages

### ISSUE THREAD

**Issue by kiskunk** [heremaps/here-android-sdk-examples#211]
The VoiceSkin is deprecated. When I use the turn-by-turn navigation demo, it just beeps, no voice given. The deprecated voicecatalog cannot download voices.
How can I use a voice (prefererably other than english/default) in turn-by-turn?

**Comment by Merlin1stHere** [comment]
Hello, @kiskunk!
Why do you say that VoiceSkin and VoiceCatalog are deprecated?
Please refer the documentation page https://developer.here.com/documentation/android-premium/dev_guide/topics/map-voice-instructions.html for information how to use VoiceCatalog and VoiceSkin classes.

**Comment by kiskunk** [comment]
[http://oi68.tinypic.com/a0ywpu.jpg](Because this)

**Comment by starand** [comment]
@kiskunk which version of SDK do you use?

**Comment by kiskunk** [comment]
> @kiskunk which version of SDK do you use?

I just registered a new account/plan, and downloaded from their website a week ago. (Android Premium)

**Comment by starand** [comment]
ok, please use VoiceGuidanceOptions instead.

```
VoiceGuidanceOptions voiceGuidanceOptions =
                NavigationManager.getInstance().getVoiceGuidanceOptions();
voiceGuidanceOptions.setVoiceSkin(voiceSkin);
```

**Comment by kiskunk** [comment]
> ok, please use **VoiceGuidanceOptions** instead.
> 
> ```
> VoiceGuidanceOptions voiceGuidanceOptions =
>                 NavigationManager.getInstance().getVoiceGuidanceOptions();
> voiceGuidanceOptions.setVoiceSkin(voiceSkin);
> ```

Tried thanks, now my new problem is after downloading the voice catalog and selecting the proper id, then trying to download that voice pack, it always gives back: Error.UNKNOWN

       final VoiceCatalog voiceCatalog = VoiceCatalog.getInstance();
        voiceCatalog.downloadCatalog(new VoiceCatalog.OnDownloadDoneListener() {
            @Override
            public void onDownloadDone(VoiceCatalog.Error error) {
                if (error == VoiceCatalog.Error.NONE) {
                    List<VoicePackage> voicePackages = VoiceCatalog.getInstance().getCatalogList();

                    long id = -1;
                    for (VoicePackage vPackage : voicePackages) {
                        if (vPackage.getMarcCode().compareToIgnoreCase("hun") == 0) {
                            //if (vPackage.isTts()) {
                            id = vPackage.getId();
                            break;
                            //}
                        }
                    }

                    if (!voiceCatalog.isLocalVoiceSkin(id)) {
                        final long finalId = id;
                        voiceCatalog.downloadVoice(id, new VoiceCatalog.OnDownloadDoneListener() {
                            @Override
                            public void onDownloadDone(VoiceCatalog.Error error) {
                                if (error == VoiceCatalog.Error.NONE) {
                                    VoiceGuidanceOptions voiceGuidanceOptions = m_navigationManager.getVoiceGuidanceOptions();
                                    voiceGuidanceOptions.setVoiceSkin(voiceCatalog.getLocalVoiceSkin(finalId));

                                } //this is where it gives back Error.UNKNOWN, all previous requests are successful
                            }
                        });
                    }
                }
            }
        });

**Comment by starand** [comment]
As a quick hint, try to refresh voice catalog if error happens, then try load again.
`voiceCatalog.refreshVoiceSkins();`
Does it help?

**Comment by starand** [comment]
No feedback for 15 days. Closing the ticket.

**Comment by indexer** [comment]
@starand I download the Voice Catalog and set the voice skin but it does not play Android, just only beeps when navigation , when i checked with vPackage.isTts() is true but .isTtsLanguageAvailable is false , so my android app only available beep song , how can i fixed this issue 

Regards,
Ye

**Comment by NazarKacharaba** [comment]
Voice instructions are available through downloadable text-to-speech (TTS) and pre-recorded voice skins. If you want to use TTS, your phone must have TTS engine that supports your language. If calling  `isTtsLanguageAvailable` returns `false` then check phone settings, maybe it is possible to change/configure TTS engine. Otherwise, use pre-recorded voice skins that does not require TTS engine.

**Comment by indexer** [comment]
@NazarKacharaba how can i check which voice skins id does not need TTS engine ,currently i am using pixel 3 and using Google Text-to-speech Engine , voicecatalog.istts = true but it also can't play with default google text to speech engine

**Comment by NazarKacharaba** [comment]
Note that SDK has DevGuide documentation, it is all written there.

Before download you can use `VoicePackage.isTts()`, it should be `false`(it means that it does not require TTS engine) or after voice package has been downloaded check if voice skin output is AUDIO and not TTS:
```
List<VoiceSkin> skins = VoiceCatalog.getLocalVoiceSkins();
// in loop
OutputType type = skin.getOutputType(); // should be AUDIO.
```
