### ISSUE TITLE
Disable beeping and ringing

### ISSUE THREAD

**Issue by kiskunk** [heremaps/here-android-sdk-examples#213]
When I start turn-by-turn navigation since it doesn't support hungarian, the app makes ringing and beeping noises (supposedly to indicate turns). I would like to turn them off.

What I tried without success
-setting the navigationmanager audio volume to 0f
-calling navigationmanager.audio.stop
-navigationManager.setEnabledAudioEvents(EnumSet.noneOf(NavigationManager.AudioEvent.class));

I need to be able to turn off those beeps without turning off the device's volume.

**Comment by Merlin1stHere** [comment]
Hi @kiskunk!
I've checked NavigationManager.setVolume and it works as expected. If I call it with 0 as parameter no more sounds is played.

**Comment by Xgamefactory** [comment]
NavigationManager.getAudioPlayer().setVolume(0) not mute sound immediately.

**Comment by Merlin1stHere** [comment]
@Xgamefactory 
To stop sound immediately you should call 
NavigationManager.getAudioPlayer().setVolume(0) and NavigationManager.getAudioPlayer().stop() functions together.

**Comment by starand** [comment]
Hi @Xgamefactory, is there any updates?

**Comment by Xgamefactory** [comment]
hi yes we can stop sound but sound wont play anymore. we need something toggling mute sound.

**Comment by Merlin1stHere** [comment]
@Xgamefactory Call NavigationManager.getAudioPlayer().setVolume(100) and the next audio event should be played. SDK doesn't provide API to mute/unmute current playing voice.

**Comment by starand** [comment]
@Xgamefactory 
Did you solve the problem?
