### ISSUE TITLE
Mapscheme rendered above markers and other map objects

### ISSUE THREAD

**Issue by rsd96** [heremaps/here-android-sdk-examples#214]
Setting a custom mapscheme, it seems to render on top of existing markers on some devices. So far I have noticed this behavious in Oneplus 5t and Samsung Note 9. The zoom level of the map seems to affect this issue as well, when i tried too zoom out really far it seems to work fine but zooming in again brings back the issue. 

![screenshot_20190207-110052](https://user-images.githubusercontent.com/24352826/53144282-bfa18400-35ef-11e9-9788-84b3994806d5.jpg)

**Comment by NazarKacharaba** [comment]
Could you share your code that you use to set map scheme and its customization, please?

**Comment by rsd96** [comment]
`
                if (map != null && map.getCustomizableScheme(floatSchemeName) == null) {
                    map.createCustomizableScheme(floatSchemeName, map.mapScheme)
                    var scheme = map.getCustomizableScheme(floatSchemeName)

                    val range = ZoomRange(map.minZoomLevel, map.maxZoomLevel)

                    if (scheme != null) {
                        val items = listOf(CustomizableVariables.Land.COLOR, CustomizableVariables.BuiltupArea.COLOR, CustomizableVariables.HarborArea.COLOR, CustomizableVariables.AirportArea.COLOR, CustomizableVariables.PedestrianArea.COLOR)
                        for (property in items) {
                            val color = Color.argb(1, 253, 245, 226)
                            scheme.setVariableValue(property, color, range)
                        }

                        val roadItems = listOf(CustomizableVariables.Street.CATEGORY0_COLOR, CustomizableVariables.Street.CATEGORY1_COLOR, CustomizableVariables.Street.CATEGORY2_COLOR, CustomizableVariables.Street.CATEGORY0_THINCOLOR, CustomizableVariables.Street.CATEGORY1_THINCOLOR, CustomizableVariables.Street.CATEGORY2_THINCOLOR)
                        for (property in roadItems) {
                            val color = Color.argb(1, 255, 242, 175)
                            scheme.setVariableValue(property, color, range)
                        }

                        val roadOutlineItems = listOf(CustomizableVariables.Street.CATEGORY0_OUTLINECOLOR, CustomizableVariables.Street.CATEGORY1_OUTLINECOLOR, CustomizableVariables.Street.CATEGORY2_OUTLINECOLOR)
                        for (property in roadOutlineItems) {
                            val color = Color.argb(1, 232, 232, 232)
                            scheme.setVariableValue(property, color, range)
                        }

                        scheme.setVariableValue(CustomizableVariables.Building.COLOR, Color.parseColor("#e8e8e8"), range)

                        map.setMapScheme(scheme)
                    }
                }
`


I call this function inside onEngineInitializationCompleted.

**Comment by NazarKacharaba** [comment]
What is name of your base scheme in this method `createCustomizableScheme(newSchemeName, baseSchemeName)`?

**Comment by rsd96** [comment]
I'm getting the existing mapscheme for the base. 
`
var floatSchemeName = "CUSTOM-Scheme"`
`map.createCustomizableScheme(floatSchemeName, map.mapScheme)`

**Comment by NazarKacharaba** [comment]
>Color.argb(1, 253, 245, 226)

Is that intentional that `alpha` is 1? It most probably should be 255 as `alpha` range for this method is [0, 255]

**Comment by rsd96** [comment]
Thank you. Changing the alpha value to 255 fixed the issue. Strange how this was causing problems in only a few devices though.
