### ISSUE TITLE
Marker with title baloon.

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#215]
Hi,
how can we achive marker object with title adove. there was that support before i guess.
Something like MarkerView with title textview and icon.

**Comment by NazarKacharaba** [comment]
You can use `MapOverlay` class for that. See `Map.addMapOverlay(MapOverlay overlay);`

**Comment by Xgamefactory** [comment]
using mapoverlay for every marker ?

**Comment by NazarKacharaba** [comment]
Yes, It is not entirely straightforward, but in the end you can achieve that by applying padding to the view. SDK does not have another API to show info bubble for `MapMarker`.
