### ISSUE TITLE
Maneuver is not visible

### ISSUE THREAD

**Issue by Natraj21** [heremaps/here-android-sdk-examples#216]
I'm trying to implement turn by turn navigation using here sdk-3.10.0.96.
Enabled mapRoute.setManeuverNumberVisible(true); and implemented Listeners.... please could you share working turn by turn navigation example....

NavigationManager.getInstance().addNewInstructionEventListener(new WeakReference<NavigationManager.NewInstructionEventListener>(new NavigationManager.NewInstructionEventListener() {
                                                @Override
                                                public void onNewInstructionEvent() {
                                                    super.onNewInstructionEvent();
                                                    Maneuver maneuver = NavigationManager.getInstance().getNextManeuver();

                                                    Log.v("Manevra", maneuver.getNextRoadName() + " " + maneuver.getRoadName());

                                                    maneuver.getRoadName();
                                                }
                                            }));

                                            NavigationManager.getInstance().addManeuverEventListener(new WeakReference<NavigationManager.ManeuverEventListener>(new NavigationManager.ManeuverEventListener() {
                                                @Override
                                                public void onManeuverEvent() {
                                                    super.onManeuverEvent();

                                                }
                                            }));

**Comment by starand** [comment]
Hi @Natraj21 
Please take a look on this sample - https://github.com/heremaps/here-android-sdk-examples/tree/master/turn-by-turn-navigation

**Comment by Natraj21** [comment]
Yes from this reference only I've implemented but its not working as expected. Up to drawing route on maps is ok, apart from this nothing working like Maneuver, Voice guide, turn indicators ....when I'm trying to add voice 
if (id > -1)
 NavigationManager.getInstance().setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(id));
it throwing null pointer exception.
Navigation indictors are not at all appeared ....Please give some some other full package reference...
There are lot of feature to be implement like rerouting, alternate routes, arrivals ....

**Comment by NazarKacharaba** [comment]
Did you solve your problem?

> nothing working like Maneuver, Voice guide, turn indicators ....when I'm trying to add voice

What do you mean by `not working`? You don't receive maneuver callback?

>NavigationManager.getInstance().setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(id));
it throwing null pointer exception.

What `id` do you use to get voice skin?

Also, always check return code for methods like `setVoiceSkin`, it should be `Error.NONE`.

**Comment by Natraj21** [comment]
I've replace code with this  
voiceGuidanceOptions.setVoiceSkin(voiceCatalog.getLocalVoiceSkin(id));
instead 
NavigationManager.getInstance().setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(id));

**Comment by Natraj21** [comment]
maneuver is not visible....unable to show on screen

**Comment by NazarKacharaba** [comment]
Could you answer the question I asked you in my previous comment, please? Thanks.

**Comment by Natraj21** [comment]
yes, voice guide issue was resolved and unable to show maneuver...

**Comment by Natraj21** [comment]
please could you help us with maneuver issue.. unable to display the maneuver

**Comment by NazarKacharaba** [comment]
```
NavigationManager.getInstance().addManeuverEventListener(new WeakReference<NavigationManager.ManeuverEventListener>(new NavigationManager.ManeuverEventListener() {
                                            @Override
                                            public void onManeuverEvent() {
                                                super.onManeuverEvent();
                                            }
                                        }));

```
You provide anonymous listener that is wrapped in `WeakReference`, it does not have strong reference and after some time it gets garbage collected. You should hold string reference to your listener, e.g:
```
class Foo {
  ManeuverEventListener listener = new ManeuverEventListener() {
    @Override public void onManeuverEvent() {
      //...
    }
  };

  void initManeuverListener() {
    NavigationManager.getInstance().addManeuverEventListener(new WeakReference<>(listener));
  }
}
```

**Comment by starand** [comment]
Hi @Natraj21,
Was your issue solved? We are going to close the issue.

**Comment by Natraj21** [comment]
Please close .. am using msdkui to achieve this requirement...
