### ISSUE TITLE
NullPointerException MapsEngine.getEndpointCategoryName()

### ISSUE THREAD

**Issue by eugenebrusov** [heremaps/here-android-sdk-examples#217]
**HERE SDK:** 3.10.0.85
**Affected devices:** 
- Samsung SM-G532F (Android 6.0.1)
- TCL 9003X (Android  6.0)
- Galaxy Note4 (Android 6.0.1)

**Stacktrace:**
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke direct method 'java.lang.String com.nokia.maps.MapsEngine.getEndpointCategoryName()' on a null object reference

com.nokia.maps.MapsEngine.t (MapsEngine.java:1670)
com.nokia.maps.o.l (AnalyticsProperties.java:224)
com.nokia.maps.s$a.<init> (AnalyticsTrackerExternal.java:433)
com.nokia.maps.s.o (AnalyticsTrackerExternal.java:810)
com.nokia.maps.s.j (AnalyticsTrackerExternal.java:75)
com.nokia.maps.s$8.run (AnalyticsTrackerExternal.java:724)
com.nokia.maps.s$35.run (AnalyticsTrackerExternal.java:2731)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.lang.Thread.run (Thread.java:818)
```

**Comment by eugenebrusov** [comment]
After research, I found that app threw that exception if I use an old outdated license key. That exception is thrown in some depth of HERE SDK so that it's not possible to catch it even if `MapEngine.getInstance().init...` is wrapped with try/catch block. 

Hope that helps to reproduce that issue and fix it...

**Comment by starand** [comment]
Hi @eugenebrusov,
Thank you for the reporting. Fix will be included in SDK 3.11 (should be released around 1st of Apr).

**Comment by starand** [comment]
@eugenebrusov,
New SDK was released, please download and check whether the issues was solved.

**Comment by khobragadenitin** [comment]
Hi There,
I am currently Using 3.1.0 SDK and facing same issue.
for that want to download 3.1.1. But it is Downloading 3.1.5 SDK. Creating conflict in Project.
So please Share  3.1.1 SDK

**Comment by starand** [comment]
We do not support such version of SDK. Latest release was 3.15. 
What is the product name you use?
