### ISSUE TITLE
Use SDK in foreground service

### ISSUE THREAD

**Issue by nikoloz14** [heremaps/here-android-sdk-examples#219]
Is there any way of using premium SDK in background service? For example calculating routes in background and just displaying notification on device. I have searched everywhere and can't find an example or guidance. I tried MapEngine.getInstance().init() in service, but get MISSING_SERVICE error. I need to know if its possible or no? If someone has done this, show the example, please

**Comment by starand** [comment]
@nikoloz14,
You cannot start mapService from background. To be more precise see https://developer.android.com/about/versions/oreo/background

From our DEveloper's Guide:
Important: Starting with Android O (8.0), the startService() method now throws an
IllegalStateException if an app targeting Android 8.0 tries to use that method in a situation
when it isn't permitted to create background services. When an app goes into the background, it has a
window of several minutes in which it is still allowed to create and use services.

**Comment by nikoloz14** [comment]
Thanks, but I still don't get it completely. I'll ask question differently.

1) Is there any way to call MapEngine.getInstance().init() from my own foreground service?
OR
2) Is there any way to call CoreRouter.calculateRoute() function and get result in my own foreground service?
