### ISSUE TITLE
Unable to resolve NavigationManger Class

### ISSUE THREAD

**Issue by DanishAmjad12** [heremaps/here-android-sdk-examples#22]
In my case I need to show turn-by-turn navigation for which I need to use **"NavigationManager"** but I am unable to resolve this class. I imported the lib folder into my project but can't able to find this class in **"Here SDK"** .

**Comment by sschuberth** [comment]
The `NavigationManager` class is in the `com.here.android.mpa.guidance` package. Also see the [documentation](https://developer.here.com/mobile-sdks/documentation/android-premium/topics_api_nlp_hybrid_plus/com-here-android-mpa-guidance-navigationmanager.html).

**Comment by DanishAmjad12** [comment]
I cant find the **"guidance"** in lib mpa folder.

**Comment by DanishAmjad12** [comment]
Here's the SDK which I downloaded 
[HERE-sdk.zip](https://github.com/heremaps/here-android-sdk-examples/files/941152/HERE-sdk.zip)

**Comment by sschuberth** [comment]
The `guidance` directory will not be visible directly. Your example's `libs` directory should contain the `HERE-sdk.aar` file. As that file is in fact a ZIP archive, just like JARs, you *could* look at it with an unzip tool and find that it contains a `class.jar`, which in turn contains the `com/here/android/mpa/guidance` directory hierarchy.

But all of that is internal details that you should not need to know. Just do

    import com.here.android.mpa.guidance.NavigationManager;

like e.g. [here](https://github.com/heremaps/here-android-sdk-examples/blob/3c3990f27a55fe05a3fc686298d9997ed4a018dd/turn-by-turn-navigation-android/app/src/main/java/com/here/android/example/guidance/MapFragmentView.java#L26) and you should be good to know. In fact, if you start just using the `NavigationManager` class in your code, Android Studio should first flag it as an error, but then offer to resolve the error by automatically adding the necessary import statement by pressing `Alt+Enter`.

**Comment by DanishAmjad12** [comment]
As I am on free-trail so I need to know SDK for free trail or premium are same? 
when I signUp for free-trail it will generate **"App-ID"** & **"App-Code"** then I downloaded the SDK.

Am I able to use this feature **"Navigation"** on free-trail?

**Comment by sschuberth** [comment]
> Am I able to use this feature "Navigation" on free-trail?

Yes. The free trial is a trail for the Premium SDK. See again the link from above to the [turn-by-turn navigation example](https://github.com/heremaps/here-android-sdk-examples/tree/master/turn-by-turn-navigation-android) in this repository.

**Comment by DanishAmjad12** [comment]
Now I faced **Route Corrupted** error I used the same start lat lng and end lat lng.

**Comment by sschuberth** [comment]
@DanishAmjad12 Please open new a new ticket for new issues, so we can keep them all separate and more clearly point out the resolutions.

Speaking of resolutions, what was the resolution for your *NavigationManager* issue? Disclosing your resolution might help others with similar issues.

**Comment by DanishAmjad12** [comment]
Yeah sure. I downloaded the Android Premium sdk in which I found NavigationManager class 
`import com.here.android.mpa.guidance.NavigationManager;`
Thanks.

**Comment by sschuberth** [comment]
Good, so I'll close this issue then.
