### ISSUE TITLE
Multiple NavigationManagers in different processes not working

### ISSUE THREAD

**Issue by nikoloz14** [heremaps/here-android-sdk-examples#223]
Hi, is there any way to use NavigationManager in difference processes? I'll give you example.

I have foreground service(exported) running that calculate routes and uses NavigationManager to get maneuver instructions and throws notifications.

On the other side I have Fragment running with Map rendered, where I want to synchronize with NavigationManager from service and use navigationManager.simulate() method using map and its features like: Map following the location marker, showing arrows and e.t.c. When fragment is detached service is still running and throws notifications. I hope you get the point.

So in this case when NavigationManager is running in service, NavigationManager in fragment is doing nothing, so my question is if there is way to fix this, or am I doing something wrong?

**Comment by NazarKacharaba** [comment]
To call `MapEngine.getInstance().init(...)` your app needs to be in foreground(visible to a user). Once it is initialized it can be used in the background service. If your second process is only a foreground service without visible UI, then you cannot use HERE SDK in this process. 

Google [restricted](https://developer.android.com/about/versions/oreo/android-8.0-changes) starting services if app is running in the background. Internally `MapEngine.getInstance().init(...)` calls `startService` therefore SDK has this restriction.

I would advice to have simple visible UI for second process to initialize `MapEngine`.

**Comment by nikoloz14** [comment]
That is different topic.

First of all, I am using SDK in foreground service without problem. It is started with startForeground() command, which shows notification that service is running. So, why are you saying that I can't use it in foreground service? Google restricted background services, as I know. So, that's not the case here. When I close the app, service is still running and SDK is working without problems.

Here's manifest:
` <service
            android:name=".NavigationHereService"
            android:exported="true"
            android:process=":remote" />`

I am addressing different problem. While foreground service is using NavigationManager, fragment which is in main process, can't use NavigationManager. My question is: Is this bug or is it intended to work like this? Or there is ways to workaround this problem

**Comment by NazarKacharaba** [comment]
You are right right, `MapEngine` can be initialized from the `Service` if it is set as _foreground_.

Still I'm not sure I completely understand your use case but anyway...

Different process for the `Service` means that you will have two VM, therefore you cannot share instances of static fields and singletons(like `MapEngine` or `NavigationManager`) between `Fragment` and `Service`, they will have its own instances of them. 

Theoretically, you can have two identical calculated routes in `Fragment` and `Service`(`Route` object can not be shared/passed to service as it is not serializable) that are being used in different instances of `NavigationManager`, simulation can be run in parallel in `Fragment` and `Service`, then if `Fragment` is destroyed, `Service` is still up and running and its `NavigationManager` will continue navigation. That is only my thoughts and I'm not sure at all whether it will work, it is certainly not very common use case.

**Comment by starand** [comment]
If there is no further questions, we will close the ticket.
