### ISSUE TITLE
how to activate userlocation marker ? setMyLocationEnabled

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#229]
is there a method to display default user location like in google maps sdk ?

`map.setMyLocationEnabled(true);`

**Comment by starand** [comment]
You can try the following:
```
                        map.getPositionIndicator().setZIndex(50);
                        map.getPositionIndicator().setVisible(true);
```
But, positioning indicator will be shown only after position update.

**Comment by starand** [comment]
@Xgamefactory,
Do you have further questions? Otherwise we can close the issue.

**Comment by Xgamefactory** [comment]
awesome thanks we will try it.

**Comment by Xgamefactory** [comment]
tried with no success.
method executes but no position indicator is visible.
```
mapView.getPositionIndicator().setZIndex(50);
mapView.getPositionIndicator().setVisible(true);
```

**Comment by Xgamefactory** [comment]
i guess you forget to add default image for position indiciator and forgot to mention it in docs and your github examples )
