### ISSUE TITLE
how to change the white guide arrow not the green one ?

### ISSUE THREAD

**Issue by lyticshub** [heremaps/here-android-sdk-examples#230]
how to change the color of the white arrow of the guide in the map not the green one ?

![image](https://user-images.githubusercontent.com/49643713/56130504-5ef64e00-5f85-11e9-87fe-0c57b23f4893.png)

**Comment by Merlin1stHere** [comment]
@lyticshub Unfortunately, the SDK doesn't provide such feature. You can't change guidance arrow color.
