### ISSUE TITLE
Cannot resolve symbol 'MapSettings'?

### ISSUE THREAD

**Issue by haitrvn** [heremaps/here-android-sdk-examples#232]
boolean success = com.here.android.mpa.common.MapSettings.setIsolatedDiskCacheRootPath(diskCacheRoot,
                intentName);
All projects have this error, how can i fix this?

**Comment by starand** [comment]
Hi @haitrvn,

If you use Starter SDK, you will definitely get this error because there is no such API.
Just remove this line, and further if statement. It should work.
