### ISSUE TITLE
map initialization error: library missing

### ISSUE THREAD

**Issue by Ashish-Patel** [heremaps/here-android-sdk-examples#235]
i am getting missing library error while initializing here-map. can some one help me out. here is the method.

m_mapFragment.init(new OnEngineInitListener() {
                    @Override
                    public void onEngineInitializationCompleted(Error error)  {
                        if (error == Error.NONE) {
                        // MISSING LIBRARIES
}
});

**Comment by starand** [comment]
Hi @Ashish-Patel,
Which device do you use?

**Comment by Ashish-Patel** [comment]
I'm Using Lenovo Vibe k5 Note.

**Comment by Ashish-Patel** [comment]
@starand how to Make HERE-sdk.aar contains missing libraries (you can unzip it and look into libs folder).

**Comment by Ashish-Patel** [comment]
@starand after defining split ABI also, giving same error. here is the code.
android {
    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a'
            universalApk false
        }
    }
}

**Comment by starand** [comment]
@Ashish-Patel one quick idea. Did you check whether there are libMAPSJNI.so in your HERE-sdk.aar file?
If you use other native libraries make sure all native libs supports the same ABI (arm32 or arm64).

**Comment by Ashish-Patel** [comment]
@starand how can I extract it, there is not option to extract in winrar. And I am using the same credentials and sdk generated through here-map console after providing the package name. How libaraies can be missing. I don't know how to check ABI and all. Can you tell me some alternative way. Or should I change the package name and generate app ID and. aar file again.

**Comment by starand** [comment]
You can rename aar to zip, and then unpack it. Please provide files list under libs folder.
When you get "Missing libraries", you can extract more details - error.getDetails(). Please share this info as well.
I do not think you have to create new account. Anyway, do you use other native libraries?

**Comment by Ashish-Patel** [comment]
i'm getting this error message-->>
Native libraries missing: gnustl_shared, gnustl_shared, gnustl_shared. Please refer to the user guide for details about proper project setup.

**Comment by starand** [comment]
Which version of SDK do you use?

**Comment by starand** [comment]
Most likely you somehow corrupted the HERE-sdk.aar file. Closing ticket, as you solved the issue.
