### ISSUE TITLE
HereMap setOnCameraIdleListener is not available

### ISSUE THREAD

**Issue by Ashish-Patel** [heremaps/here-android-sdk-examples#238]
How can i pick the center location/latlng from map based on CameraPositionChange/CameraIdleListener. i havn't found any method to pick the location form the center of map based on moving map.
could someone help me out.? Thanks In Advanced.

**Comment by starand** [comment]
Hi @Ashish-Patel,

You should user Map.OnTransformListener interface.
>      * Listener for {@code Map} transform events. Map transform events are triggered by any
>      * operation which causes the {@link com.here.android.mpa.mapping.MapState MapState} to change.
>      * This includes user interaction (such as map gestures) as well as programmatic calls to the
>      * map.

onMapTransformEnd(MapState mapState) callback returns mapState object which contains map center.
Please let us know whether this helps.

**Comment by Ashish-Patel** [comment]
Thanks @starand , it worked. you guys are awesome.!!!
