### ISSUE TITLE
Incorrect License Key

### ISSUE THREAD

**Issue by maheshsystimanx** [heremaps/here-android-sdk-examples#239]
I created project with package name com.keytens.keyten.I using the https://developer.here.com/projects/PROD this link to create project.i  got the licencekey and app id and code.but when i run the project at the time show In correct license key.pls check this issue

**Comment by starand** [comment]
Hi @maheshsystimanx,
Make sure you copied all symbols for appCode/Id/License Key. Try to create another account to double check. You have to share your app with credentials to check.

**Comment by maheshsystimanx** [comment]
Hi 



    Here i  send my manifest file appid ,appcode,licencekey

<meta-data
    android:name="com.here.android.maps.appid"
    android:value="{VJz2NeFlqD46nDx0o3dI}" />
<meta-data
    android:name="com.here.android.maps.apptoken"
    android:value="{bAf0W3Sa-2Et8peUcZ-4TA}" />
<meta-data
    android:name="com.here.android.maps.license.key"
    android:value="{AoEzH4ldDTFCIi4dAn73EnLWyjOg6CNVQ0UkmND2gK+S4HCPWZGFQ+4XAeqnHJ457AgU8PpLbS1uA8anA0S/NY+GLsA30U4Bv9wvnMDr9xuOs9uOve1ElritGrR7lPNO27S0eR2hJFp7RszqpnCEdk6R+Z1ti3yYP0I4dqDPVmY91CGGULObuItOOx0tWZIlgU1fmVAiWFaFFQSkeA8Lb0ouY2q+TSCPtR1KHRierm4tLKafA4nmpd9L0fhDHBJtk/7cubfRzWFCBKA4d6CZeRkj6Nlb5dQXQdWQ7udHQCJOBgOnSorTf/XPW9DX1KVOOeq1SzsRU5xyCdubEe17eawvkY4rd5Cpf4+9HhPGrT923qINP57pF8MOymC8TfDLGuTJbU0op0f0snCFB+M7UXoivpXtG/3PE2U7AYrCNxfVGTkI6geaBij4rftYxsIKeoZSkfbg5MWChlAjrozbhAx7bG0xV9y4+Qrr1AtCs0aQD1W6snW3gZxfIHgwF/X6PwTYEgNcQ2OqOQLNhnB9vjxAps5eC7nU2ufHaHZCduTFbS0IawHqLldVSbS1mQuFG5KtINRTV+y1BeClBIK4tNz3ki03y6MIfXn7Exf2WNC1P7C7CWOHkHIYDdjebrCtcU3KKb5LSW4E4lkmVmjLLsEojT6MLB2DP0W6/m1xBkc=}" />

Package name:com.keytens.keyten



And also i attach my premium sdk screenshot.but i triend starter sdk is shows error in program.so i use premium sdk this method





Thanks & Regards,

Mahesh,
SystimaNX IT Solutions Pvt Ltd,
M : +91-8754048942,









Confidentiality  Notice: This email (including any attachments) is for the sole use of  the intended recipient(s) and may contain confidential and privileged  information. Any unauthorised review, use, disclosure, dissemination,  forwarding, printing or copying of this email or any action taken in  reliance on this e-mail is strictly prohibited and unlawful. If you are  not the intended recipient, please notify the sender by reply email and  destroy all copies of the original message. Thanks for your cooperation.








---- On Fri, 03 May 2019 11:41:17 +0530 starand <mailto:notifications@github.com> wrote ----




Hi https://github.com/maheshsystimanx,

 Make sure you copied all symbols for appCode/Id/License Key. Try to create another account to double check. You have to share your app with credentials to check.

**Comment by starand** [comment]
Please removed {} from app Id, code and LK

**Comment by starand** [comment]
@maheshsystimanx did you solve your problem?

**Comment by 3888** [comment]
Hi @starand,

I can't believe, but I faced the same issue. 
The error is Error: INCORRECT_LICENSE_KEY, SDK Version: 3.16.2.101

PACKAGE NAME
com.here.android.example.kotlin

   applicationId "com.here.android.example.kotlin"

APP ID
OeASZOc3KVOrKirzzD7K

<meta-data
            android:name="com.here.android.maps.appid"
            android:value="OeASZOc3KVOrKirzzD7K" />

APP CODE
RrACJk2i2Li3PTBrhMYBaQ

        <meta-data
            android:name="com.here.android.maps.apptoken"
            android:value="RrACJk2i2Li3PTBrhMYBaQ" />
LICENSE KEY
fpZd5t8Lg6iJonDeOU5VCS3KtxMxMpKaiQCesGYhkA+QYw561lNcC8OMKJLAPTsHisXt6D1lc5D+YmRdNllEAt7Hc1jljqZ74O4ScWc9Hi5pfRN+rad/L2EbC23ToJy3ZiuGEC1m7G/y4npcPd+4vs68CCDRRdeO01TtxxV8ViKIRpeEbSpQ1vJHcqeYm8LHj9pl/3UJipQ0qTyH9XPfKB8ioWWp1mzjehn8v2B2l33hNtyr5C5nYeg7BR9VoJ4xJANbN2WXuhomx2MJffG3rMS/eo1ge3nhgMRqkGiHJRnMADKisRcm7aABs+gty2IlOM7yf7Illft+NgEDdBS91yAp0p5VHZxAImbM48ysZ1CoQyKnXi33gNgCzIBff3X5PGvA10k5pEe3LS0Dl3DJlhO/0ouI+5Tmn6sDJLq8V6LwS8REWLJIkW4SvJrRidGxdUwo24/1PbtFvbqIck0SjngbjIkKK0Qg9uRBGMkcfd2Evvs0tcfSJ8e5wIlkkgvZBLUJAuC6xbTWAexMr8inBrnMAvb/dX5RRyX4ol4Upjk4bnPUjRLLloec0Da66XeeBbXKfJl19kXXcKnA2SuhR7TPCjj3m6CzonQDYAtrq0wv2hE2gqjgIZtl5RnHB+tpiPb4SYRQo3xJYO2aRFdVs1v6ajevyGHX9EMIDpQ3ULI=

        <meta-data
            android:name="com.here.android.maps.license.key"
            android:value="fpZd5t8Lg6iJonDeOU5VCS3KtxMxMpKaiQCesGYhkA+QYw561lNcC8OMKJLAPTsHisXt6D1lc5D+YmRdNllEAt7Hc1jljqZ74O4ScWc9Hi5pfRN+rad/L2EbC23ToJy3ZiuGEC1m7G/y4npcPd+4vs68CCDRRdeO01TtxxV8ViKIRpeEbSpQ1vJHcqeYm8LHj9pl/3UJipQ0qTyH9XPfKB8ioWWp1mzjehn8v2B2l33hNtyr5C5nYeg7BR9VoJ4xJANbN2WXuhomx2MJffG3rMS/eo1ge3nhgMRqkGiHJRnMADKisRcm7aABs+gty2IlOM7yf7Illft+NgEDdBS91yAp0p5VHZxAImbM48ysZ1CoQyKnXi33gNgCzIBff3X5PGvA10k5pEe3LS0Dl3DJlhO/0ouI+5Tmn6sDJLq8V6LwS8REWLJIkW4SvJrRidGxdUwo24/1PbtFvbqIck0SjngbjIkKK0Qg9uRBGMkcfd2Evvs0tcfSJ8e5wIlkkgvZBLUJAuC6xbTWAexMr8inBrnMAvb/dX5RRyX4ol4Upjk4bnPUjRLLloec0Da66XeeBbXKfJl19kXXcKnA2SuhR7TPCjj3m6CzonQDYAtrq0wv2hE2gqjgIZtl5RnHB+tpiPb4SYRQo3xJYO2aRFdVs1v6ajevyGHX9EMIDpQ3ULI=" />

copied all symbols for appCode/Id/License Key - yes
try to create another account to double check - yes

Any suggestions what is wrong?
