### ISSUE TITLE
Can not display map

### ISSUE THREAD

**Issue by arorayogita** [heremaps/here-android-sdk-examples#242]
I am using premium sdk plan for navigation .Previously maps are working fine but suddenly maps are not loading and showing black screen and i am getting below exception 
"Cannot created HERE SDK objects before MapEngine is initialized"

**Comment by starand** [comment]
Hi @arorayogita,
What error do you get in onEngineInitializationCompleted(Error error) callback when you init map?
You cannot create HERE SDK objects before MapEngine is initialized. Make sure you avoid this.

**Comment by arorayogita** [comment]
I am getting Error.NONE and all functionalities and listeners are working fine except map

**Comment by starand** [comment]
you can set breakpoints in the exception place and in onEngineInitializationCompleted(). What happens first?
Most likely this is your app issue. Try to reproduce it on github sample, or remove functionality of your app part by part to localize the issue place. Or you can share your app and we took a look.

**Comment by arorayogita** [comment]
Okay @starand
But after getting this error I Have created a sample activity in my app in  which i am just showing maps and I have taken code from your samples In that case it is also not working .

**Comment by starand** [comment]
Does not any github sample works with your credentials?

**Comment by arorayogita** [comment]
@starand  It was working previously but currently i am getting this issue.

**Comment by starand** [comment]
Is it possible to share your app?
