### ISSUE TITLE
Changing Routing option Color and route Selection

### ISSUE THREAD

**Issue by yogita-techindustan** [heremaps/here-android-sdk-examples#244]
Hi
1) I want to change routes color as i have set route count to 3 ,So i want to show these routes with different colors but I am not able to change the color of routes.
I am using these lines of code:
 currentRoute.setRenderType(MapRoute.RenderType.USER_DEFINED);
currentRoute.setColor(R.colors.Green)

2) I am not able to click on these routes as i want if i have 3 routes to go for origin to destination so user can select from which route he wants to navigate ..

**Comment by NazarKacharaba** [comment]
Hi @arorayogita,
It would be nice to have all the code so we can find where the problem is.

For example, this code works OK: it generates different color for each route, and it resets it onRouteSelect event:
```
void setRouteClickListener() {
    mapView.getMapGesture().addOnGestureListener(new MapGesture.OnGestureListener.OnGestureListenerAdapter() {
        @Override
        public boolean onMapObjectsSelected(List<ViewObject> objects) {
            for (ViewObject object : objects) {
                if (object instanceof MapRoute) {
                    ((MapRoute) object).setColor(generateColor());
                    // other code
                }
            }
            return false;
        }
    }, 0, false);
}

void onRouteCalculated(List<RouteResult> results) {
    for (RouteResult result : results) {
        MapRoute mapRoute = new MapRoute(result.getRoute());
        mapRoute.setRenderType(MapRoute.RenderType.USER_DEFINED);
        mapRoute.setColor(generateColor());
        map.addMapObject(mapRoute);
    }
}

int generateColor() {
    Random random = new Random();
    return Color.argb(1.0f, random.nextFloat(), random.nextFloat(), random.nextFloat());
}
```

**Comment by starand** [comment]
Hi @arorayogita, did you solve you issue?

**Comment by VadimT7** [comment]
To change the color of a route, you need to use ARGB format of color when setting the color of the route.

This is an example that gives it a red color:
`mapRoute.setColor(Color.argb(120, 255, 0, 0));`

The first part represents the "A" (alpha) in the ARGB format and represents the transparency of the color. The higher the value, the less transparent the color.

Hope it helps!
