### ISSUE TITLE
NavigationManager.StartNavigation return INVALID_PARAMETERS

### ISSUE THREAD

**Issue by joseBarreto** [heremaps/here-android-sdk-examples#247]
I'm using HereMaps Sdk for navigation and route calculations. When I try to start a navigation or simulation I get error from INVALID_PARAMETERS...

I can not identify the problem to be able to solve. I already have my routes configured and my map added to the NavigationManager

I am using the example of the own nokia in their github as base.
https://github.com/heremaps/here-android-sdk-examples/blob/master/turn-by-turn-navigation/app/src/main/AndroidManifest.xml

```
//OnEngineInitListener...    
NavigationManager.Instance.SetMap(mapFragment.Map);
NavigationManager.Instance.SetMapUpdateMode(NavigationManager.MapUpdateMode.Position);
var nresult = NavigationManager.Instance.StartTracking();
//nresult return only INVALID_PARAMETERS and navigation dont start
```

**Comment by starand** [comment]
Hi @joseBarreto,
Tried to reproduce the issue using the github sample and Java8 - was not able. Could you pease try the same?
If you do not use Freemium plan, there can be restrictions in your license key.

**Comment by joseBarreto** [comment]
> Hi @joseBarreto,
> Tried to reproduce the issue using the github sample and Java8 - was not able. Could you pease try the same?
> If you do not use Freemium plan, there can be restrictions in your license key.

I'm using "Freemium, XYZ".
Navigation types are not available for this subscription?

**Comment by starand** [comment]
> I'm using "Freemium, XYZ".
> Navigation types are not available for this subscription?
They are available. So this is not related to your problem.
Anyway I was not able to reproduce the issue. Is it possible to share your app?

**Comment by joseBarreto** [comment]
In fact, the package I am using is "ANDROID SDK PREMIUM"

**Comment by joseBarreto** [comment]
We are using Xamarin.Android, we made the sdk link from HERE-sdk.aar to C #, since we have already built the entire application.
Everything works great, rotarization, position capture and others.
Our only problem is to be with the navigation modes, because it returns this generic error that we can not identify.

I also did not find a way to understand what
NavigationManager.Instance.StartNavigation,
NavigationManager.Instance.Simulate,
NavigationManager.Instance.StartTracking
expect to receive setup for the job.

Can you tell me what causes this error generally from "INVALID_PARAMETERS"

> > I'm using "Freemium, XYZ".
> > Navigation types are not available for this subscription?
> 
> They are available. So this is not related to your problem.
> Anyway I was not able to reproduce the issue. Is it possible to share your app?

**Comment by starand** [comment]
We do not officially support Xamarin.
There are the following cases when this error can happen:
1) null passed as route.
2) In case you use RouteOptions.TransportMode.PUBLIC_TRANSPORT
3) route type is UMRoute
4) in other cases - Navigation engine is complex feature (e.g. Map was not init, incorrect voice package and so on).

**Comment by joseBarreto** [comment]
> We do not officially support Xamarin.
> There are the following cases when this error can happen:
> 
> 1. null passed as route.
> 2. In case you use RouteOptions.TransportMode.PUBLIC_TRANSPORT
> 3. route type is UMRoute
> 4. in other cases - Navigation engine is complex feature (e.g. Map was not init, incorrect voice package and so on).

I confirmed all these points, and apparently would not be one of them.
I have a new data, which I do not know if it can help.

When I use an android emulator 9, x86 browsing works normally.

When I run on a physical device with android 8.1, I get the "INVALID_PARAMETERS".

Any tips on that point?

**Comment by joseBarreto** [comment]
Sorted out!
The device he was using was a Samsung Galaxy S7 with Root and Room customized for android 8.1
After removing the root and returning to the original build the problem has been resolved.
I tested it on other devices with android 6,7 and 9. It is also working, as long as root is disabled.
