### ISSUE TITLE
How to save battery in navigation

### ISSUE THREAD

**Issue by ChenYuehNung** [heremaps/here-android-sdk-examples#250]
When running HERE navigation, the cell phone become so hot.
Is there any way to fine tune it ?

We have HERE SDK and Mapbox SDK navigation in our app testing report.
Mapbox SDK - 10% drain with a 30 min drive and the phone remained cool. 
HERE SDK - 16% drain with a 30 min drive and the phone got very hot

**Comment by NazarKacharaba** [comment]
Try to turn off some render heavy stuff like:
```
Map.setTrafficInfoVisible(false);
Map.setCartoMarkersVisible(false);
Map.areExtrudedBuildingsVisible(false);
```

Disable layers that you do not need:
```
Map.setVisibleLayers(…);
```

Preload map data(using `MapLoader`) so during navigation SDK does not need to heavy use networking.

I suspect that GPS adapter also heats the phone. You can use gps location only from network(like wifi signals etc) using `PositioningManager.start(LocationMethod.NETWORK)`, however it works reliably only in cities where there are lots of wifi spots.

Those suggestions do not guaranty that your phone will not get heated during navigation, but it may improve things a bit.

**Comment by ChenYuehNung** [comment]
Hi @NazarKacharaba 

Thank you for your reply, we will try the way you suggested.

**Comment by ChenYuehNung** [comment]
> Try to turn off some render heavy stuff like:
> 
> ```
> Map.setTrafficInfoVisible(false);
> Map.setCartoMarkersVisible(false);
> Map.areExtrudedBuildingsVisible(false);
> ```
> 
> Disable layers that you do not need:
> 
> ```
> Map.setVisibleLayers(…);
> ```
> 
> Preload map data(using `MapLoader`) so during navigation SDK does not need to heavy use networking.
> 
> I suspect that GPS adapter also heats the phone. You can use gps location only from network(like wifi signals etc) using `PositioningManager.start(LocationMethod.NETWORK)`, however it works reliably only in cities where there are lots of wifi spots.
> 
> Those suggestions do not guaranty that your phone will not get heated during navigation, but it may improve things a bit.


Hi @NazarKacharaba 
Thank you for your reply, we will try the way you suggested.

**Comment by starand** [comment]
@ChenYuehNung is there any further questions? Can we solve the issue?

**Comment by ChenYuehNung** [comment]
Hi @starand 
Yes, this issue had been resolved. It is better than before.
Thanks.
