### ISSUE TITLE
Set padding usage

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#251]
hi i saw setPadding method was added in new released sdk.
I've tried and it seems that it's not taking effects.

`Map.setPadding(56, 16 , 56 ,16);
Map.zoomTo(GeoBoundingBox.getBoundingBoxContainingGeoCoordinates(list), Map.Animation.LINEAR, 0);`

This is how i implement it, any suggestion?

**Comment by starand** [comment]
Hi @bluesnow4425,
Do you use Premium or Starter SDK?

**Comment by bluesnow4425** [comment]
Premium thanks.

**Comment by bluesnow4425** [comment]
hi i've tested many times and it seems like if i pass `Map.MOVE_PRESERVE_ORIENTATION`, it would take effect. However, if i pass 0, it's not working.

**Comment by NazarKacharaba** [comment]
Hi @bluesnow4425,
What are you trying to achieve with padding? Set padding to `list` of `MapObject`?

Method `setPadding` is only used to define invisible area of the map around `MapView`([doc](https://developer.here.com/documentation/android-premium/api_reference_java/com/here/android/mpa/mapping/Map.html#setPadding-int-int-int-int-)), it does not set padding for `MabObject`(like MapMarker, MapCircle etc), for this purposes use [this](https://github.com/heremaps/here-android-sdk-examples/blob/master/map-objects/app/src/main/java/com/here/android/example/map/objects/MapFragmentView.java#L296-L320) approach.

**Comment by bluesnow4425** [comment]
The list includes only a few coordinates.
What i would like to do is to show several coordinates in the map and i don't want it to be a the edge of the map so i'd like to add some padding to those coordinates.

**Comment by NazarKacharaba** [comment]
Method `setPadding` does not move/change zoom on the map. It is only used to define invisible area of the map.

For example, you have view above map and you want to adjust `setCenter` to logical visible area of the map, in that case you use `setPadding`.

setCenter w/o using padding
<img width="200" height="300" alt="Screen Shot 2019-04-23 at 11 11 07 AM" src="https://user-images.githubusercontent.com/10234183/58791954-e06c7300-85fb-11e9-8836-9428d80742a8.png">

setCenter w/ using padding
<img width="200" height="300" alt="Screen Shot 2019-04-23 at 11 09 58 AM" src="https://user-images.githubusercontent.com/10234183/58791961-e4989080-85fb-11e9-9160-47fd41c7c2ba.png">

**Comment by bluesnow4425** [comment]
That's exactly what i want, but it seems not working with zoomTo. Is it correct that i setPadding right before zoomTo?

**Comment by NazarKacharaba** [comment]
If you use `zoomTo()` with `GeoBoundingBox` argument, then it ignores `padding` and use provided `bounding box` to calculate your new center.
Use `setCenter` method if you want to achieve the same behaviour that is on the screenshot.

**Comment by starand** [comment]
@bluesnow4425, did you solve your issue? If yes, please close the ticket.

**Comment by samvgorode** [comment]
Faced exactly the same problem.
Should do like so:
To move map 200pix up:

`map.setPadding(0, 200, 0, 0)`
 `val mapTransformCenter = PointF(map.transformCenter.x, (map.transformCenter.y + 200))
                map.setCenter( mapTransformCenter, Animation.LINEAR,
                    map.zoomLevel, map.orientation, map.tilt)`

Move to previous state:

`map.setPadding(0, 0, 0, 0)`
 `val mapTransformCenter = PointF(map.transformCenter.x, (map.transformCenter.y - 200))
                map.setCenter( mapTransformCenter, Animation.LINEAR,
                    map.zoomLevel, map.orientation, map.tilt)`

**Comment by NazarKacharaba** [comment]
Hi @samvgorode 
Do not use `transform center` in this case, just call `map.setCenter(geoCenter, NONE)` after you set `padding`. You will get following result;
![Sample](https://user-images.githubusercontent.com/10234183/75777234-47bb7d00-5d5e-11ea-92f0-b0b148765b48.gif)

**Comment by samvgorode** [comment]
@NazarKacharaba thanx for the explanation!
