### ISSUE TITLE
Add nullable annotations

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#252]
The official statement is that HERE SDK does not support Kotlin. On the other hand having the public API of the SDK properly annotated with @Nullable and @NotNull annotations serves as a documentation and helps both Java and Kotlin users.

**Comment by starand** [comment]
@xsveda,
Thank you for this notice. We agree, that annotations improve public API. Indeed, there are some classes that use annotations.
Anyway, there are a lot of classes in SDK, and it will take time to update all of them (as well as it requires investigation of implementation). Most likely we will be adding them into new classes and probably sometimes update existent ones.
