### ISSUE TITLE
Takes a long time to load map

### ISSUE THREAD

**Issue by ChenYuehNung** [heremaps/here-android-sdk-examples#253]
Hi 
Sometime my app launched and got "onEngineInitializationCompleted" event, but the map would take more than 20 sec to shown.
I tried launching HERE WeGo, It is always shown as soon (less than 3 sec).
Have any way to find out the issue and resolve it ?

**Comment by starand** [comment]
Hi @ChenYuehNung,

Please share the following info:
1) Which version of SDK do you use?
2) Which device and Android OS version?
3) How do you connect to internet? Did you test connection speed?
4) Do you see the same issue with any of our github samples?

**Comment by ChenYuehNung** [comment]
Hi @starand 

Thank for your reply. We have found the root cause.
Because the GPS is not ready from PositioningManager when EngineInitializationCompleted event had been trigger, and we was doing something on map. e.g add Marker.
This is our solution to fix this issue

PositioningManager.getInstance().addListener(new WeakReference<>(this));


			if (PositioningManager.getInstance().isActive() && PositioningManager.getInstance().getLastKnownPosition() != null && PositioningManager.getInstance().getLastKnownPosition().isValid()) {

				onPositionUpdated(PositioningManager.LocationMethod.GPS_NETWORK,
						PositioningManager.getInstance().getLastKnownPosition(), false);

			} else {

				PositioningManager.getInstance().start(PositioningManager.LocationMethod.GPS_NETWORK);
			}
