### ISSUE TITLE
SDK cache is missing

### ISSUE THREAD

**Issue by fabiancarlos** [heremaps/here-android-sdk-examples#254]
Having tring to use here maps on React Native, and writing the code from example... but, after days, i stuck in this error when initiliazing Maps..

```
SDK cache is missing
```

**Comment by starand** [comment]
Hi @fabiancarlos,
We do not support React Native officially. Therefore I would recommend try to reproduce this using our github sample & java. Please let us know whether you are able to reproduce in this way.

**Comment by starand** [comment]
That error means SDK cache does not exist. Cache path should look like - /data/user/0/com.example.yourappname/files/.here-maps/diskcache-v5/BundleStore
