### ISSUE TITLE
Add support for x86_64 architecture

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#255]
Yesterday [Google announced](https://android-developers.googleblog.com/2019/06/moving-android-studio-and-android.html) that as of June 30 2019 the 32 bit emulators are deprecated. They will still work till the end of 2020 but will receive no updates.

It would be great to have an option to work with HERE SDK on 64 bit emulators.

**Comment by starand** [comment]
Hi @xsveda,

As you may know, new Android Q OS should be released this autumn, therefore should be included into 3.13 HereSDK release. Plus AndroidX fragment. We are working on including this into SDK 3.13, but there is no guarantee.

**Comment by starand** [comment]
Hi @xsveda,
Yesterday, we updated SDK to version 3.12.4 which includes x86_64 libraries. You can download the latest SDK from dev portal in usual way.
