### ISSUE TITLE
Add direct AndroidX support

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#256]
Its been more than a year since AndroidX libraries have been published and during the time most of the Android eco-system including libraries have already migrated.

As HERE SDK is still using Android Support libs we need to run the Jetifier as a part of our build pipeline which consumes resources and slows down our builds.

But HERE SDK is using Support libs version 28.0.0 which is comparable with AndroidX libs 1.0.0 so transition should be smooth. 

What are the plans about AndroidX support?

**Comment by starand** [comment]
Hi @xsveda,
Thank you for pointing us. Most probably new map fragment will be added in SDK 3.13 release.
