### ISSUE TITLE
Possible leak through OnEngineInitListener instance

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#257]
When `MapEngine.getInstance().init()` method is called given `OnEngineInitListener` instance is stored in `MapsEngine` class in `CopyOnWriteArrayList` to invoke it once map engine initialization finishes.

The list of ` OnEngineInitListener` instances should be cleared after map engine initialization finishes as it is no longer needed but it seems it is not cleared in HERE SDK version 3.11.2.82.

This may lead to a memory leak.

Example:
When `MapEngine.getInstance().init()` is called in Android Activity and ` OnEngineInitListener` as implemented as anonymous instance it will keep a reference to Activity instance. When user rotates the device the Activity instance leaks.

```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    MapEngine.getInstance().init(ApplicationContext(applicationContext)) { error ->
        if (error == OnEngineInitListener.Error.NONE) {
            setContentView(R.layout.activity)
        }
    }
}
```
Leak can be detected with [LeakCanary](https://github.com/square/leakcanary)

**Comment by starand** [comment]
Hi @xsveda,
Thank you for reporting. The fix will be included in SDK 3.12 Release (planned to about 1st of July).
