### ISSUE TITLE
 cannot resolve symbol SupportMapFragment;

### ISSUE THREAD

**Issue by olivierfischer** [heremaps/here-android-sdk-examples#258]
getting the error  cannot resolve symbl SupportMapFragment on the statement 

import com.here.android.mpa.mapping.SupportMapFragment;

using HERE_Android_SDK_Premium_v3.8.0.104

Thanks,
Olivier

**Comment by starand** [comment]
Hi @olivierfischer,
SupportMapFragment was introduced later than 3.8 release (in SDK 3.10). It is recommended to switch SDK 3.11. Otherwise you please use MapFragment instead.

**Comment by olivierfischer** [comment]
Where do I get 3.11?
When I download the ask from my here account page I get 3.8.

**Comment by starand** [comment]
Try register new user to get the latest SDK. Then you can use your credentials.

**Comment by olivierfischer** [comment]
That worked.


Thanks,
Olivier
