### ISSUE TITLE
Get the content of voice navigation

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#259]
hi i noticed that there is an **AudioFeedbackListener** that i can be notified before and after it plays voice guidance, but is there any way that we can retrieve exactly the string it said like ios did?

**Comment by starand** [comment]
Hi @bluesnow4425,
Yes there is no such param in HERE SDK Android API. Could you please provide iOS class name you used?

**Comment by bluesnow4425** [comment]
func navigationManager(_ navigationManager: NMANavigationManager, **willPlayVoiceFeedback** text: String?) {
   }

**Comment by Merlin1stHere** [comment]
@bluesnow4425 You can use AudioPlayerDelegate (see NavigationManager.AudioPlayer).

**Comment by starand** [comment]
Hi @bluesnow4425,
Did you solve your issue? If no response for few days we are going to close the ticket.
