### ISSUE TITLE
How to test ReRouteListener

### ISSUE THREAD

**Issue by nikoloz14** [heremaps/here-android-sdk-examples#260]
Is there any way to test ReRouteListener with simulation without real navigation?

When navigation.simulate() is called it never goes to different direction, so it is impossible to test new alternative routes

**Comment by Merlin1stHere** [comment]
@nikoloz14 You can use an application for fake GPS.
As example: https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito&hl=uk
