### ISSUE TITLE
 the time to arrival value does not change if we switch vehicle profile between car and truck

### ISSUE THREAD

**Issue by indexer** [heremaps/here-android-sdk-examples#262]
How can i calculate the correct Time to Arrive , because even i set the bicycler TTA time is still same with car and truck, It there any method to calculate ?

**Comment by Merlin1stHere** [comment]
@indexer I could not reproduce this issue. All values returned from functions getTtaIncludingTraffic, getTtaUsingDownloadedTraffic, getTtaExcludingTraffic are different for routes that are calculated with the same coordinates and different TransportMode. Could you provide more details for this issue?
Waypoints that you use, version of the SDK, sample code?

**Comment by indexer** [comment]
@Merlin1stHere  
Hello Merlin , 
Thanks for reply , we are testing with  Turn By Turn Navigation Example , so we does not add any traffic api for creating route, SDK version is  HERE_Android_SDK_Premium_v3.11.2.82

**Comment by Merlin1stHere** [comment]
@indexer My question about how to you obtain the TTA value for the route.
Which of functions did you use? Route. getTtaIncludingTraffic, Route. getTtaUsingDownloadedTraffic or Route. getTtaExcludingTraffic?
As I understand you use coordinates for route from example?

**Comment by indexer** [comment]
@Merlin1stHere  i used m_navigationManager?.getTta(TrafficPenaltyMode.OPTIMAL, true)?.duration to get the TTA

**Comment by Merlin1stHere** [comment]
@indexer How do you set the transport mode for your route?
The correct way is:
```
RouteOptions options = new RouteOptions();
options.setTransportMode(RouteOptions.TransportMode.CAR);
routePlan.setRouteOptions(options);
```
I tried to set transport mode CAR and TRACK and I got different values for TTA.

Be careful, the code **routePlan.getRouteOptions().setTransportMode(RouteOptions.TransportMode.CAR)** doesn't change current settings of the route plan.

**Comment by indexer** [comment]
@Merlin1stHere thanks you can close the issue thank u much
