### ISSUE TITLE
GeocodeRequest without area

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#263]
hi i'm looking for [Geocode using free-form input](https://developer.here.com/api-explorer/rest/geocoder/latitude-longitude-by-free-form-address) function in android sdk. 
As i tested, geocodeRequest without search area is not executing.

Is there any way to use geocode without location? Or the only way is to use restful api?

**Comment by NazarKacharaba** [comment]
Hi @bluesnow4425, you are right. Currently, HERE SDK does not allow to use this API without providing location. You will have to use Restful API.
