### ISSUE TITLE
 java.lang.IllegalArgumentException: Image provided is invalid.

### ISSUE THREAD

**Issue by EugeneZaychenko** [heremaps/here-android-sdk-examples#266]
Hi, I downloaded the latest version of Premium SDK and started getting such an error. In previous versions, there is no such error. I create an Image() object and this object isValid = false, then I set the icon from the resources and specify anchorPoint. When I try to set this image in MapMarker() I get this exception because Image() is not valid

**Comment by NazarKacharaba** [comment]
Could you provide this image(url or attach to this issue) so we can investigate where is the problem?

**Comment by EugeneZaychenko** [comment]
I understood what the problem was. When creating an icon, Android Studio also created a vector image and tried to set these icons. This was the reason for the exception.

**Comment by starand** [comment]
@EugeneZaychenko please solve the issue
