### ISSUE TITLE
NavigationManager.RoadView.zoomIn() and zoomOut() fails with INVALID_OPERATION

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#267]
After I start a navigation through `navigationManager.startNavigation(route)` I call `RoadView` zoom actions: `zoomIn()` and `zoomOut()`.
Both of them fail with `NavigationManager.Error.INVALID_OPERATION` despite which of the `NavigationManager.MapUpdateMode` is used.

There are no requirements in zoom methods documentation.

Is it a bug or what requirements are for these methods to make them work?

**Comment by NazarKacharaba** [comment]
Did you set `map` to `NavigationManager` using `NavigationManager.setMap(map)` method?

**Comment by xsveda** [comment]
Sure. The `Map` is set and it is moving together with userposition.

Also `NavigationManager.getRoadView().setOrientation(NORTH_UP/DYNAMIC)` works as expected.

**Comment by NazarKacharaba** [comment]
Could you share code snipped to reproduce this issue?

**Comment by xsveda** [comment]
```
navigationManager.startNavigation(route) // Starts the navigation
navigationManager.setMap(map) // Map instance is set
navigationManager.setMapUpdateMode(MapUpdateMode.ROADVIEW) // Map is being updated based on current position
navigationManager.getRoadView().setOrientation(Orientation.NORTH_UP) // Map is oriented NORTH by still following current position
navigationManager.getRoadView().zoomOut() // Returns NavigationManager.Error.INVALID_OPERATION
```

**Comment by Merlin1stHere** [comment]
@xsveda Did you try to call the zoomOut function not immediately after calling the startNavigation function?

**Comment by xsveda** [comment]
@Merlin1stHere Sure, in our app the function is called after clicking on a button, still the same result.

**Comment by Merlin1stHere** [comment]
@xsveda Please try to call navigationManager.setMap(map) before navigationManager.startNavigation(route).

**Comment by xsveda** [comment]
@Merlin1stHere Thanks for the hint!!! I've tested that on MSDUIDemo and it seems to work that way. Please document this behavor in the `zoomIn()` / `zoomOut()` method Java Doc 🙏

**Comment by starand** [comment]
>  * <b>Note:</b> Setting the map while Navigation is ongoing is not supported.

See setMap() embedded documentation
