### ISSUE TITLE
positionindicator jumps when initiating navigation

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#271]
As we're working on the navigation, we found out that current location snaps too soon to the road, which makes user confused about the orientation when they're in unfamiliar places.
Sometimes i even haven't left the parking lot and it already tells me that i passed the second maneuver.

I check the api reference and I found out that during navigation, 
**PositioningManager.OnPositionChangedListener.onPositionUpdated(PositioningManager.LocationMethod method,GeoPosition position, boolean isMapMatched)** returns TRUE for isMapMatched.
I know it approximates user location to the route, but it seems not working ideally.

Is there any way to prevent position change too fast?

**Comment by Merlin1stHere** [comment]
@bluesnow4425 Did you try to use enhanced map matcher?

**Comment by bluesnow4425** [comment]
i do enabled in Application class but i didn't init supportMapFragment with certain context. Should i pass it as supportMapFragment.init?

**Comment by Merlin1stHere** [comment]
I'm not sure I understand what you mean by "**i do enabled in Application class**"
Do you call MapEngine.init with ApplicationContext that enables enhanced map matcher?

**Comment by bluesnow4425** [comment]
now i do. I'll observe if it still happens. Thanks
