### ISSUE TITLE
Had difficulty to start roadview navigation

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#272]
hi recently i find out that if i start navigation when I'm (1) driving fast in the highway (2) moving statically (like slightly move in the parking lot) , it has difficulty to start RoadView mode map update. It takes pretty long (sometimes more than 5 mins) that i can see the RoadView navigation.

I got feedback from colleagues that it's getting worse after enableEnhancedMapMatcher. Any suggestion to it?

**Comment by starand** [comment]
Hi @bluesnow4425,
Did you preload map data using MapPrefetcher or MapLoader?
Navigation requires some additional data, so when you start it, some additional data is being downloaded and that is why you see delays.

That can be GPS issue as well. Can you record GPX log?

**Comment by bluesnow4425** [comment]
Got it. Will use gpx from next testing.

**Comment by starand** [comment]
Hi @bluesnow4425, is there any updates? Or how long we should keep the ticket opened?

**Comment by starand** [comment]
Please comment or create new issue once you have more information.
