### ISSUE TITLE
HOW to use your examples with latest sdk ?

### ISSUE THREAD

**Issue by SheptunovaAA** [heremaps/here-android-sdk-examples#276]
No one of this examples is still working - cause the half of code is not provided by last HERE sdk!

**Comment by NazarKacharaba** [comment]
Please try again. 
If it is still does not work, then you may read the [short guide that explains how to use example projects](https://github.com/heremaps/here-android-sdk-examples/blob/master/README.md).

**Comment by SheptunovaAA** [comment]
> Please try again.
> If it is still does not work, then you may read the [short guide that explains how to use example projects](https://github.com/heremaps/here-android-sdk-examples/blob/master/README.md).

No, you don't understand me. The half of classes in this examples are not exist in latest sdk (nor in 'aar' file, nor in 'api references').

All keys, app_ids etc were setup in projects, but after sync and build many 'here' classes from examples are deleted\not existed. 
For example - class `import com.here.android.mpa.routing.RouteWaypoint;` in example `routing`.

**Comment by SheptunovaAA** [comment]
<img width="394" alt="Снимок экрана 2019-08-27 в 11 58 57" src="https://user-images.githubusercontent.com/5654812/63757030-156a2800-c8c2-11e9-94bf-9615e683c252.png">
For example - part of imports from `MapFragmentView` from `routing` example. As you can see - part of classes from `here sdk` are available, and part - not

**Comment by SheptunovaAA** [comment]
@NazarKacharaba 
I'm also want to use class 'import com.here.android.mpa.mapping.customization.CustomizableScheme;' from this [userguide section](https://developer.here.com/documentation/android-premium/dev_guide/topics/map-customization.html), but it also not exist in the latest aar file.. But in api it is mentioned

**Comment by NazarKacharaba** [comment]
Try to re-invalidate cache in Android Studio: File -> Invalidate caches /Restart -> Invalidate and restart.

**Comment by SheptunovaAA** [comment]
> Try to re-invalidate cache in Android Studio: File -> Invalidate caches /Restart -> Invalidate and restart.

Just because you ask, I've done it. But it have no effect.

Have a look to classes in latest `here sdk`, for ex - we want to find `CustomizableScheme `. But the package `com.here.android.mpa.mapping.customization` is not exist in official aar file:

<img width="547" alt="Снимок экрана 2019-08-27 в 14 55 11" src="https://user-images.githubusercontent.com/5654812/63769208-e7451200-c8da-11e9-9e6f-13111608abd9.png">

Note - I've got 'premium sdk' for trial period, and after then - get aar file from official site.

**Comment by SheptunovaAA** [comment]
So, I've found what's problem was in. 
I've download both premium and standard sdk again, and part of classes were found in one aar file, and another part of here classes were found in second aar file. 

I don't understand why all classes from standard aar plan not included in premium.. It's Very strange for me 

But the cause of problem was in bad aar files, so i'm closing this issue..

**Comment by SheptunovaAA** [comment]
So, I've found what's problem was in.
I've download both premium and standard sdk again, and part of classes were found in one aar file, and another part of here classes were found in second aar file.

I don't understand why all classes from standard aar plan not included in premium.. It's Very strange for me

But the cause of problem was in bad aar files, so i'm closing this issue..
