### ISSUE TITLE
custom route

### ISSUE THREAD

**Issue by SheptunovaAA** [heremaps/here-android-sdk-examples#277]
Hello, guys! 
Please tell me, can I show my custom route on your map?
At this moment class 'Route' has private constructor, so I could't do it.. I have list of geocoordinates and I want to show this collection as a route on your map.

**Comment by NazarKacharaba** [comment]
`Route` can be constructed internally by the SDK, you can not provide custom coordinates to it.
However if you just need to show graphical object on map, you can use `MapPolyline` class that can be built with list of geo coordinates.

**Comment by SheptunovaAA** [comment]
Ok, thk you!
