### ISSUE TITLE
Does the Image object support vector resources?

### ISSUE THREAD

**Issue by SheptunovaAA** [heremaps/here-android-sdk-examples#279]
I'm trying to use vector drawable when creating `Image` object like this:
```
Image image = new Image();
 try {
        image.setImageResource(R.drawable.ic_location_on_black_24dp);
} catch (IOException e) {
        e.printStackTrace();
}
```
But when I run the app it crashes with such error:
`
Process: com.mapstutorial.simplerouting, PID: 2637
    java.lang.IllegalArgumentException: Image provided is invalid.
`

With `Here sdk` I can use only raster drawables?  In other places in app vector drawables works fine

**Comment by NazarKacharaba** [comment]
`Image` class does not support vector images. You can either convert them to bitmap at runtime or have another `png` copy in your assets.

**Comment by SheptunovaAA** [comment]
> `Image` class does not support vector images. You can either convert them to bitmap at runtime or have another `png` copy in your assets.

Ok, thank you for reply.
