### ISSUE TITLE
Traffic update lines are not visible (Red/Green).

### ISSUE THREAD

**Issue by Murali-Krishnan** [heremaps/here-android-sdk-examples#282]
we are trying to make traffic lines visible on the map.
tried this traffic-related codes on map initialized. nothing is shown.

map.setMapScheme(Map.Scheme.NORMAL_TRAFFIC_DAY);
map.setTrafficInfoVisible(true);       
map.getMapTrafficLayer().setEnabled(MapTrafficLayer.RenderLayer.FLOW,false);
map.getMapTrafficLayer().setEnabled(MapTrafficLayer.RenderLayer.ONROUTE, true);

we are testing currently in India.

**Comment by Murali-Krishnan** [comment]
@Merlin1stHere
We are not requesting traffic info for our route.
But we have managed to get the traffic update only for my current route. Please refer the screenshot.

![Screenshot from 2019-09-13 12-11-24](https://user-images.githubusercontent.com/19664492/64842974-6d728f80-d621-11e9-92df-fde8039ed5f4.png)

Code snippet : 
//Setting enable update for TrafficUpdater instance to true.
TrafficUpdater.getInstance().enableUpdate(true);

//Setting the map scheme.
CustomizableScheme scheme = mMap.createCustomizableScheme("CARNAV_TRAFFIC_DAY", Map.Scheme.CARNAV_TRAFFIC_DAY);
mMap.setMapScheme(scheme);

//Creating a map route object, enabling traffic for that. And adding this to map.
MapRoute mapRoute = new MapRoute(route);
mapRoute.setTrafficEnabled(true);
mMap.addMapObject(mapRoute);

//Enabling traffic layers and info to the maps.
mMap.setTrafficInfoVisible(true);
mMap.getMapTrafficLayer().setEnabled(MapTrafficLayer.RenderLayer.ONROUTE, true);
mMap.getMapTrafficLayer().setEnabled(MapTrafficLayer.RenderLayer.FLOW, false);
mMap.getMapTrafficLayer().setDisplayFilter(TrafficEvent.Severity.VERY_HIGH);
mMap.getMapTrafficLayer().setDisplayFilter(TrafficEvent.Severity.HIGH);

If you check the above code snippet, the FLOW layer is disabled and we are not requesting traffic info for our route. Even though traffic updates are visible on the map.
Do any malfunctions would occur for traffic update on the map if we disable FLOW layer and not request traffic info for our route ??

**Comment by Merlin1stHere** [comment]
@Murali-Krishnan Generally no, but in your case the traffic info will be downloaded for visible area and not more often than TrafficUpdater refresh interval.
**TrafficUpdater.RequestInfo info = trafficUpdater.request(route, callback);** will get traffic info for the whole route.

**Comment by Murali-Krishnan** [comment]
@Merlin1stHere
Thanks for your support, we have requested traffic info for the whole route. 
Code Snippet : 
	TrafficUpdater.getInstance().request(route, trafficListener);

    private TrafficUpdater.Listener trafficListener = new TrafficUpdater.Listener() {
        @Override
        public void onStatusChanged(TrafficUpdater.RequestState requestState) {
            Log.i(TAG, requestState.name());
        }
    };

It's working as expected. **We may close this issue thread.**
Once again thanks for your great support.
