### ISSUE TITLE
How to implement animation for marker

### ISSUE THREAD

**Issue by ChenYuehNung** [heremaps/here-android-sdk-examples#283]
Hi
We have implemented this marker animation on the Mapbox SDK. Now we are trying to implement the same functionality on the HERE SDK. But we can't find any way to get the marker layer and set the properties from the document. Can you tell me how to implement animation on the marker?
Thank you.
![Breathing icon_location](https://user-images.githubusercontent.com/12604467/64754847-8e70ad00-d55b-11e9-9a4c-5f1827dd8786.gif)

**Comment by NazarKacharaba** [comment]
Yeah, you have to change radius of `MapCircle` based on zoom level.

You have the size in pixel of your bitmap in `MapMarker`, you can convert this value to geo distance based on current zoom level with help of `Map.getScaleFromZoomLevel(zoomLevel)` method. So basically this will be your `radius` for `MapCircle`.

**Comment by NazarKacharaba** [comment]
Code snipped to see how to change `MapCircle` radius based on current map radius.
```
private float delta = 0f;
void changeCircleRadiusForCurrentFrame() {
    handler.postDelayed(new Runnable() {
        @Override
        public void run() {
            double scale = m_map.getScaleFromZoomLevel(m_map.getZoomLevel());
            float imageSizeInInches = markerBitmap.getWidth() / getResources().getDisplayMetrics().xdpi;

            // 100 - convert to meters;  2 - half size of the image to represent circle radius
            double imageRadiusInGeoMeters = scale * imageSizeInInches  / 100 / 2;
            double currentRadiusForAnimation = imageRadiusInGeoMeters + imageRadiusInGeoMeters * delta;

            circle.setRadius(currentRadiusForAnimation);

            delta = delta >= 0.3f ? 0f : delta + 0.01f;

            changeCircleRadiusForCurrentFrame();
        }
    }, 16);
}
```

**Comment by ChenYuehNung** [comment]
> Code snipped to see how to change `MapCircle` radius based on current map zoom level.
> 
> ```
> private float delta = 0f;
> void changeCircleRadiusForCurrentFrame() {
>     handler.postDelayed(new Runnable() {
>         @Override
>         public void run() {
>             double scale = map.getScaleFromZoomLevel(m_map.getZoomLevel());
>             float imageSizeInInches = markerBitmap.getWidth() / getResources().getDisplayMetrics().xdpi;
> 
>             // 100 - convert to meters;  2 - half size of the image to represent circle radius
>             double imageRadiusInGeoMeters = scale * imageSizeInInches  / 100 / 2;
>             double currentRadiusForAnimation = imageRadiusInGeoMeters + imageRadiusInGeoMeters * delta;
> 
>             circle.setRadius(currentRadiusForAnimation);
> 
>             delta = delta >= 0.3f ? 0f : delta + 0.01f;
> 
>             changeCircleRadiusForCurrentFrame();
>         }
>     }, 16);
> }
> ```

Hi @NazarKacharaba 
Thanks for your sample code and support. I have been finished animation for the marker.
