### ISSUE TITLE
the title of map package shows in wrong locale

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#285]
Hi i'm making download offline maps page, and i found that for most devices it shows in wrong locale when it's set to Traditional Chinese. Include Sony, Google Pixel shows simplified Chinese instead even if the system is set to traditional Chinese. I tried to set it to Traditional Chinese (Hong Kong), Traditional Chinese (Macau), and Traditional Chinese (Taiwan), none of above works, it still shows simplified Chinese.

At the same time, navigation manager works fine on all testing devices and returns Traditional Chinese road name and direction.

PS: It works fine on xiaomi and Asus mobiles. Same setting on all mobile phones but Xiaomi and Asus shows Traditional Chinese but Google and Sony shows simplified.

**Comment by starand** [comment]
Hi @bluesnow4425 
Most likely the fix will be available in SDK 3.15

**Comment by starand** [comment]
Please reopen if the issue is reproducible with SDK 3.15 (once available).
