### ISSUE TITLE
Do not force MapEngine initialization in AndroidXMapFragment

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#294]
HERE SDK `MapView` can be used without any fragment, but using the fragment is very convenient as it handles all the `onResume()`, `onPause()` calls and handles saving the `MapView` state.

Current implementation of `AndroidXMapFragment` requires calling an `init()` function before a `Map` object is created and assigned to `MapView`. 

In our application we use map on several screens and as the initialization of `MapEngine` is time intensive, we do the initialization during the start of an application before any `MapView` is shown.

When first screen with `MapView` arrives, we are already ready to use it (`MapEngine` is initialized) but we are still forced to call an `AndroidXMapFragment`s `init()` function which have 2 drawbacks:

1. We need to handle the callback and wait with any map operation until the initialization is done which complicates the already complicated fragment lifecycle.
2. Even though the `MapEngine` is already initialized the fragments `init()` function call takes few hundreds milliseconds which just unnecessarily extends the loading time of each screen.

Can we get an API on `AndroidXMapFragment` that will just create a `Map` and set it to `MapView` without force us to call initialization?
Or at least would it be possible to make the `init()` function call do nothing when the `MapEngine` is already initialized and just return immediately with `Map` and `MapView` ready?

**Comment by NazarKacharaba** [comment]
Thanks for your suggestion.

Method `AndroidXMapFragment.init(context, listener)` not only initializes `MapEngine`, but also initializes fragment related objects. In case `MapEngine` is initialized, it will not be reinitialized again. 

Implementing new synchronous method `init()`(something like `val result = fragment.init()`) will not help much as it will also take few hundreds milliseconds to execute.

Another approach could be to call `AndroidXMapFragment.init(context, listener)` internally, but that will probably break existing behavior.
