### ISSUE TITLE
Non Public API usage in HEREMaps (3.13.2)

### ISSUE THREAD

**Issue by krezzoid** [heremaps/here-android-sdk-examples#295]
Hey guys,

We would like to update our apps in Apple Store and have the following error:

> **ITMS-90338: Non-public API usage** - The app references non-public symbols in Frameworks/NMAKit.framework/NMAKit: _getcontext, _makecontext, _setcontext. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by starand** [comment]
We are actively working on fix and most probably fix will be available next week. (Issues on iOS side should be reported under https://github.com/heremaps/here-ios-sdk-examples/issues).
It is already reported on SO - https://stackoverflow.com/questions/58214571/ios-here-sdk-nmakit-private-api-usage

**Comment by krezzoid** [comment]
@starand thanks and sorry for reporting to wrong repo
