### ISSUE TITLE
Crash in some Samsung device when navigationManager.startNavigation(route) called

### ISSUE THREAD

**Issue by mansi-techindustan** [heremaps/here-android-sdk-examples#297]
The issue is in some specific Samsung device. It occurs on my testing device Samsung Galaxy A30 running on Android 9 and its working fine on some Samsung Device. 
The error occur when trying to call `navigationManager.startNavigation(route)`.
The project is using Android Premium SDK.
Please help.

**Comment by mansi-techindustan** [comment]
@starand we are including the .aar file in the project. How can I find the SDK version?

**Comment by starand** [comment]
Use static method Version.getSdkVersion(). 
If this is Java crash - you will see the HERE sdk version in crash call-stack. Please share call-stack as well.

**Comment by mansi-techindustan** [comment]
@starand there were no such method `getSdkVersion()` in Version class. There is`getNativeVersion()`

**Comment by mansi-techindustan** [comment]
@starand I think the sdk version is `3.8.0.104`

**Comment by starand** [comment]
@mansi-techindustan use proper import. Sdk does not provide **getNativeVersion()** in public API.
Recently we released SDK 3.13. Go to dev portal and download the latest SDK.
We do not support so old SDK version. And you did not share the crash call-stack.

**Comment by mansi-techindustan** [comment]
@starand thanks. I will update the SDK and will check it again

**Comment by starand** [comment]
@mansi-techindustan please let us know whether the issue is reproducible or not.

**Comment by mansi-techindustan** [comment]
@starand I have updated the SDK to version 3.8.0.104 still there is crash in navigation and simulation

**Comment by starand** [comment]
@mansi-techindustan, we released recently SDK 3.13. We do not support such old SDK as 3.8. Please update and try to reproduce.

**Comment by mansi-techindustan** [comment]
@starand after updating to 3.13 there are many methods that are missing is there any documentation to see the alternatives.

**Comment by starand** [comment]
@mansi-techindustan - https://developer.here.com/documentation/versions#android
FInd HERE SDK for Android - Premium Edition, find interesting version and you will see what was added/removed. For the latest version you can find documentation in the SDK package. Please let us know if you still have related questions.

**Comment by mansi-techindustan** [comment]
@starand `navigationManager.setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(206)`
the method setVoiceSkin() is not found. Is this feature removed?

**Comment by starand** [comment]
@mansi-techindustan 
VoiceGuidanceOptions voiceGuidanceOptions =
                NavigationManager.getInstance().getVoiceGuidanceOptions();
voiceGuidanceOptions.setVoiceSkin(m_noneVoiceSkin);
...voiceGuidanceOptions.getVoiceSkin();

**Comment by mansi-techindustan** [comment]
@starand thanks there was a method in code `navigationManager.setTtsOutputFormat(NavigationManager.TtsOutputFormat.RAW)` in documentaion its mention that its set to RAW by default. So I have commented the code. All the methods issues have been resolve but we are getting black screen when simulation or navigation starts. The navigation can not start in any of our devices.

**Comment by starand** [comment]
setTtsOutputFormat for now is in VoiceGuidanceOptions class.
Try to compile and run this github sample - https://github.com/heremaps/here-android-sdk-examples/tree/master/turn-by-turn-navigation - does it work?
You can compare with your code.

**Comment by mansi-techindustan** [comment]
@starand thanx. I will compare the above sample code with my project.

**Comment by mansi-techindustan** [comment]
@starand the navigation works now. There was a code
 boolean success =  `com.here.android.mpa.common.MapSettings.setIsolatedDiskCacheRootPath(
                m_activity.getExternalFilesDir(null) + File.separator + ".here-maps",
                "com.package")'
This boolean is check before map initialisation.  The problem is `setIsolatedDiskCacheRootPath` method is deprecated so its returning always false. Is there any alternative method? Is this really necessary in new SDK?

**Comment by starand** [comment]
@mansi-techindustan, this method return **true** only in case it is called before **MapEngine** or **MapFragment** init. Once the engine was initialised it returns false (read method documentation).
Even if it is deprecated? it should work. You can see this in all github sample apps. Please take a look. The problem is on app side.

**Comment by mansi-techindustan** [comment]
@starand thanx, I will take a look in the github sample apps.

**Comment by mansi-techindustan** [comment]
@starand  After updating the latest version of  HereMapsSdk. The size of my apk file is increased from 98 MB to 133 MB. is their any way to reduce the Sdk size?

**Comment by starand** [comment]
@meghanhade, starting from SDK 3.13 (and 3.12.5) we added x86_64 emulators support. That means there are four different ABIs in SDK: arm32, arm64, x86, x86_64. This does not affect end user, as user downloads only his ABI from google play.

Of course, you can remove unneeded ABIs in your build.
Take a look on **Native Libraries and ABI Spilts section** - https://developer.here.com/documentation/android-premium/dev_guide/topics/development-tips.html
And you can removed other native libraries - https://developer.here.com/documentation/android-premium/dev_guide/topics/size-management.html

**Comment by mansi-techindustan** [comment]
@starand where can I chat with support, I need some help in navigation?

**Comment by starand** [comment]
The best and probably quickest way is to create an issue here.

**Comment by mansi-techindustan** [comment]
@starand we are displaying turn-by-turn using this listener, how can I know that we reached a destination. Currently we are using below code to check if we reached the destination or no which seems to be working in few destination not in all destination.
`private NavigationManager.NewInstructionEventListener instructionHandler = new NavigationManager.NewInstructionEventListener() {
@Override
public void onNewInstructionEvent() {
Maneuver m = m_navigationManager.getNextManeuver();
if (m.getDistanceToNextManeuver() <= 0.0) {
                tvTurnType.setText("You have reached your Destination");
            }
}

}`

**Comment by starand** [comment]
Please create separate ticket for each issue.
NavigationManager.getDestinationDistance() returns the current distance to destination.
