### ISSUE TITLE
Stick dom marker in here maps on zooming

### ISSUE THREAD

**Issue by eaglesiar** [heremaps/here-android-sdk-examples#299]
I'm trying to add a truck Marker in the HERE Map. This marker is basically a truck icon. Here is my code.

```
 addDomMarker(posObj): void {
      const map = this.mapComponent.getMap();
      (window as any).mymap = map;
      const domIcon = new H.map.DomIcon(truckIcon);
      this.truckMarker = new H.map.DomMarker(posObj, {
           icon: domIcon
           });

      map.addObject(this.truckMarker);
      map.setCenter(posObj);
   }



 export const truckIcon = `<div class="truck-container">
 <svg class="truck-marker" id="truck"
      ...        // svg code 
 </svg></div>`;
```
Problem is when I'm zooming in or out, instead of sticking to the map , the dom marker is moving(animation).

Initial Position:
https://i.stack.imgur.com/qY3lj.png

After zoom out: ( black color dot is initial position.)

https://i.stack.imgur.com/lIR6i.png

After that it comes back to initial position. I want this marker to stick on the map rather that having animation. Is there any work around?

**Comment by starand** [comment]
Hi @eaglesiar 
There is no DomMarker class in SDK. Do you use MapMarker? Can you record a video to understand what is wrong?

**Comment by eaglesiar** [comment]
https://developer.here.com/documentation/maps/topics_api/h-map-dommarker.html

**Comment by starand** [comment]
Provided documentation is for "Maps API for JavaScript". This project is for MobileSDK Android.
