### ISSUE TITLE
Delay in getting position from PositioningManager.OnPositionChangedListener

### ISSUE THREAD

**Issue by mansi-techindustan** [heremaps/here-android-sdk-examples#301]
I am trying to display position indicator when navigation starts, but the position changed listener update the location late. I need to display the marker just after navigation start button clicked.

**Comment by starand** [comment]
@mansi-techindustan, thank you for reporting. We will take a look.
Please provide the following info: SDK version, Android OS version and whether it is related to some phone model/vendor?

**Comment by mansi-techindustan** [comment]
@starand it's in all device. Currently I am testing on Android Pie device and HereMap sdk version is 3.13.3.105

**Comment by Merlin1stHere** [comment]
@mansi-techindustan Navigation requires accurate positions for matching to the exact place on a road.
Location changed events from device with low accuracy are ignored during navigation. This situation is possible when starting navigation if the GPS coordinates are not yet available. (Coordinates given from network usually inaccurate). You can use PositioningManager.getLastKnownPosition to set marker immediately.
