### ISSUE TITLE
How to recenter map when a navigation is active?

### ISSUE THREAD

**Issue by mansi-techindustan** [heremaps/here-android-sdk-examples#302]

**Comment by starand** [comment]
@mansi-techindustan, try NavigationManager.setMapUpdateMode(MapUpdateMode mode)
Please let us know whether this is what you need.

**Comment by mansi-techindustan** [comment]
@starand ```mNavigationManager.setMapUpdateMode(NavigationManager.MapUpdateMode.ROADVIEW)```
This was used in the existing code. This only zoom at the centre of the current map position open, not in route of the Navigation running.

**Comment by starand** [comment]
I guess you need MapUpdateMode.NONE and you can sue methods like setCenter/setZoomLevel/setTilt.
Or if this does not match your expectation, please describe what you need in more words.

**Comment by starand** [comment]
@mansi-techindustan did you solve the issue? Do you have further questions?

**Comment by mansi-techindustan** [comment]
@starand  Thanku for the guidance. I have resolved the issues.
