### ISSUE TITLE
How to reduce onMapObjectsSelected latency?

### ISSUE THREAD

**Issue by MathieuChabas** [heremaps/here-android-sdk-examples#303]
Hello,
I am using Here SDK Starter Edition and I am experiencing some latency when selecting a marker. I made some tests with a Samsung Galaxy S9, Android 9, SDK version 3.13, and I recorded a latency of around 850 ms between onPanStart() and onMapObjectsSelected(), which becomes significant for the users. The latency is almost imperceptible with the iOS SDK. 
Is there a way to reduce this latency or to get the selected marker before the method onMapObjectsSelected() is fired? Thank you!

**Comment by starand** [comment]
Hi @MathieuChabas,
Such behaviour was implemented intentionally. In case this is two finger gesture, onMapObjectsSelected() and onTap() is not triggered. There is no way to somehow speed up this.

But you can get selected objects in onLongPressEvent() which takes point as a parameter:
```
int pointX = (int) p.x;
int pointY = (int) p.y;
int tapAreaSize = 50;

ViewRect tapArea = new ViewRect(pointX - (tapAreaSize >> 1), 
                pointY - (tapAreaSize >> 1), tapAreaSize, tapAreaSize);

Map.getSelectedObjects(tapArea);
```
Hope that helps. Please close ticket if there it no further questions.
