### ISSUE TITLE
Discrepancy in place data in case of online search and offline search

### ISSUE THREAD

**Issue by xsveda** [heremaps/here-android-sdk-examples#305]
SDK: Android Premium 3.13

When an `ExploreRequest` is done in the same area when a device is online and offline there is a big discrepancy in the result data for the same places. 

The [documentation](https://developer.here.com/documentation/android-premium/dev_guide/topics/places-offline.html) states the in the offline mode search there might be some detailed place information missing (ratings, reviews, etc.)...that's fine. 

The problem is that offline place data also lacks any kind of ID (we tried both `pvid` and `sharing` reference). There is also a difference in other "basic" data such as place name or location.

As an example this part a search result for the same fuel station in the US:

|| OFFLINE  | ONLINE |
| ------------- | ------------- | ------------- |
| Reference (pvid) | missing  | available |
| Reference (sharing) | missing  | available |
| Name | Mega Mart  | MEGA Mart |
| Latitude	| 36.95320129  | 36.953301 |
| Longitude | -84.08510685  | -84.08513 |

We need to recognize that the offline and online results are connected to the same place. One of our use cases is to build a Favorites Places feature where user can mark a selected place as Favorite despite the current connection mode.

Is it possible to pair offline and online results for the same place?

**Comment by starand** [comment]
Hi @xsveda,

As you can see in **Release Notes**, **Known Issues** paragraph, _"Online and offline Place search results may differ when both an explicit search center and an implicit viewport are sent."_
That happens because different data sources are used for online and offline search. Online data is being updated more frequently. And not all data can be included into offline packages.

**Comment by xsveda** [comment]
Hi @starand thanks for the info!

Do you know about any options how to match these two versions of the same place data?

**Comment by starand** [comment]
You only can try to match location and name of POI. There is no other way to do that. And there is no simple solution for the issue as well.
