### ISSUE TITLE
Disabling real gps coordinates.

### ISSUE THREAD

**Issue by EugeneZaychenko** [heremaps/here-android-sdk-examples#310]
Hello, I use your Android SDK (premium) in my application, the essence of which is sending a fake location.
The problem is that the real gps coordinate is periodically sent.
The only assumption is that your SDK sends real coordinates. Is it so? If so, how can this be disabled or redefined?

I send gps like this
mLocationManager.setTestProviderLocation (LocationManager.GPS_PROVIDER, mockLocation)

**Comment by NazarKacharaba** [comment]
Hi @EugeneZaychenko 
It would really help if you provide a bit of code so we can narrow down the problem. Does this happen during navigation?

>The problem is that the real gps coordinate is periodically sent.

What does this mean? Do you receive real location in your listener` android.location.LocationListener.onLocationChanged(Location location)` that listens device location changes?

HERE SDK can only act as a mock location provider when you call `PositionSimulator.startPlayback(String gpxFile)` method.

**Comment by EugeneZaychenko** [comment]
It happens all the time. It seems to me that the problem is related to PositionIndicator. I set isVisible and isAccuracyIndicatorVisible = false but the coordinates are sent. This is my guess.

To send a fictitious location, I create a route and use NavigationManager.getInstance()?. simulate (route, speed). Then I take GeoPosition from NavigationManager.PositionListener() and use the standard for Android method mLocationManager.setTestProviderLocation(LocationManager.GPS_PROVIDER, mockLocation)

**Comment by NazarKacharaba** [comment]
Try to call `PositioningManager.stop()`, then HERE SDK will not listen to the real device location.
After that you can call `NavigationManager.simulate(route, speed)`.  In route simulation, active `PositionIndicator` will only show matched position from the `NavigationManager.PositionListener` callback, disabled indicator should not be shown on the map nor should it make coordinates to be sent anywhere.

If this does not help, please provide working example to reproduce your issue, I'm not sure I understand what you are trying to achieve.

**Comment by starand** [comment]
@EugeneZaychenko are there any updates? Otherwise we will close the ticket.
