### ISSUE TITLE
MapLoader.getMapPackages() returns outdated result

### ISSUE THREAD

**Issue by ondree** [heremaps/here-android-sdk-examples#312]
Hello, we have issue with MapLoader after updating to android sdk 3.13. `MapLoader.getMapPackages()` does not return updated `MapPackages` when any of children packages is uninstalled. 

For example, when whole USA package is installed and we try to uninstall Alabama – operation is finished with `ResultCode.OPERATION_SUCCESSFUL` and `MapLoader.Listener.onUninstallMapPackagesComplete` callback is notified with correctly updated `MapPackage` object (Alabama is `NOT_INSTALLED`). 

When we call `MapLoader.getMapPackages()` later, `MapLoader.Listener.onGetMapPackagesComplete` callback gets outdated data and uninstalled package is returned again with `INSTALLED` state. 

We are using android-premium sdk 3.13.3.105, It was working as expected with version 3.12.4.88.

**Comment by NazarKacharaba** [comment]
Hi @ondree, thanks for reporting this issue! We are working to fix this.

**Comment by NazarKacharaba** [comment]
@ondree 
Could you try latest HERE SDK version 3.14 and check whether issue is still reproducible? Thanks.
