### ISSUE TITLE
Calculate route with VPN on Android

### ISSUE THREAD

**Issue by joseBarreto** [heremaps/here-android-sdk-examples#314]
Hello,
Are there any restrictions on using the map when a VPN is enabled on Android?

I use a tool to monitor the size of data traveling in applications, but when it is turned on and I try to calculate a route I get.

"INSUFFICIENT_MAP_DATA =
The route cannot be calculated because there is not enough local map data to perform route calculation. "

Is this correct?

**Comment by starand** [comment]
Hi @joseBarreto,
There is no any restriction related to VPN.
The INSUFFICIENT_MAP_DATA issue can happen, when you try to create a route right after map engine is initialised.  Try to add few seconds pause after mapEngine/mapFragment is initialised.

We will try to reproduce. Is the issue specific to some VPN or you can reproduce it with different VPNs?
Is it Android or device specific?

**Comment by starand** [comment]
We tried to reproduce the issue, but we could not.
Is there any updates from your side?
