### ISSUE TITLE
Change distance units on Voice Routing

### ISSUE THREAD

**Issue by cfsbhawkins** [heremaps/here-android-sdk-examples#315]
So how does one change the voice direction units from kilometers to miles? I am using a US TTS voice?
I am using voice skin 206, is there a different voice pack I should be using?

**Comment by starand** [comment]
Hi @cfsbhawkins 

Please use the following API:
`NavigationManager.setDistanceUnit(UnitSystem us)`

**Comment by cfsbhawkins** [comment]
Thanks that worked, I was looking under voice options.
