### ISSUE TITLE
MapObject as a PositionIndicator 

### ISSUE THREAD

**Issue by dhananjay23** [heremaps/here-android-sdk-examples#325]
Hello Team,

How to assign custom MapObject as a PositionIndicator,
I want to change current user position icon

Thank you
Regards

**Comment by LiXiaohezi** [comment]
// create a map marker to show current position
                                            Image icon = new Image();
                                            m_positionIndicatorFixed = new MapMarker();
                                            try {
                                                icon.setImageResource(R.drawable.gps_position);
                                                m_positionIndicatorFixed.setIcon(icon);
                                            } catch (IOException e) {
                                                e.printStackTrace();
                                            }

                                            m_positionIndicatorFixed.setVisible(true);
                                            m_positionIndicatorFixed.setCoordinate(m_map.getCenter());
                                            m_map.addMapObject(m_positionIndicatorFixed);

                                            m_mapFragment.getPositionIndicator().setVisible(false);

**Comment by LiXiaohezi** [comment]
// create a map marker to show current position
                                            Image icon = new Image();
                                            m_positionIndicatorFixed = new MapMarker();
                                            try {
                                                icon.setImageResource(R.drawable.gps_position);
                                                m_positionIndicatorFixed.setIcon(icon);
                                            } catch (IOException e) {
                                                e.printStackTrace();
                                            }

                                            m_positionIndicatorFixed.setVisible(true);
                                            m_positionIndicatorFixed.setCoordinate(m_map.getCenter());
                                            m_map.addMapObject(m_positionIndicatorFixed);

                                            m_mapFragment.getPositionIndicator().setVisible(false);

**Comment by dhananjay23** [comment]
I have already implemented using MapMarker but MapMarker will not turned (yaw/head angle) 

Another MapMarker implemented using MapLocalModel  as per below code but MapLocalModel will not move smoothly,
please suggest me how can i achieve smoothly move marker like PositionIndicator


```
private var indicator: MapLocalModel?
if (indicator != null) return

        indicator = MapLocalModel()
        val size = 3f

        val buff = FloatBuffer.allocate(12)
        buff.run {
            put(-size / 2f)
            put(-size / 2f)
            put(0f)
            put(-size / 2f)
            put(size / 2f)
            put(0f)
            put(size / 2f)
            put(-size / 2f)
            put(0f)
            put(size / 2f)
            put(size / 2f)
            put(0f)
        }


        val vertIndicieBuffer = IntBuffer.allocate(6)
        vertIndicieBuffer.run {
            put(2)
            put(1)
            put(0)
            put(1)
            put(2)
            put(3)
        }

        val textCoordBuffer = FloatBuffer.allocate(8)
        textCoordBuffer.run {
            put(0f)
            put(0f)
            put(0f)
            put(1f)
            put(1f)
            put(0f)
            put(1f)
            put(1f)
        }

        val myMesh = LocalMesh()
        myMesh.vertices = buff
        myMesh.vertexIndices = vertIndicieBuffer
        myMesh.textureCoordinates = textCoordBuffer
        indicator!!.mesh = myMesh
        indicator!!.scale = 1f
        val img = Image()
        try {
            img.setImageResource(R.drawable.location_navigation_arrow)
        } catch (e: IOException) {
            Toast.makeText(this@NavigationMapActivity, e.message, Toast.LENGTH_SHORT).show()
        }
        indicator!!.texture = img

        indicator!!.isDynamicScalingEnabled = true // keep size when zooming
        mapFragment!!.positionIndicator.isVisible = false
        map!!.addMapObject(indicator)

```

**Comment by Merlin1stHere** [comment]
@dhananjay23 If you want to change current user position icon just use the PositionIndicator.setMarker function.
https://developer.here.com/documentation/android-premium/api_reference_java/com/here/android/mpa/mapping/PositionIndicator.html#setMarker-com.here.android.mpa.common.Image-

**Comment by Merlin1stHere** [comment]
@dhananjay23 You can rotate the image for the position indicator in the OnTransformListener.onMapTransformEnd callback

**Comment by dhananjay23** [comment]
This method is not calling when navigation start

**Comment by Merlin1stHere** [comment]
@dhananjay23 You can create a function that rotate image for the position indicator using map angle and current position course. Then call it where you need, immediately after starting navigation and also in OnTransformListener.onMapTransformEnd callback.
