### ISSUE TITLE
Navigation example is missing to show TTS

### ISSUE THREAD

**Issue by datasun** [heremaps/here-android-sdk-examples#326]
The current navigation example could be improved to show how to include default voice instructions (EN). Currently the [inlined comments ](https://github.com/heremaps/here-android-sdk-examples/blob/master/turn-by-turn-navigation/app/src/main/java/com/here/android/example/guidance/MapFragmentView.java)are a bit vague. It reads like there is TTS working out-of-the-box and that NavigationManager is enough to enable it - but apparently that's not the case?

**Comment by starand** [comment]
Hi @datasun 
The sample was added - https://github.com/heremaps/here-android-sdk-examples/tree/master/voice-navigation

**Comment by datasun** [comment]
@starand Thanks!
