### ISSUE TITLE
Getting Missing File error while initializing map engine when resuming from background.

### ISSUE THREAD

**Issue by binod-techindustan** [heremaps/here-android-sdk-examples#327]
Recently I developed Map features by using HereMap premium Sdk, and things were going well. But I found an issue during multitasking, by keeping the Navigation on the App got BLACK screen with 'missing file Error' during switching between apps. When pressing back I got a crash with error message `com.here.android.mpa.common.UnintializedMapEngineException: Cannot create HERE SDK object before MapEngine is initialized.`.My testing device is Realme C2  with Android version 9 having RAM 2GB.

**Comment by binod-techindustan** [comment]
@starand Please review my issue.

**Comment by binod-techindustan** [comment]
@starand  could you please check the issue.

**Comment by NazarKacharaba** [comment]
Hi @binod-techindustan 
In your case, exception `UnintializedMapEngineException` means that your application was killed by the OS while it was in the background. You need to call `MapEngine.init(...)` or `AndroidXMapFragment.init(..)` again when your app returns from background.

In your `onCreate` method you can check if `MapEngine.isInitialized()` and then do initialization if needed.

**Comment by starand** [comment]
@binod-techindustan, does proposed solution work for you?

**Comment by binod-techindustan** [comment]
@NazarKacharaba we have been initializing the Map Engine on `onCreate` using Map Fragment `init` method. We OS killed the `activity` when resuming the screen it calls `onCreate` method again. So is there any other way to initialize the engine.  
``` m_mapFragment.init( new OnEngineInitListener() {
                @Override
                public void onEngineInitializationCompleted(OnEngineInitListener.Error error) {
if (error == Error.NONE) {
m_map = m_mapFragment.getMap();
........
}else{
//showing error
      }
});```

**Comment by NazarKacharaba** [comment]
What kind of `Error` do you receive in `onEngineInitializationCompleted` callback(There is `getDetails`, `getStackTrace`, `getThrowable` in `Error` type)?

**Comment by starand** [comment]
Closing ticket as no response.
