### ISSUE TITLE
NavigationManager.AudioFeedbackListener is not working correctly

### ISSUE THREAD

**Issue by Pavlikevych** [heremaps/here-android-sdk-examples#333]
Callbacks from AudioFeedbackListener are working in random order or it doesn't work at all.

**Comment by starand** [comment]
Hi @Pavlikevych,
Could you please provide sample app where you see the issue?
Which SDK version do you use? What about Android, device version? Is it reproducible on all devices?

**Comment by Pavlikevych** [comment]
SDK version v3.14.2_192. Google Pixel 3 Android 10. reproduced on Google Pixel 3

**Comment by Merlin1stHere** [comment]
@Pavlikevych What do you mean when you say about random order?
Keep in mind that if new audio starts play when another one is playing you don't receive onAudioEnd callback. So the order shown below is normal.
onAudioStart
onAudioStart
onAudioStart
onAudioStart
onAudioStart
onAudioEnd
onAudioStart
onAudioStart
onAudioEnd
onAudioStart
onAudioEnd
onAudioStart
...

**Comment by Pavlikevych** [comment]
For example, I have shown below order 
onAudioStart
onAudioEnd
onAudioEnd
or Callbacks doesn't work during guidance.

**Comment by Merlin1stHere** [comment]
I can't reproduce the issue.
Can you reproduce this bug using our navigation example?
https://github.com/heremaps/here-android-sdk-examples/tree/master/advanced-navigation
Is this issue reproducible on other device?

**Comment by Pavlikevych** [comment]
yes, I reproduced it, using this navigation example in real route guidance, it is working shown below order, and only in the first time 
onAudioStart
onAudioEnd
I reproduced it on Google Pixel 3, Google Pixel 1 and emulators(simulate route)

**Comment by Merlin1stHere** [comment]
@Pavlikevych What voice skin did you use?

**Comment by Pavlikevych** [comment]
@Merlin1stHere en_US_male, languageCode: en-US

**Comment by Merlin1stHere** [comment]
@Pavlikevych. Unfortunately, I still cannot reproduce the issue. Could you provide us with a complete sample that does this?

**Comment by Pavlikevych** [comment]
@Merlin1stHere, Sorry I can not provide the sample.

**Comment by starand** [comment]
@Pavlikevych, you can try to reproduce the issue on one of our github sample (e.g. voice-navigation).
If we cannot reproduce, we cannot fix the issue (if exists).
