### ISSUE TITLE
How to mute and unmute voice guidance during navigation? 

### ISSUE THREAD

**Issue by binod-techindustan** [heremaps/here-android-sdk-examples#337]
We are trying add feature to mute and unmute voice guidance. We can disable the voice using `navigationManager.getAudioPlayer().stop()`. How to properly re-enable the audio.

**Comment by binod-techindustan** [comment]
@starand please help

**Comment by Merlin1stHere** [comment]
@binod-techindustan 
Method stop stops the navigation instruction currently being played. Future instructions will continue to be played.

To mute audio:
navigationManager.getAudioPlayer().setVolume(0)
navigationManager.getAudioPlayer().stop()

To unmute audio:
navigationManager.getAudioPlayer().setVolume(1)

**Comment by starand** [comment]
`navigationManager.getAudioPlayer().stop()` stops only currently playing sound. Usually it is short. 
The next maneuver  instruction will be pronaunced.

To fully stop voice guidance set voice skin with id 100003001.
```
NavigationManager.getInstance().getVoiceGuidanceOptions()
                .setVoiceSkin(m_voiceCatalog.getLocalVoiceSkin(100003001))
```
When you need to enable voice guidance again, set needed voice skin.

**Comment by binod-techindustan** [comment]
Thanks @starand 
Its working fine

**Comment by galisamas** [comment]
Hello, have a similar issue to this. I am trying to change between off, beeping, and full voice. However, 100003001 goes with the beeping, even tho it should be completely no sounds... If I try to turn the volume to 0 (when off) and back to 1 (when beeping and full voice), the beeping stops working... 
So how to manipulate in the middle of the navigation with different voice skins?
