### ISSUE TITLE
Safety Spot Listener Not Triggering When The User Passes The Safety Spot

### ISSUE THREAD

**Issue by Asma-Yasin** [heremaps/here-android-sdk-examples#339]
I am trying to display an icon informing the user that he's expecting a speed camera ahead.

I'm listening to `NavigationManager.SafetySpotListener()` and overriding `onSafetySpot(SafetySpotNotification)` function. Everything is working perfectly fine and the function is being triggered whenever the `NavigationManager` triggers an audible warning. My problem is I have no way of knowing if the `SafetySpotNotification` is still ahead or not.

In iOS, there is a function for `NMASafetySpotWarner`, called `isSafetySpotNotificationInfoAhead`, that does what I need, but I couldn't find its match in Android SDK.

Am I missing something here? Please advise.

**Comment by starand** [comment]
Hi @Asma-Yasin,

Looks like there is no such method on Android side. Thank you for reporting.
As a workaround, you can get current position and distance to camera, and then periodically check whether needed distance is already passed (distance(current, callbackPostioing).

**Comment by starand** [comment]
`SafetySpotChecker.isSafetySpotNotificationInfoAhead(SafetySpotNotificationInfo)` will be added in SDK 3.15 release (will be released around 1st of Apr).
