### ISSUE TITLE
Error: Cannot initalize map libraries_missing 

### ISSUE THREAD

**Issue by bobesianca** [heremaps/here-android-sdk-examples#34]
Hei, 
I have this error on my emulator. I use the emulators from Android Studio, but is not working on any of them.  I mention that i added the library from here in the libs folder. 
Can you help me with that?
thanks :)

**Comment by SirBif** [comment]
Were you using an x86 image? The SDK only supports the ARM ones: https://developer.here.com/mobile-sdks/documentation/android-premium/topics/system-requirements.html

**Comment by bobesianca** [comment]
I did read that, but in Android Studio 2.3 I can not find any ARM arhitectures devices or I don t know where to find. Do you know how? Thanks a lot!

**Comment by bobesianca** [comment]
I have changed it to ARM, but now my emulator says ” Process system isn't responding” and i have to choose to continue or close the app, either way there s no app in my emulator. Thanks for your answer :)

**Comment by SirBif** [comment]
Mmm.. you could try with an image for a different API version. I remember having luck with the API level 18 image, but that was some time ago. Which image were you using?

**Comment by artemnikitin** [comment]
@bobesianca SDK currently not support X86, it means it will not work on emulators, like Genymotion. Please, look on http://stackoverflow.com/questions/39021240/gradle-native-libraries-not-found-on-device-but-present-in-apk/39021670#39021670 to fix

**Comment by sschuberth** [comment]
@artemnikitin But it *should* work in an ARM emulator as suggested by @SirBif, right?

**Comment by artemnikitin** [comment]
@sschuberth in ARM emulator, yes, but it doesn't make sense because it will be much slower than a real device.
