### ISSUE TITLE
Add Cluster on Map Layer (POI Layer)  

### ISSUE THREAD

**Issue by dhananjay23** [heremaps/here-android-sdk-examples#340]
How to add cluster on map layer below code is available for adding NMAMapObject on map layer in iOS
`- (BOOL)addMapObject:(nonnull NMAMapObject *)object toLayer:(NMAMapLayerType)layer `

**Comment by dashchak** [comment]
Please check Dev guide:
https://developer.here.com/documentation/ios-premium/dev_guide/topics/marker-clustering.html
