### ISSUE TITLE
How to get all upcoming maneuvers?

### ISSUE THREAD

**Issue by binod-techindustan** [heremaps/here-android-sdk-examples#341]
We are planning to display all upcoming maneuvers from the current position.

**Comment by starand** [comment]
Hi @binod-techindustan,

Till SDK 3.15 you cannot get instruction list. You receive only callbacks with navigation instruction.

In SDK 3.15 we added that possibility in `Route` class:
`public List<String> getInstructions(Locale locale, InstructionsUnitSystem unitSystem)`

mSDK 3.15 should be released about 1st of April.
