### ISSUE TITLE
How to use Tunnel Extrapolation?

### ISSUE THREAD

**Issue by goldmountain0918** [heremaps/here-android-sdk-examples#345]
I need example how to use tunnel extrapolation.

**Comment by SiriUS2551AK** [comment]
Hello @goldmountain0918,

According to [the official developer`s guide](https://developer.here.com/documentation/android-premium/dev_guide/topics/map-matching.html), the HERE SDK (premium edition) enables the tunnel extrapolation automatically, when the GPS signal is lost while entering a road tunnel.

> SDK for Android performs Map Matching automatically when it needs to match a raw position to the road network, e.g. during drive guidance, where there may be inaccuracies in the road rendering or GPS data. Map matching also supports instances where the GPS signal is lost while entering a road tunnel. The position is extrapolated and updated based on the driver’s speed and knowledge of the tunnel layout.

So, it does not require an additional developer`s work for enabling this feature if you do not use a custom location source.
