### ISSUE TITLE
How to get offline maps update size?

### ISSUE THREAD

**Issue by samvgorode** [heremaps/here-android-sdk-examples#348]
@starand 
To check for updates we use 
`MapLoader`
```
@HybridPlus
    public boolean checkForMapDataUpdate() {
        return this.a.b();
    }
```
But how to get exact update size in Mb before update started ?

**Comment by starand** [comment]
Hi @samvgorode 

Looks like there is no such method on Android, to check update size (we will take a look on iOS implementation and probably will add it next release).

You can use this workaround:
 - request update to needed map version;
 - listen to  MapLoader.Listener#onInstallationSize() callback;
 - use cancelCurrentOperation() if you need to cancel the task.

onInstallationSize() callback will not be triggered if there is no enough space to install update.

Documentation:
```
     * <li>When the update starts, a summary of the update's size can be obtained through the
     * {@link MapLoader.Listener#onInstallationSize(long, long)} callback.</li>
```
```
        /**
         * A callback triggered during certain {@link MapLoader} operations to indicate the size, in
         * KB, of the map data which is to be downloaded and stored for that particular operation.
         *
         * @param diskSize
         *            Amount of disk storage needed for the current operation
         * @param networkSize
         *            Amount of network traffic to be used for the current operation
         */
        void onInstallationSize(long diskSize, long networkSize);
```

**Comment by samvgorode** [comment]
Ok. Thank for a quick answer. So, waiting for the next release...

**Comment by starand** [comment]
This change is too late for mSDK 3.15 release (planned for about 1st of Apr).
