### ISSUE TITLE
m_map.setZoomLevel()

### ISSUE THREAD

**Issue by gwu1234** [heremaps/here-android-sdk-examples#35]
m_map.setCenter(new GeoCoordinate(45.519914, -73.852406),  Map.Animation.LINEAR);
//m_map.setZoomLevel(13.2);
the line in your source code set the center of the map view on this latitude and longitude very nicely if the second line is commented out 

if I remove the comment on the second line, the code becomes
m_map.setCenter(new GeoCoordinate(45.519914, -73.852406),  Map.Animation.LINEAR);
m_map.setZoomLevel(13.2);
map will center on Germany, not on the latitude and longitude

**Comment by artemnikitin** [comment]
In which example do you see this?

**Comment by gwu1234** [comment]
turn-by-turn-navigation

**Comment by artemnikitin** [comment]
I tried your coordinates on the same example and for me, everything works ok. Can you check maybe something wrong is on your side?

**Comment by gwu1234** [comment]
funny
I did not change 1 single line of your sample code 
I simply comment and uncomment the line m_map.setZoomLevel(13.2);

**Comment by JohnLXiang** [comment]
@gwu1234 I'd suggest to use Map.onTransformListener to set zoom level if any animation was used in setCenter() call.  If you have any further questions, please let me know.

**Comment by Xgamefactory** [comment]
you should use setCenter with zoomlevel argument if you wish to setcenter and zoomlevel at once.

> **public void [setCenter ](https://developer.here.com/documentation/android-premium/topics_api_nlp_hybrid_plus/com-here-android-mpa-mapping-map.html#topic-apiref__setcenter-geocoordinate-map-animation-double-float-float)(GeoCoordinate point, Animation animation, double level, float orientation, float tilt)**
> 
> Moves the center of this Map to a specific GeoCoordinate, while simultaneously setting a zoom level (a fraction within the range of minimum and maximum levels), orientation (from 0 degrees to 360 degrees), and tilt (within the range of minimum and maximum tilt angles).
