### ISSUE TITLE
voice navigation 

### ISSUE THREAD

**Issue by gwu1234** [heremaps/here-android-sdk-examples#36]
I wrote a section of code for voice android navigation, but it is not  working  
could you send me (or point me to ) a section of code to turn on voice navigation ?
I need English, French and Spanish in tts

**Comment by JH-YVR** [comment]
Please check the sample https://github.com/heremaps/here-android-sdk-examples/tree/master/turn-by-turn-navigation-android

**Comment by gwu1234** [comment]
I knew this sample code
it has not voice

**Comment by gwu1234** [comment]
this sample navigation does not have any voice related logic and code

**Comment by JH-YVR** [comment]
OK, I understand. For the languages you listed, you first need to download the appropriate voice skins. Check the User Guide section 'Voice Instructions' and there is some code snippets showing how to do this: https://developer.here.com/mobile-sdks/documentation/android-premium/topics/map-voice-instructions.html

**Comment by gwu1234** [comment]
you first need to download the appropriate voice skins:  do I need to download it manually? or it is done programmatically ? and could you give me  a complete sample code for voice navigation ?
after a long struggle, my code is working partially, It supports voice navigation,  but not very stable.

**Comment by artemnikitin** [comment]
@gwu1234 for sure it can be done programmatically. We are in the process of adding more complex navigation example that will cover this.

For now, some examples to look for:
```java
    /**
     * Download catalog
     */
    private void downloadCatalog() {
        /**
         * First get the voice catalog from the backend that contains all available languages (so called voiceskins) for download
         */
        VoiceCatalog.getInstance().downloadCatalog(new VoiceCatalog.OnDownloadDoneListener() {
            @Override
            public void onDownloadDone(VoiceCatalog.Error error) {
                if (error != VoiceCatalog.Error.NONE) {
                    Toast.makeText(activity.getApplicationContext(), "Failed to download catalog", Toast.LENGTH_LONG).show();
                } else {
                    Toast.makeText(activity.getApplicationContext(), "Catalog downloaded", Toast.LENGTH_LONG).show();
                }
            }
        });
    }
```
Later you will be able to get list of available language by doing this:
```java
VoiceCatalog catalog = VoiceCatalog.getInstance();
List<VoicePackage> availableLanguages = catalog.getCatalogList();
```
Then you need to download language:
```java
/**
     * Download voice by ID
     *
     * @param skin_id ID of voice for download
     */
    private void downloadVoice(final long skin_id) {
        VoiceCatalog.getInstance().downloadVoice(skin_id, new VoiceCatalog.OnDownloadDoneListener() {
            @Override
            public void onDownloadDone(VoiceCatalog.Error error) {
                if (error != VoiceCatalog.Error.NONE) {
                    Toast.makeText(activity.getApplicationContext(), "Failed to download voice skin", Toast.LENGTH_LONG).show();
                } else {
                    Toast.makeText(activity.getApplicationContext(), "Voice skin was downloaded", Toast.LENGTH_LONG).show();
                }
            }
        });
    }
```
And finally, to set it for navigation you need to do:
```java
NavigationManager.getInstance().setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(skin_id));
```

**Comment by gwu1234** [comment]
thanks 
will try these

**Comment by Xgamefactory** [comment]
thanks for adding useful example even on stackoverflow  it is not possible to find helpful answers for here sdk questions )

**Comment by stillie** [comment]
Thank you @artemnikitin this helped me out.... a lot simpler than i thought

**Comment by kiskunk** [comment]
This is now deprecated, in the turn-by-turn sample app its only beeping, how can I set up a custom language instead of beeping?

**Comment by sjd753** [comment]
> @gwu1234 for sure it can be done programmatically. We are in the process of adding more complex navigation example that will cover this.
> 
> For now, some examples to look for:
> 
> ```java
>     /**
>      * Download catalog
>      */
>     private void downloadCatalog() {
>         /**
>          * First get the voice catalog from the backend that contains all available languages (so called voiceskins) for download
>          */
>         VoiceCatalog.getInstance().downloadCatalog(new VoiceCatalog.OnDownloadDoneListener() {
>             @Override
>             public void onDownloadDone(VoiceCatalog.Error error) {
>                 if (error != VoiceCatalog.Error.NONE) {
>                     Toast.makeText(activity.getApplicationContext(), "Failed to download catalog", Toast.LENGTH_LONG).show();
>                 } else {
>                     Toast.makeText(activity.getApplicationContext(), "Catalog downloaded", Toast.LENGTH_LONG).show();
>                 }
>             }
>         });
>     }
> ```
> 
> Later you will be able to get list of available language by doing this:
> 
> ```java
> VoiceCatalog catalog = VoiceCatalog.getInstance();
> List<VoicePackage> availableLanguages = catalog.getCatalogList();
> ```
> 
> Then you need to download language:
> 
> ```java
> /**
>      * Download voice by ID
>      *
>      * @param skin_id ID of voice for download
>      */
>     private void downloadVoice(final long skin_id) {
>         VoiceCatalog.getInstance().downloadVoice(skin_id, new VoiceCatalog.OnDownloadDoneListener() {
>             @Override
>             public void onDownloadDone(VoiceCatalog.Error error) {
>                 if (error != VoiceCatalog.Error.NONE) {
>                     Toast.makeText(activity.getApplicationContext(), "Failed to download voice skin", Toast.LENGTH_LONG).show();
>                 } else {
>                     Toast.makeText(activity.getApplicationContext(), "Voice skin was downloaded", Toast.LENGTH_LONG).show();
>                 }
>             }
>         });
>     }
> ```
> 
> And finally, to set it for navigation you need to do:
> 
> ```java
> NavigationManager.getInstance().setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(skin_id));
> ```

You saved my day!! This is clear documentation and on how to use voice navigation!! Here docs sucks!! Thanks man!!!!

**Comment by Ashish-Patel** [comment]
setVoiceSkin() is not working for me. showing can not resolve symbol. can someone help me.?

**Comment by starand** [comment]
@Ashish-Patel 
Do you use Premium or Starter SDK?
Please share snipped of code how you use setVoiceSkin() method.

**Comment by Ashish-Patel** [comment]
m_navigationManager = NavigationManager.getInstance();

                            final VoiceCatalog voiceCatalog = VoiceCatalog.getInstance();
                            voiceCatalog.downloadCatalog(new VoiceCatalog.OnDownloadDoneListener() {

                                @Override
                                public void onDownloadDone(VoiceCatalog.Error error) {
                                    if (error == VoiceCatalog.Error.NONE) {
                                        // Get the list of voice packages from the voice catalog list
                                        List<VoicePackage> voicePackages = voiceCatalog.getCatalogList();
                                        // select
                                        for (VoicePackage vPackage : voicePackages) {
                                            if (vPackage.getMarcCode().compareToIgnoreCase("eng") == 0) {
                                                if (vPackage.isTts()) {
                                                    vid = vPackage.getId();

                                                    if (!voiceCatalog.isLocalVoiceSkin(vid)) {
                                                        voiceCatalog.downloadVoice(vid, new VoiceCatalog.OnDownloadDoneListener() {
                                                            @Override
                                                            public void onDownloadDone(VoiceCatalog.Error error) {
                                                                if (error == VoiceCatalog.Error.NONE) {
                                                                    // set the voice skin for use by navigation manager
                                                                    m_navigationManager.setVoiceSkin(voiceCatalog.getLocalVoiceSkin(vid));
                                                                }
                                                            }
                                                        });
                                                    }
                                                    break;
                                                }
                                            }
                                        }
                                    }
                                }
                            });

**Comment by Ashish-Patel** [comment]
i'm using premium sdk. but haven't paid beacuse sdk was downloadable.

**Comment by starand** [comment]
Most probably the issue happens because setVoiceSkin() was removed from NavigationManager and moved to VoiceGuidanceOptions class. You can use it as below:
```
        VoiceGuidanceOptions voiceGuidanceOptions =
                NavigationManager.getInstance().getVoiceGuidanceOptions();
        voiceGuidanceOptions.setVoiceSkin(voiceSkin);
```

**Comment by Ashish-Patel** [comment]
Thanks Man. You saved my life.!!

**Comment by Ashish-Patel** [comment]
m_mapFragment.init(new OnEngineInitListener() {
                    @Override
                    public void onEngineInitializationCompleted(Error error) {

}
});

i'm getting missing libraries, can someone help me. whats the issue. yesterday it was working, suddenly started giving error.

**Comment by starand** [comment]
You can create separate ticket.
Which device do you use? Try to download SDK again. Make sure you do not use ABI splits in your build.gradle file.

**Comment by Ashish-Patel** [comment]
my voice instruction is working randomly. sometimes it works, sometimes don't
m_navigationManager = NavigationManager.getInstance();

                            final VoiceCatalog voiceCatalog = VoiceCatalog.getInstance();
                            voiceCatalog.downloadCatalog(new VoiceCatalog.OnDownloadDoneListener() {

                                @Override
                                public void onDownloadDone(VoiceCatalog.Error error) {
                                    if (error == VoiceCatalog.Error.NONE) {
                                        // Get the list of voice packages from the voice catalog list
                                        List<VoicePackage> voicePackages = voiceCatalog.getCatalogList();
                                        // select
                                        for (VoicePackage vPackage : voicePackages) {
                                            if (vPackage.getMarcCode().compareToIgnoreCase("eng") == 0) {
                                                if (vPackage.isTts()) {
                                                    vid = vPackage.getId();
                                                        voiceCatalog.downloadVoice(vid, new VoiceCatalog.OnDownloadDoneListener() {
                                                            @Override
                                                            public void onDownloadDone(VoiceCatalog.Error error) {
                                                                if (error == VoiceCatalog.Error.NONE) {
                                                                    // set the voice skin for use by navigation manager
//                                                                    m_navigationManager.setVoiceSkin(voiceCatalog.getLocalVoiceSkin(vid));
                                                                    VoiceGuidanceOptions voiceGuidanceOptions =
                                                                            m_navigationManager.getVoiceGuidanceOptions();
                                                                    voiceGuidanceOptions.setVoiceSkin(voiceCatalog.getLocalVoiceSkin(vid));
                                                                }
                                                            }
                                                        });
                                                        break;
                                                }
                                            }
                                        }
                                    }
                                }
                            });
can someone figure out. i'm using downloading English voice skin using this method below method.
 if (vPackage.getMarcCode().compareToIgnoreCase("eng") == 0)

**Comment by stillie** [comment]
@Ashish-Patel This is how i have downloaded the Voice for english male voice

`        VoiceCatalog.getInstance().downloadCatalog(new VoiceCatalog.OnDownloadDoneListener() {
            @Override
            public void onDownloadDone(VoiceCatalog.Error error) {
                if (error == VoiceCatalog.Error.NONE) {
                    VoiceCatalog catalog = VoiceCatalog.getInstance();
                    List<VoicePackage> availableLanguages = catalog.getCatalogList();
                    for (VoicePackage voicePackage : availableLanguages) {
                        if (voicePackage.isTts() && voicePackage.getMarcCode().compareToIgnoreCase("eng") == 0) {
                            downloadVoice(1101); // This is a random ID that HERE Maps support gave me to get the male voice
                            break;
                        }

                    }
                }
            }
        });`

The downloadVoice method:

`    /**
     * Download voice by ID
     *
     * @param skin_id ID of voice for download
     */
    private void downloadVoice(final long skin_id) {
        VoiceCatalog.getInstance().downloadVoice(skin_id, new VoiceCatalog.OnDownloadDoneListener() {
            @Override
            public void onDownloadDone(VoiceCatalog.Error error) {
                if (error == VoiceCatalog.Error.NONE) {
                    NavigationManager.getInstance().setVoiceSkin(VoiceCatalog.getInstance().getLocalVoiceSkin(skin_id));
                }
            }
        });
    }`

**Comment by Ashish-Patel** [comment]
where should i write this code, after map initialization or inside oncreate() method. because every time its downloading and initializing whenever i am coming to navigation activity, so its taking time to download and starting synthesizing after sometime.

**Comment by stillie** [comment]
After the maps have been initialized. If its before the init, then NavigationManager.getInstance() will be null

**Comment by starand** [comment]
And this is expected behavior as all native libs are loaded into memory during SDK initialization.

**Comment by JustTrust** [comment]
> @Ashish-Patel This is how i have downloaded the Voice for english male voice
> downloadVoice(1101); // The app required a male voice for what ever reason, this was the only way i was able to get it by >using this ID. HERE Maps support gave me this ID during the support. 

 There is no sense start a loop if you just download voice with hardcoded id. And they gave you id of non tts voice. This is prerecorded voice without street names.
I also faced with this problem and seems it still not solved. There is no tts male voice in the voice package.

**Comment by zenyagami** [comment]
v3 is deprecated for HERE SDK for Android (Navigate Edition) 4.x how I can get the voice working on 4.x also the images and so on?
