### ISSUE TITLE
MapViewLite goes to black after resuming from another map activity

### ISSUE THREAD

**Issue by shamilds** [heremaps/here-android-sdk-examples#368]
I have MainActivity with MapViewLite view, everything works as expected. If I move to a different activity which as another MapViewLite view, second activity displays map fine. But coming back to MainActivity, MapViewLite view turns black. I can reproduce this issue with sdk sample. I am testing on Samsung Note5 and Samsung S10, both has the same issue. No exceptions on logcat either. 

This happens only after displaying second MapViewLite view. Tried few things and went through sdk documentation, could not find anything related to this. Is there anything additional I have to do before or after displaying second MapViewLite?

sdk version : heresdk-lite-android-4.3.2.0.1948.aar
sample app : https://github.com/shamilds/here-sample

Any help would appreciate.

**Comment by NazarKacharaba** [comment]
Hi @shamilds 
This repo contains examples of SDK 3.x.
You should create issue in SDK 4.x repo - https://github.com/heremaps/here-sdk-examples

**Comment by shamilds** [comment]
@NazarKacharaba Noted. Thank you for pointing it out. I will raise this issue on sdk 4.x repository.
