### ISSUE TITLE
Get unknown error while initializing map engine

### ISSUE THREAD

**Issue by jordenchang55** [heremaps/here-android-sdk-examples#37]
Recently, I developed map feature with your android premium SDK, and things were going well. But somedays ago, it threw Native engine initialization failed for unknown reason while the MapEngine was initializing. And it cannot initial anymore.
To check what's going wrong, I also download your example project and run it, but the error is still there. I cannot find solution from stackoverflow, so I hope you can help me to solve this.

My test phone is Redmi Note 4 with Android 6.0 and Nextbit Robin with Android 7.0, both device get same exception.
here's initializing code from turn-by-turn navigation sample project:

```
private void initMapFragment() {
        m_mapFragment = (MapFragment) m_activity.getFragmentManager()
                .findFragmentById(R.id.mapfragment);

        if (m_mapFragment != null) {
            m_mapFragment.init(new OnEngineInitListener() {
                @Override
                public void onEngineInitializationCompleted(OnEngineInitListener.Error error) {

                    if (error == Error.NONE) {
                        m_map = m_mapFragment.getMap();
                        m_map.setCenter(new GeoCoordinate(49.259149, -123.008555),
                                Map.Animation.LINEAR);
                        m_map.setZoomLevel(13.2);

                        m_navigationManager = NavigationManager.getInstance();
                    } else {
                        Toast.makeText(m_activity,
                                "ERROR: Cannot initialize Map with error " + error,
                                Toast.LENGTH_LONG).show();
                        Log.e("MapFragmentView", error.getDetails(), error.getThrowable());
                    }
                }
            });
        }

    }
```

and here's my log:
```
05-18 11:39:44.275 12031-12031/com.here.android.example.guidance E/MapFragmentView: Native engine initialization failed for unknown reason.
                                                                                    java.lang.Throwable
                                                                                        at com.nokia.maps.av.a(EngineError.java:27)
                                                                                        at com.nokia.maps.MapsEngine$j.a(MapsEngine.java:764)
                                                                                        at com.nokia.maps.MapsEngine$j.a(MapsEngine.java:650)
                                                                                        at com.nokia.maps.MapsEngine$j.doInBackground(MapsEngine.java:634)
                                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                        at java.lang.Thread.run(Thread.java:761)
```

**Comment by andrewcarter** [comment]
There are a couple of things you can try to address this issue:

1. Uninstall all of the apps you currently have installed which use the HERE SDK. Delete the shared map disk cache folder. It is located at `getExternalStorageDirectory()/.here-maps`, so for most devices the `adb` command to delete is: `adb shell rm -r /sdcard/.here-maps`

2. In your app specify an isolated disk cache location and `MapService` component as described here: [Using an Isolated Map Disk Cache with the Map Service](https://developer.here.com/mobile-sdks/documentation/android-premium/topics/map-service.html#map-service__map-service-isolated-cache)

If either of these suggestions works it would be greatly appreciated if you let us know!

**Comment by jordenchang55** [comment]
I tried both solution, and the second one is work.
Thanks for your answer.

**Comment by nishantt12** [comment]
I am getting the same error tried both the solutions but not working.

here is the logcat:

06-07 15:21:52.138 23216 23216 E milezero_response: Map initialization error UNKNOWN  details: Native engine initialization failed for unknown reason.  stacktrace: java.lang.Throwable
06-07 15:21:52.138 23216 23216 E milezero_response: 	at com.nokia.maps.aw.a(EngineError.java:27)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at com.nokia.maps.MapsEngine$h.a(MapsEngine.java:857)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at com.nokia.maps.MapsEngine$h.a(MapsEngine.java:733)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at com.nokia.maps.MapsEngine$h.doInBackground(MapsEngine.java:717)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-07 15:21:52.138 23216 23216 E milezero_response: 	at java.lang.Thread.run(Thread.java:761)
06-07 15:21:52.176 23216 23521 W cr_CrashFileManager:
