### ISSUE TITLE
Route pois

### ISSUE THREAD

**Issue by volkovskiyda** [heremaps/here-android-sdk-examples#372]
Does here sdk for android support getting updates about the upcoming pois on the route? I mean after successful route calculation, I want to get updates about how far away are some pois (petrol-station, restaurant, favorites etc), do they lay on the route (or on another side of the road and we can not reach them).

**Comment by NazarKacharaba** [comment]
Hi @volkovskiyda 
Unfortunately there is no this exact functionality in the SDK.

But you can try to search needed placed along the route using route geometry, then add those places to the route plan as `RouteWaypoint.VIA_WAYPOINT` and recalculate route. Then you will be able to use Navigation API for those places(like distance updates, side of the road etc.)
