### ISSUE TITLE
 ETA is not accurate in Truck Maps.

### ISSUE THREAD

**Issue by mansi-techindustan** [heremaps/here-android-sdk-examples#377]
Hi,
After using the Routing options for truck routes , and changing the weight limit we are not getting the accurate ETA.
Example : if we are making the routes from 'SACRAMENTO' to 'RENO' with change in Weight-limit  so while increasing the weight limit major differences in ETA is shown which is not accurate.

**Comment by NazarKacharaba** [comment]
Hi @mansi-techindustan 
What ETA value do you expect to see? When you change the truck's weight, ETA should be increased?

**Comment by mansi-techindustan** [comment]
@NazarKacharaba  when i am using Weight-limit below  than or equals to   '7.2574779'  while making the routes from 'SACRAMENTO' to 'RENO' it is showing '2 hours 45 mins' and as I am increasing Weight-limit to   '7.7110703'  or above then it is showing '3 hour 11 min'. Though i have checked my calculations as well.

**Comment by NazarKacharaba** [comment]
It is expected behaviour that you see bigger ETA value for trucks to have bigger weight. SDK uses different speed profiles for light, medium, and heavy trucks. Use `SpeedProfile.FAST` to avoid this overestimation.

**Comment by mansi-techindustan** [comment]
Thanku @NazarKacharaba
