### ISSUE TITLE
Marker Clustering

### ISSUE THREAD

**Issue by edurocks** [heremaps/here-android-sdk-examples#378]
Good Afternoon,
I am trying to implement the cluster on markers following the here site tutorial on android but it doesn´t work. I follow step by step and the markers are added to the list but it doesn´t render on the screen and no error is show on the logcat. Why is this happening? Thanks.

**Comment by NazarKacharaba** [comment]
Did you use this tutorial - https://developer.here.com/documentation/android-premium/3.15/dev_guide/topics/marker-clustering.html ?

**Comment by edurocks** [comment]
Yes @NazarKacharaba . Exactly this. Really don´t know what is going on. Seems very strange.

**Comment by SiriUS2551AK** [comment]
Hi @edurocks,

I have checked it with this instruction https://developer.here.com/documentation/android-premium/3.15/dev_guide/topics/marker-clustering.html and it works fine. I have used this sample  https://github.com/heremaps/here-android-sdk-examples/tree/master/map-objects as a skeleton.

Can you please provide the sample code that can help to reproduce this issue?

**Comment by edurocks** [comment]
No. I am not using any map scheme? Do I have to use some of them? I have the insertion of multiples markers at once inside a async task e it doesn´t show the clusters but if I zoom in it shows the markers on the map but not the cluster.
