### ISSUE TITLE
Starter/Premium getZoom/setZoom equivalent in Lite/Explore

### ISSUE THREAD

**Issue by axionnneeeel** [heremaps/here-android-sdk-examples#385]
Hello,

I can't find the equivalent method for getZoom and setZoom(Starter/Premium) in Lite/Explore edition.

Can please someone help me with that ?

**Comment by NazarKacharaba** [comment]
Hi @axionnneeeel 
This repo contains examples of SDK 3.x.
You should create issue in SDK 4.x repo - https://github.com/heremaps/here-sdk-examples
