### ISSUE TITLE
PositioningManager not work on android 9

### ISSUE THREAD

**Issue by yusufsafrudin** [heremaps/here-android-sdk-examples#392]
I have an Android app using the HERE Premium SDK. my app can't detect current location
mPositioningManager?.start(PositioningManager.LocationMethod.GPS_NETWORK_INDOOR)!! always return false
how to fix this issue

my code:

mPositioningManager = PositioningManager.getInstance()
mPositioningManager?.addListener(WeakReference(positionListener))
mPositioningManager?.lastKnownPosition

if (mPositioningManager?.start(PositioningManager.LocationMethod.GPS_NETWORK_INDOOR)!!) {
            val image = Image()
            try {
                image.setImageResource(R.drawable.pin_black2)
            } catch (e: IOException) {
                e.printStackTrace()
            }
            mapFragment!!.positionIndicator.marker=image
            mapFragment!!.positionIndicator.isVisible = true
            mapFragment!!.positionIndicator.isAccuracyIndicatorVisible = true
            mapFragment!!.positionIndicator.accuracyIndicatorColor = R.color.colorPrimaryDark
        } else {
            Toast.makeText(
                this@MainActivity,
                "Can't get your location",
                Toast.LENGTH_LONG
            ).show()
            //finish()
        }

**Comment by Merlin1stHere** [comment]
Has your application been granted ACCESS_FINE_LOCATION permission?

**Comment by yusufsafrudin** [comment]
Thank you, it's worked
