### ISSUE TITLE
Calculate TTA with specified user's speed limit

### ISSUE THREAD

**Issue by volkovskiyda** [heremaps/here-android-sdk-examples#395]
After route calculation, we have RouteTta (including\excluding traffic, using downloaded traffic).  But this TTA does not consider user's speed limit. How can we calculate TTA with the user's specified speed limit?
The route has also route elements, which contains info about default \ static speed. Do we need to manually calculate tta using this info?

**Comment by NazarKacharaba** [comment]
Hi @volkovskiyda 
What do you mean by `user's specified speed limit`? What API do you use to specify this `speed limit`?
it would also help if you provide piece of code to reproduce your issue.

**Comment by Merlin1stHere** [comment]
@volkovskiyda Unfortunately, there is no such feature in the SDK.
