### ISSUE TITLE
What is the best way for back press handling and device orientation changes?

### ISSUE THREAD

**Issue by SergiiM** [heremaps/here-android-sdk-examples#397]
Good day! I'm using HERE Android SDK Premium Edition v.3.14 for my app.
I've left a question in [stackoverflow](https://stackoverflow.com/questions/63793659/heremap-androidxmapfragment-back-press-handling) corresponding to back press handling. 
And I come to conclusion, that for fragment-based app developer should handle back press manually, am I right?
And what about handling of device orientation changes? Do you have any recommendations or samples?
Thanks for answering!

**Comment by Merlin1stHere** [comment]
@SergiiM As I can see you have an answer to your SO question. 
HERE SDK views and fragments do not require special handling for device rotation.

**Comment by SergiiM** [comment]
@Merlin1stHere hi and thank you for answer. Actually on SO I've answered to my question by myself, so I would like to check is it correct answer and best practice?
Corresponding to device rotation: only thing I would like to note, that developer should add 
`android:configChanges="orientation|keyboardHidden|screenSize"` to app manifest and HERE SDK will handle rotation.

**Comment by Merlin1stHere** [comment]
@SergiiM The android: configChanges = "Orientation" parameter just prevents the activity from being recreated during rotation. It is not necessary for the HERE maps. You can save the Map object somewhere and initialize the map view with it after recreation of the activity.

**Comment by SergiiM** [comment]
@Merlin1stHere thanks for specification, it's not obvious, that developer can save Map object somewhere not in Activity context. And what about best practices for back handling, when working with maps in fragment-based architecture.

**Comment by Merlin1stHere** [comment]
@SergiiM This follows from the [https://developer.android.com/guide/components/activities/activity-lifecycle](Android Activity Lifecycle).
By default Android keeps fragments in memory even if the Activity is deleted during rotation. This way you can store your own configurations and objects in a fragment. But this behaviour is not guaranteed. In situations of lack of resources, the android can delete a fragment.

**Comment by SergiiM** [comment]
@Merlin1stHere well, it's not obvious at all after your answer. How I as a developer can know, that lib's Map object is not context-dependant? And what if developer uses setRetainInstance(true) for fragment with you map object?  And finally could you, please, give recommendations about back press handling? This is the third time I'm asking about it. Thank you.

**Comment by starand** [comment]
The question is related more to Android Fragments. Consider AndroidXMapFragment fragment **as usual Android fragment** and follow general Android documentation. There is nothing specific with regards to mSDK.

**Comment by SergiiM** [comment]
@starand thanks for answering
