### ISSUE TITLE
Remove Numbers on Map

### ISSUE THREAD

**Issue by edurocks** [heremaps/here-android-sdk-examples#401]
Good Afternoon,
When I initialize the map and zoom in a certain level it begins to appears some numbers on the map. Is there a way to remove it? And how can I remove the white arrow on navigation manager? Thanks.

**Comment by NazarKacharaba** [comment]
Hi @edurocks 
Could you make screenshot  and highlight those numbers?

**Comment by edurocks** [comment]
Yes. Of course. 
![Screenshot_20200928-104558_FuelSave](https://user-images.githubusercontent.com/22355468/94417513-141bc680-0178-11eb-901f-36449d5d0dc4.jpg). Those numbers that appears is it possible to remove it?

**Comment by NazarKacharaba** [comment]
Use following API to disable numbers.
Map.setVisibleLayers(EnumSet.of(Map.LayerCategory.POINT_ADDRESS), false);

**Comment by edurocks** [comment]
Thanks @NazarKacharaba . It works perfectly. I will close this issue but I have a final question. Whem I am using the navigation manager I see those white arrows on in and is there a way to remove it or it is part of the navigation itself and can´t be removed? Thanks.

**Comment by NazarKacharaba** [comment]
This particular setting is unavailable in the SDK.

**Comment by edurocks** [comment]
Thanks. I will close the issue
