### ISSUE TITLE
Is there any way to get place details after finishing navigation?

### ISSUE THREAD

**Issue by SergiiM** [heremaps/here-android-sdk-examples#403]
Hi, I'm using HERE Android SDK Premium Edition v.3.14
And I've implemented navigation mode. I would like to show finish point details like in google maps, when navigation is ended. Is it possible to get detail data in onEnded callback method of NavigationManagerEventListener? Or I should fetch details data on a step of place selection? Thank You!

**Comment by NazarKacharaba** [comment]
You can use [ExploreRequest](https://www.developer.here.com/documentation/android-premium/3.16/api_reference_java/com/here/android/mpa/search/class-use/ExploreRequest.html) to fetch place info for needed geo location.

**Comment by SergiiM** [comment]
Hi @NazarKacharaba, thank you for your answer. Could you, please, clarify a little: as I understood ExploreRequest returns me DiscoveryResultPage with List<DiscoveryResult> and I should find result with the same geo location as the last waypoint in the route? Is there a situation, when 2 stores in one building with the same geo location?

**Comment by NazarKacharaba** [comment]
Hi @SergiiM 
Have a look at this example - https://github.com/heremaps/here-android-sdk-examples/blob/7bc08e1e0a60b49bebf196a9d3961fe4d362a474/search/app/src/main/java/com/here/android/example/search/MapFragmentView.java

Yes, it is possible to have two places on the same geo location.

**Comment by SergiiM** [comment]
Hi @NazarKacharaba, thank you for your answer. I've solved the problem via keeping link to PlaceRequest from getDetailsRequest method. Anyway, I'm appreciate for your comments. Issue can be closed.
