### ISSUE TITLE
Searching city-town-village in offline - able to find village and town but not city

### ISSUE THREAD

**Issue by VladChernetsky** [heremaps/here-android-sdk-examples#404]
SDK: Android Premium 3.16

Downloaded offline maps: Ukraine/Kyiv Oblast, Ukraine/Zhytomyr Oblast.
GeocodeRequest is used for searching. 
The goal - search cities.

When I search for a village or a town - there are PlacesGeocodeResults with PlacesLocation objects. PlacesLocation has boundingBox data.
Examples: Чуднів, Буча, Ірпінь.

But when I try to search some cities there is no result with boundingBox.
Examples: Київ, Житомир.

Is this possible to search for a city with boundingBox in offline mode? Or it is a bug that I cannot find Kyiv and Zhytomyr as a city but only addresses in these cities?

**Comment by DmytroLytvynovskyi** [comment]
Hi, @VladChernetsky 
When you try to find some city like "Житомир" you don't get results, or you get irrelevant results like some streets placed in Zhytomyr?
Have you tried to search for "Житомир, Україна"?
Can you provide a snippet of code in which you use a search?
