### ISSUE TITLE
What impact on route calculation has RouteOptions.setTime?

### ISSUE THREAD

**Issue by JustTrust** [heremaps/here-android-sdk-examples#405]
When using Android Premiun SDK there is an option to set time for route calculation. In [documentation](https://developer.here.com/documentation/android-premium/3.16/api_reference_java/index.html?com%2Fhere%2Fandroid%2Fmpa%2Frouting%2FRouteOptions.html) no any description for this setter, simply have been said that  **Sets the arrival or departure time**. How this time impact on a returned route? Its possible to realize that time was changed. Is ETA or TTA changed because of this? Its hard to find another documentation that relatad to this. If it exist please give me a link. Thanks in advance.

**Comment by NazarKacharaba** [comment]
Hi @JustTrust 
Setting arrival/departure time can affect:
1. TTA/ETA for public transport;
2. Some roads can be travelled only within defined time frames for certain transport types, so final route will be different.
3. School zone in some countries have speed limitation for certain time frames, TTA/ETA will be different.

**Comment by JustTrust** [comment]
Thanks for the answer!
