### ISSUE TITLE
Download voice:  Access to this operation is denied. Contact your HERE representative for more information.

### ISSUE THREAD

**Issue by hmtriit** [heremaps/here-android-sdk-examples#419]
I'm using the Premium SDK downloaded using application Freemium.
When I'm trying to access downloaded Voice, I get the following error message
java.security.AccessControlException: Access to this operation is denied. Contact your HERE representative for more information.

- I searched everywhere but I couldn't find a solution to that. Anyone around here, could you please assist me?
- Here SDK version 3.16 and 3.17
- This is affects turn by turn navigation

Thanks

**Comment by NazarKacharaba** [comment]
Hi @hmtriit 
What API do you use to access _downloaded voice_? Could you attach stack-trace?

**Comment by Huynhtri027** [comment]
Thank @NazarKacharaba support
I work in a licensed commercial. Currently, I have updated the license, and API download Voice works well.

I'll close the issue.
Thanks,

**Comment by hmtriit** [comment]
Thank @NazarKacharaba support
I work in a licensed commercial. Currently, I have updated the license, and API download Voice works well.

I'll me close the issue.
Thanks
