### ISSUE TITLE
QUESTION: Route color to match traffic color

### ISSUE THREAD

**Issue by ne2rnas** [heremaps/here-android-sdk-examples#420]
Hello! I'm using Android Premium SDK. I want to change the color of the route to match the color of the traffic. 

For example, in the screenshot below, the traffic in yellow is being drawn within the route but there are portions of the route visible in blue color. 

Can I make the blue portion of the route completely yellow? Is this kind of customization available in the SDK or should I draw custom Polylines for my use case?

Thanks.

![image](https://user-images.githubusercontent.com/7700271/101181141-35f06880-3655-11eb-84b6-5d90e6a30598.png)

**Comment by prostolyalya** [comment]
Hi @ne2rnas
SDK don't have API for change part of route.

**Comment by ne2rnas** [comment]
Ok, thanks. You may close this issue.
