### ISSUE TITLE
Incorrect license key

### ISSUE THREAD

**Issue by kastyk35** [heremaps/here-android-sdk-examples#428]
Hello!

I have used your examples from https://github.com/heremaps/here-android-sdk-examples/tree/master/map-rendering to build an application in Android Studio. Everything went fine until I was going to try it on the emulator device. After granting permissions, I got only a message:

"Map engine initialization
Error: INCORRECT_LICENSE_KEY"

I was trying endless times to paste my key into AndroidManifest.xml file - nothing.
I was changed my app name in my profile, to get new license key, of course all paths and files in my project have been updated with a correct data - still nothing.

I built a .app package and installed directly on my phone - that same, incorrect key.

I have no clue, how can I fix that. Again, I checked multiple times all credentials - all of them are properly placed in the manifest.

I'll be happy with any help.

**Screenshots**
![image](https://user-images.githubusercontent.com/78548376/106942835-edbcf780-6724-11eb-81d6-93f8e195f421.png)

**Comment by NazarKacharaba** [comment]
Hi @kastyk35 
Make sure your application package name is the same in all these places: _build.gradle_, _AndroidManifest.xml_ and also on https://developer.here.com. If you still get an error, contact HERE support support@here.com and share your APK file.
