### ISSUE TITLE
Here SDK start navigation position issue

### ISSUE THREAD

**Issue by Abhish-ek91** [heremaps/here-android-sdk-examples#429]
I am using HERE maps premium edition for my android app. Everything is working fine, I can show the map, show my current location, add markers on coordinates, draw a route between current location and destination location. When I tap on start navigation a dialog appears showing to select navigation or simulation. If I select simulation the camera moves to navigation mode(fixed on to the position of PositioIindicator) and starts moving on the drawn path. 

But if I select navigation option from the dialog the camera supposed to move to the navigation mode(fixed on to the position of PositioIindicator showing the direction arrow towards front) immediately but it is not moving to that position and map is staying idle. App is getting fixed on to the current location position only after the NavigationManager.PositionListener's onPositionUpdated method starts providing GeoPosition which is happening after a couple of seconds. It's kind of difficult for me explain what problem I am facing but I think others must have faced this same problem.

**my code**

private void startNavigation() {
        m_naviControlButton.setText(R.string.stop_navi);
        m_navigationManager.setMap(m_map);
        m_mapFragment.getPositionIndicator().setVisible(true);

        AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(m_activity);
        alertDialogBuilder.setTitle("Navigation");
        alertDialogBuilder.setMessage("Choose Mode");
        alertDialogBuilder.setNegativeButton("Navigation",new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialoginterface, int i) {
                m_navigationManager.startNavigation(m_route);
                m_map.setTilt(60);
                startForegroundService();
              
            };
        });

        alertDialogBuilder.setPositiveButton("Simulation",new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialoginterface, int i) {
                m_navigationManager.simulate(m_route,60);//Simualtion speed is set to 60 m/s
                m_map.setTilt(60);
                startForegroundService();
            };
        });

        AlertDialog alertDialog = alertDialogBuilder.create();
        alertDialog.show();
        m_navigationManager.setMapUpdateMode(NavigationManager.MapUpdateMode.ROADVIEW);

        addNavigationListeners();
    }

private void addNavigationListeners() {
        m_navigationManager.addNavigationManagerEventListener(new WeakReference<>(m_navigationManagerEventListener));
        m_navigationManager.addPositionListener(new WeakReference<>(m_positionListener));
    }

private final NavigationManager.PositionListener m_positionListener = new NavigationManager.PositionListener() {
        @Override
        public void onPositionUpdated(GeoPosition geoPosition) {
            _wayLatitude = geoPosition.getCoordinate().getLatitude();
            _wayLongitude = geoPosition.getCoordinate().getLongitude();

            Toast.makeText(m_activity, "data is here" + _wayLatitude, Toast.LENGTH_SHORT).show();
        }
    };

**Comment by NazarKacharaba** [comment]
Hi @Abhish-ek91 
Could you attach video of phone screen with the problem you mentioned, please? In that case we will better understand the problem.

**Comment by Abhish-ek91** [comment]
Can you please share your email id or something to send the video. The video file size is more than 10MB so I can't attach it here.

**Comment by NazarKacharaba** [comment]
Could you upload using Google Drive, Dropbox or OneDrive and make public link to it?

**Comment by Abhish-ek91** [comment]
Here is the link. Please watch till the end.
https://drive.google.com/file/d/1VO8AaBiqEWlnMr8Z9I_kAaDkAckIyJQT/view?usp=sharing

**Comment by prostolyalya** [comment]
Hello @Abhish-ek91,
Position updates after a couple of seconds because `PositioningManager` automatically chooses `LocationMethod.GPS_NETWORK`. This method is effective at open space, where the gps-signal is stable. In buildings, for example, gps-signal isn't stable.
For your case, you can start `PositioningManager` on the start app, added in code:
```
private void initMapFragment() {
. . .
m_navigationManager = NavigationManager.getInstance();
**PositioningManager.getInstance().start(PositioningManager.LocationMethod);**
```
Or, you can start `PositioningManager` with another `LocationMethod`, for example, `NETWORK`. This method using a wireless network, which more effective in buildings:
```
PositioningManager.getInstance().start(PositioningManager.LocationMethod.NETWORK);
```
For more information about `PositioningManager` and `LocationMethod` please read [this](https://developer.here.com/documentation/android-starter/3.15/api_reference_java/com/here/android/mpa/common/PositioningManager.html) and [this](https://developer.here.com/documentation/android-starter/3.15/api_reference_java/com/here/android/mpa/common/PositioningManager.LocationMethod.html).

**Comment by Abhish-ek91** [comment]
I have tried
`PositioningManager.getInstance().start(PositioningManager.LocationMethod.NETWORK);`

It's also taking time to update position. But what about

`PositioningManager.getInstance().start(PositioningManager.LocationMethod.NONE);` 

And

`PositioningManager.getInstance().start(PositioningManager.LocationMethod.GPS_NETWORK_INDOOR);`

Can I use any of them by default. Because with comparison to  LocationMethod.NETWORK,  LocationMethod.NONE and LocationMethod.GPS_NETWORK_INDOOR are updating the position faster.

**Comment by prostolyalya** [comment]
Hello @Abhish-ek91,
From [documentation](https://developer.here.com/documentation/android-premium/3.17/api_reference_java/com/here/android/mpa/common/PositioningManager.LocationMethod.html):
```
NONE: Device positioning is not active.
GPS_NETWORK_INDOOR: Positioning is provided using GPS, or Wi-Fi or Bluetooth LE network. Returned positions may contain building and floor information.
```
By default is better to use `GPS_NETWORK` or `GPS_NETWORK_INDOOR`.

**Comment by Abhish-ek91** [comment]
I am using GPS_NETWORK_INDOOR for now. Thank you for your help.
