### ISSUE TITLE
RoutingEngine not located in HERE-sdk.aar

### ISSUE THREAD

**Issue by Tecmek** [heremaps/here-android-sdk-examples#441]
I'm trying to get a route, I'm using this file: https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/explore/android/Routing/app/src/main/java/com/here/routing/RoutingExample.java the RoutingEngine class is not being imported. I checked the .aar but it was not located in there either. I even re-downloaded the SDK, thinking that would resolve the issue. It did not. Is there any way around this? HERE SDK FOR ANDROID (PREMIUM EDITION)
 SDK version 3.18.3 is what I'm using. I've looked on SO and Google, as well as the HERE website.

**Comment by NazarKacharaba** [comment]
SDK 3.X does not have RoutingEngine API. Mentioned _RoutingExample_ is for SDK 4.X
