### ISSUE TITLE
Navigating on pre generated route in Premium Edition

### ISSUE THREAD

**Issue by BenasBruzauskas** [heremaps/here-android-sdk-examples#444]
Hello,
We are using your services in our business where we plan the route from the desktop computer and send it to the driver's phone to driver exactly as planned, lets call it "Stick to Route" functionality. It is very important that the driver would follow the exact same route that we created in desktop computer (Also Here SDK).
Unfotunatelly, we face two main problems:
1. We cannot ensure, that the route generated in our desktop aplication would be the same in the phone navigation. How can we ensure this?.
2. Do you have the possibility to check/inform/re-route to the initial route when the driver deviates? We need to ensure, that driver would be re-routed to the initial route as effectivelly as possible.
Currently we are using Here Navigation Premium Edition for Android phones.
Version 3.18 (edited)

**Comment by juka-lp** [comment]
I would also like to know, I'm facing the same problem

**Comment by BenasBruzauskas** [comment]
@juka-lp 
Premium version does not support these kind of functions and it is impossible to do it.
