### ISSUE TITLE
Here sdk showing Android evaluation package expires on xxxx/xx/xx

### ISSUE THREAD

**Issue by debamd** [heremaps/here-android-sdk-examples#445]
After initialized the here map on any android device on the map UI showing **HERE SDK Android Evaluation Package expires on xxxx/xx/xx**

I don't want to show this message to the user.

![device_map](https://user-images.githubusercontent.com/85278534/120605027-384c4780-c46b-11eb-86d9-095999338dcc.png)

 - Device: [All Device]
 - OS: [All]
 - SDK Version: [e.g. 3.18.3]

**Comment by NazarKacharaba** [comment]
HI @debamd 
You have to update your credentials(license key, app code and app id). Please contact support@here.com for the help.
