### ISSUE TITLE
How can I create a Polygon with a hole inside in Here SDK?

### ISSUE THREAD

**Issue by lucifer222** [heremaps/here-android-sdk-examples#446]
Hi @NazarKacharaba .

![image](https://user-images.githubusercontent.com/12459096/122153570-dc83b480-ce95-11eb-884c-5a8363f6b4a3.png)

We have a requirement to create a polygon with a hole inside. 
But it seems has no directly method to draw a hole inside. 
So we create two GeoPolygon, left GeoPolygon and right GeoPolygon. 
the detail method is :

      public static List<GeoCoordinate> createLeftHoleForHere(GeoCoordinate center, double drivingRange) {
        double longitude = center.getLongitude();
        double minLongitude;
        if (longitude < 0) {
            minLongitude = longitude + 180;
        } else {
            minLongitude = longitude - 180;
        }
        double leftMidLongitude = longitude - 90;
        if (longitude < -90) {
            leftMidLongitude = longitude + 270;
        }
        List<GeoCoordinate> leftCircle = createHalfHoleForHere(center, drivingRange, true);
        GeoCoordinate lastLeftCircle = leftCircle.get(leftCircle.size() - 1);
        List<GeoCoordinate> holeList = new ArrayList<>();
        holeList.add(lastLeftCircle);
        holeList.add(new GeoCoordinate(90, lastLeftCircle.getLongitude()));
        holeList.add(new GeoCoordinate(90, leftMidLongitude));
        holeList.add(new GeoCoordinate(90, minLongitude));
        holeList.add(new GeoCoordinate(0, minLongitude));
        holeList.add(new GeoCoordinate(-90, minLongitude));
        holeList.add(new GeoCoordinate(-90, leftMidLongitude));
        holeList.add(new GeoCoordinate(-90, lastLeftCircle.getLongitude()));
        holeList.addAll(leftCircle);
        return holeList;
    }

    private static List<GeoCoordinate> createHalfHoleForHere(GeoCoordinate centerGeo, double drivingRange, boolean isLeftCircle) {
        int degreesBetweenPoints = 2; //180 sides
        double distRadians = drivingRange / RADIUS_OF_EARTH_METERS;
        double centerLatRadians = centerGeo.getLatitude() * Math.PI / 180;
        double centerLonRadians = centerGeo.getLongitude() * Math.PI / 180;
        int startAngle, endAngle;
        if (isLeftCircle) {
            startAngle = 180;
            endAngle = 360;
        } else {
            startAngle = 0;
            endAngle = 180;
        }
        List<GeoCoordinate> geoCoordinateList = new ArrayList<>();
        for (int angle = startAngle; angle <= endAngle; angle = angle + degreesBetweenPoints) {
            double degreeRadians = angle * Math.PI / 180;
            double pointLatRadians = Math.asin(Math.sin(centerLatRadians) * Math.cos(distRadians) + Math.cos(centerLatRadians) * Math.sin(distRadians) * Math.cos(degreeRadians));
            double pointLonRadians = centerLonRadians + Math.atan2(Math.sin(degreeRadians) * Math.sin(distRadians) * Math.cos(centerLatRadians),
                    Math.cos(distRadians) - Math.sin(centerLatRadians) * Math.sin(pointLatRadians));
            double pointLat = pointLatRadians * 180 / Math.PI;
            double pointLon = pointLonRadians * 180 / Math.PI;
            geoCoordinateList.add(new GeoCoordinate(pointLat, pointLon));
        }
        return geoCoordinateList;
    }

But when the drivingRange < 1000 meters, the SDK will report an error, and app crash. Can you help to check?

the detail crash is:

    java.lang.IllegalArgumentException: GeoPolygon is not supported.
        at com.nokia.maps.MapPolygonImpl.<init>(MapPolygonImpl.java:772)
        at com.here.android.mpa.mapping.MapPolygon.<init>(MapPolygon.java:2)

**Comment by lucifer222** [comment]
@NazarKacharaba  Can you help to check this issue?

**Comment by NazarKacharaba** [comment]
Hi @lucifer222 
I do not think that this case is supported by the SDK 3.X
