### ISSUE TITLE
How to delete on the map the part of the route that was passed by the driver

### ISSUE THREAD

**Issue by Strikelon** [heremaps/here-android-sdk-examples#472]
Hello. We use FTCRNavigationManager and FTCRRoute while navigation.

Please advice, are there any ways for removing from map the part of the route that was passed by the driver in real time during driver moving.

Here is the print screen for more notion:
https://pastenow.ru/b72f53d4ac0114dd566f3a4bc812662c

Thank you.

**Comment by NazarKacharaba** [comment]
Hi @Strikelon,
Unfortunately, FTCR navigation does not provide the API to change or remove colour for the travelled part of the route.
