### ISSUE TITLE
Are there any variants to get bearing of the calculated route?

### ISSUE THREAD

**Issue by Strikelon** [heremaps/here-android-sdk-examples#476]
Hi, could you advice please.

For instance I calculated the route with FTCRRouter().calculateRoute(ftcrRoutePlan) and I got the FTCRRoute

Are there any ways to get the bearing from this route, if I want to rotate the map to the direction of the route, without navigation manager tracking.

Thank you!

**Comment by NazarKacharaba** [comment]
Hi @Strikelon 
Bearing is just a degree between **two** locations, and `FTCRRoute` consists of a set of locations (`route.getGeometry()`). So you can not calculate bearing between device location and `FTCRRoute`. You will have to take a certain location on the route and use it as a second value for bearing calculation - `GeoCoordinate.getHeading(GeoCoordinate)`.

**Comment by Strikelon** [comment]
Thanks!
