### ISSUE TITLE
turn by turn navigation missing proper map scheme 

### ISSUE THREAD

**Issue by dayeba** [heremaps/here-android-sdk-examples#49]
I'm trying this turn by turn navigation example https://github.com/heremaps/here-android-sdk-examples/tree/master/turn-by-turn-navigation-android, and I keep getting error toast `Error:route calculation returned error code: ROUTE_CORRUPTED` after looking at the documentation, it was fixed by adding one line `m_map.setMapScheme(Map.Scheme.CARNAV_DAY);` to MapFragmentView https://github.com/heremaps/here-android-sdk-examples/blob/master/turn-by-turn-navigation-android/app/src/main/java/com/here/android/example/guidance/MapFragmentView.java

**Comment by starand** [comment]
@dayeba is this still a case for you? Hope the issue was resolved in last releases.
