### ISSUE TITLE
[ERROR] SearchErrorConvert - Search error: pplx::task_canceled, what: 

### ISSUE THREAD

**Issue by yuvaraj119** [heremaps/here-android-sdk-examples#503]
**Describe the bug**
I am using Heremaps Explorer version 4.13.4.0.11034. On launch of app with search engine everything works good. But when i change the orientation the Search engine stop giving result and throws error in log
Error message : [ SearchErrorConvert  [ERROR] SearchErrorConvert - Search error: pplx::task_canceled, what: ]

**Steps To Reproduce**
1. Run the app with Search engine 
2. Do some address search
3. Now change the device orientation
4. Now again start address search you will wont get the result 
5. Look at the logcat you will see this error
Error message : [ SearchErrorConvert  [ERROR] SearchErrorConvert - Search error: pplx::task_canceled, what: ]

**Expected behavior**
Expected on orientation change the search engine should give address search result.

**Smartphone:**
 - Device: [Samsung Active 2 Tablet]
 - OS: [Android 9]
 - 4.13.4.0.11034

**Comment by NazarKacharaba** [comment]
Hi @yuvaraj119,

Could you create a ticket in SDK 4.X project here - https://github.com/heremaps/here-sdk-examples? This project is related to the old SDK 3.x.
