### ISSUE TITLE
turn by turn position delay

### ISSUE THREAD

**Issue by alexsafe** [heremaps/here-android-sdk-examples#51]
Hi @sschuberth ,

I noticed that there is a delay regarding the position shown on the map during navigation. In the turn-by-turn example versus using the HEREWeGo app, the position in the example is always about 10 m behind. 
Can you please offer some advice for how to correct this?

Thanks,
Alex

**Comment by Xgamefactory** [comment]
such a professional sdk and such an awefull support (

**Comment by sschuberth** [comment]
@JohnLXiang, can you assist here?

**Comment by JohnLXiang** [comment]
Hi @alexsafe, I'm trying to reproduce the issue, if you can provide more details, that'll be very helpful.

-Did you use the simulation mode or the real navigation when you saw such delay in the example app? 
-Which SDK version did you use?

Thanks.

**Comment by starand** [comment]
No response for long time. Closing the issue.
