### ISSUE TITLE
Here maps display blue globe using latest SDK in android studio ,maps not appearing

### ISSUE THREAD

**Issue by ashk1246** [heremaps/here-android-sdk-examples#52]
![screenshot_2017-06-15-02-41-15-090_com here android example routing](https://user-images.githubusercontent.com/10883509/27251999-e5494c1e-5370-11e7-8d5b-dd5e92f63828.png)

I run the sample application provided by Maps, but it just displays a blue globe. The maps are not appearing, and I don't know what mistake I made.

**Comment by ashk1246** [comment]
fixed above by clearing phone memory, actually, the here map is downloading the map files background  ,i don't have memory space in my phone that's the reason it's not showing map.

**Comment by sschuberth** [comment]
Thanks for sharing the resolution!
