### ISSUE TITLE
[init project] Got MISSING_LIBRARIES error

### ISSUE THREAD

**Issue by bng86** [heremaps/here-android-sdk-examples#54]
- step 1.
download HERE-sdk.aar into app/libs folder
- step 2.
setting `build.gradle`
``` gradle
repositories { 
    flatDir {
        dirs 'libs'
    }
}
dependencies {
    compile (name :'here-sdk', ext:'aar')
}
```
- step 3. setting `app id`, `app token`, `license key`
``` xml
<meta-data
    android:name="com.here.android.maps.appid"
    android:value="my app id" />
<meta-data
    android:name="com.here.android.maps.apptoken"
    android:value="my app token" />
<meta-data
    android:name="com.here.android.maps.license.key"
    android:value="my license key" />
```
- step 4. init map fragment
xml
```xml
    <fragment
        android:id="@+id/mapFragment"
        class="com.here.android.mpa.mapping.MapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
```
init map fragment
```java
mapFragment.init(new OnEngineInitListener() {
            @Override
            public void onEngineInitializationCompleted(OnEngineInitListener.Error error) {
                // got error MISSING_LIBRARIES
               //  how do i fix it?
            }
}
```

**Comment by artemnikitin** [comment]
Try this https://stackoverflow.com/questions/39021240/gradle-native-libraries-not-found-on-device-but-present-in-apk/39021670#39021670

**Comment by bng86** [comment]
@artemnikitin thank you.
When I join those code and fix it.
``` gradle
splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a'
            universalApk false
        }
    }
```

**Comment by artemnikitin** [comment]
Great!

**Comment by starand** [comment]
Hi @bng86
That error happens when you use some arm64 native libraries. If there is at least one arm64 lib in your project, the OS creates 64bit address space and tries to load all 64bit libraries. But SDK does not support arm64 (till 3.7 release). 32bit and 64bit libraries cannot be mixed. Therefore please use ABI splits as advised above.
The issue should not happen with HERE SDK 3.7 (should be released soon).
