### ISSUE TITLE
ERROR: Cannot initialize Map with error: UNKNOWN

### ISSUE THREAD

**Issue by zaheerwork** [heremaps/here-android-sdk-examples#64]
I tried everything which suggested but nothing works. Every time its showing same error -ERROR: Cannot initialize Map with error: UNKNOWN..

**Comment by JohnLXiang** [comment]
Hi @zaheerwork , sorry to hear that you got this error. Could you try something to see if they would be helpful?
1. Verify your package name exactly matches the one you registered in developer.here.com
2. Verify the app code,tokemn and license key in your app matches those were assigned by developer.here.com
3.  If the issue still persists , could you try deleting sdcard/.here-maps,  reboot your device and launch the app again?
4. If all these steps don't resolve your issue, could you please paste your map initialization code here, so we can take a look?

**Comment by cosmith** [comment]
I have the same issue:

```
01-10 15:19:48.898 13751-13751/? E/RNHereMapView: UNKNOWN
01-10 15:19:48.898 13751-13751/? E/RNHereMapView: Native engine initialization failed for unknown reason.
01-10 15:19:48.898 13751-13751/? E/RNHereMapView: java.lang.Throwable
                                                      at com.nokia.maps.aw.a(EngineError.java:27)
                                                      at com.nokia.maps.MapsEngine$h.a(MapsEngine.java:857)
                                                      at com.nokia.maps.MapsEngine$h.a(MapsEngine.java:733)
                                                      at com.nokia.maps.MapsEngine$h.doInBackground(MapsEngine.java:717)
                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                      at java.lang.Thread.run(Thread.java:818)
```

My initialization code:
```java

    public RNHereMapView(ThemedReactContext reactContext) {
        super(reactContext);
        this.mContext = reactContext;

        MapEngine mapEngine = MapEngine.getInstance();
        ApplicationContext appContext = new ApplicationContext(mContext.getApplicationContext());
        mapEngine.init(appContext, new OnEngineInitListener() {
            @Override
            public void onEngineInitializationCompleted(Error error) {
                if (error == OnEngineInitListener.Error.NONE) {
                    addMapView();
                } else {
                    Log.e("RNHereMapView", error.name());
                    Log.e("RNHereMapView", error.getDetails());
                    Log.e("RNHereMapView", error.getStackTrace());
                }
            }
        });
    }
```

**Comment by AmbroseLi** [comment]
@cosmith Hi.  Could you please verify your manifest has the right app ID/code and license key entered (i.e., the ones you got from developer.here.com when you registered your app -- if you don't remember them off the top of your head, sign into your developer.here.com account and you can get a list all of them for your registered apps)?  For completeness, the part of the manifest.xml I'm referring to is:

`<meta-data android:name="com.here.android.maps.appid" android:value="{YOUR_APP_ID}"/>`
`<meta-data android:name="com.here.android.maps.apptoken" android:value="{YOUR_APP_CODE}"/>`
`<meta-data android:name="com.here.android.maps.license.key" android:value="{YOUR_LICENSE_KEY}"/>`

Thanks.

**Comment by cosmith** [comment]
Yes I figured this was the issue, my evaluation license had expired, the error could really be more descriptive here... 
Thanks!

**Comment by JH-YVR** [comment]
Thanks for the feedback @cosmith . Agree there is room for improvement in the descriptiveness of the error messages. This is something we will fix in an upcoming release.

**Comment by MohammedFayaj** [comment]
I tried everything which suggested but nothing works. Every time its showing same error -ERROR: Cannot initialize Map with error: UNKNOWN..Can anyone help

**Comment by MohammedFayaj** [comment]
@JH-YVR any please when this issue is getting fixed ?

**Comment by JH-YVR** [comment]
@MohammedFayaj , there are improvements coming in an upcoming release to provide clearer error codes when map initialization fails. In your case, if the information you are using (app id, license key, package name etc.) are all correct and valid, then these changes are likely not going to help. We will need more details to investigate the issue you are facing.

**Comment by starand** [comment]
Hi @MohammedFayaj,
UNKNOWN error is returned for the following reasons:
 - provided AppId/Code/PackageName does not correspond your license key (or they are empty);
 - license key is somehow damaged or empty.

If your license key has expired, USAGE_EXPIRED error should be returned. In case you do not see USAGE_EXPIRED error, please consider first two options.

**Comment by tamhuynhit** [comment]
Please help, I still get this UNKNOWN error while initializing the map:

- I've rechecked my Package name, AppId, AppCode and License Key, copied and pasted them several times.
- I've granted WRITE_STORAGE_PERMISSION and LOCATION permission.
- I activated the 90-day Premium trial just 2 hours ago so I assumed it cannot be expired.
- I've tried removing `/sdcard/.here-maps` method mentioned above using command `adb shell rm -r /sdcard/.here-maps`. It reported that the folder does not exist and the error still the same.

I see this note on my project dashboard:
 
>Please note: This is an evaluation license for testing and non-production use. You will need to use our Customer Integration Testing (CIT) environment. See our documentation for guidance on configuring environments and testing.

But cannot find any document related to this CIT environment configuration. I built my app in Debug mode already.

**Comment by JH-YVR** [comment]
@tamhuynhit , the note regarding CIT environment is only applicable if using HERE REST services. You can ignore the note if you are only using the Mobile SDK. 

We will be releasing an update early in April which will address the issue of the UNKNOWN error not being useful in identifying what has gone wrong. I appreciate this is not of any help for you right now. I will discuss with others to see how we can help unblock you. Please also reply if you find a fix yourself.

**Comment by tamhuynhit** [comment]
Thanks in advance. Error status with clearer information will help. For me now creating another project works.

P/S: Besides, after that, I meet another error with MISSING_LIBRARIES, that link me to a fix that listed in #54 . Many people got this error so it should be mentioned in the document IMO.

**Comment by starand** [comment]
Hi @tamhuynhit 
See my comment there - https://github.com/heremaps/here-android-sdk-examples/issues/54

**Comment by MohammedFayaj** [comment]
@starand thanks issue fixed I was trying to install two apps with Hermaps trail licence

**Comment by Bharathjh614** [comment]
Even I am getting the same Error: cannot initialize map with error INCORRECT_LICENSE_KEY 
I have entered same full package name, appid, apptoken and license key even though i am getting the error should i wait for sometime as they have mentioned it takes time to get appid whitelisted since i am using once i got appid

**Comment by JH-YVR** [comment]
@Bharathjh614 , are you still having the same issue of INCORRECT_LICENSE_KEY?

**Comment by Bharathjh614** [comment]
YES

**Comment by alan-camilo** [comment]
@tamhuynhit I have the exact same problem you described. But I manage to build and run the sample project BasicMapSolution from the sdk. It was a while ago, but how did you resolve the issue ?

**Comment by andritowmega** [comment]
That error comes through the keys.
Incredibly solve it by putting the keys before the activity where I have here

<meta-data android: name = "com.here.android.maps.appid" android: value = "..." />
        
<meta-data android: name = "com.here.android.maps.apptoken" android: value = "..." />
        
<meta-data android: name = "..." />

<activity android: label = "@ string / app_name" android: name = ". HereMaps"> </ activity>

**Comment by andritowmega** [comment]
That error comes through the keys.
Incredibly solve it by putting the keys before the activity where I have here
`<meta-data android: name = "com.here.android.maps.appid" android: value = "..." />
<meta-data android: name = "com.here.android.maps.apptoken" android: value = "..." />
<meta-data android: name = "..." />
<activity android: label = "@ string / app_name" android: name = ". HereMaps"> </ activity>`
