### ISSUE TITLE
show HereMaps inside an android Linear Layout

### ISSUE THREAD

**Issue by aliexalter** [heremaps/here-android-sdk-examples#65]
Is there anyway to show HereMaps inside a Linear Layout?
This is my layout file and I want to show map in firstMap (LinearLayout).

`
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.apploft.tabs.MyTabFragment">
```

    <RelativeLayout
        android:id="@+id/confirmed"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:id="@+id/firstMap"
            android:layout_width="match_parent"
            android:layout_height="130dp"
            android:layout_alignParentTop="true"
            android:layout_centerHorizontal="true"
            android:layout_marginLeft="20dp"
            android:layout_marginRight="20dp"
            android:layout_marginTop="10dp"
            android:background="@color/cardview_shadow_start_color"
            android:orientation="horizontal">
            
        </LinearLayout>
</RelativeLayout>

`</FrameLayout>`
`

**Comment by aliexalter** [comment]
if I added fragment inside linear layout as follow
`<LinearLayout
            android:id="@+id/firstMap"
            android:layout_width="match_parent"
            android:layout_height="130dp"
            android:layout_alignParentTop="true"
            android:layout_centerHorizontal="true"
            android:layout_marginLeft="20dp"
            android:layout_marginRight="20dp"
            android:layout_marginTop="10dp"
            android:background="@color/cardview_shadow_start_color"
            android:orientation="horizontal">
            
            <fragment
                class="com.here.android.mpa.mapping.MapFragment"
                android:id="@+id/mapfragment"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
        </LinearLayout>`

and use 
`mapFragment = (MapFragment)getFragmentManager().findFragmentById(R.id.mapfragment);`
It return null.

**Comment by aliexalter** [comment]
It worked after hit and trial. when I use getChildFragmentManager() instead of getFragmentManager()

`mapFragment = (MapFragment)getChildFragmentManager().findFragmentById(R.id.mapfragment);`

**Comment by sschuberth** [comment]
Thanks @aliexalter for sharing the solution!
