### ISSUE TITLE
Getting NETWORK_COMMUNICATION error

### ISSUE THREAD

**Issue by hi0001234d** [heremaps/here-android-sdk-examples#68]
I clone the sample project and modify it as said in tutorial guide but when i run app on mobile and press Get direction it returns NETWORK_COMMUNICATION error in onCalculateRouteFinished method.

Help me to resolve this error.

**Comment by sschuberth** [comment]
@hi0001234d, where you able to resolve the issue? If so, mind sharing the resolution?

**Comment by tomekziel** [comment]
I got the very same error (map tiles visible and zoomable but NETWORK_COMMUNICATION while trying to do route search) when API trial key was cancelled manually before expiration date.
