### ISSUE TITLE
Unable to call NavigationManager.NewInstructionEventListener

### ISSUE THREAD

**Issue by bindu623** [heremaps/here-android-sdk-examples#73]
In the existing android code of turn by turn navigation, in MapFragmentView.java, I have added
private NavigationManager.NewInstructionEventListener instructionHandler = new NavigationManager.NewInstructionEventListener() {
        @Override
        public void onNewInstructionEvent() {
            Log.d("Bindu","onNewInstruction");
            Maneuver m = NavigationManager.getInstance().getNextManeuver();
            Log.d(TAG, "New instruction : in " + NavigationManager.getInstance().getNextManeuverDistance() + " m do " + m.getTurn().name() + " / " + m.getAction().name() + " on " + m.getNextRoadName() + " (from " + m.getRoadName() + ")");
            // ...
            // do something with this information, e.g. show it to the user
            super.onNewInstructionEvent();
        }
    };
and I am calling this function from addNavigationListeners() by calling this:
        m_navigationManager.addNewInstructionEventListener(new WeakReference<>(instructionHandler));
But function call is not getting delegated.Kindly let me know where I am doing the mistake.

Thank you

**Comment by Xgamefactory** [comment]
we have this issue to plus ManeuverEventListener does not trigger too.

**Comment by starand** [comment]
No response for a long time. Closing the issue.
