### ISSUE TITLE
Caused by: java.lang.NullPointerException: ApplicationContext has not been initialized

### ISSUE THREAD

**Issue by tuanhs66** [heremaps/here-android-sdk-examples#81]
When i use RouteManager.calculateRoute(routePlan, listener);
==> crash and show log Caused by: java.lang.NullPointerException: ApplicationContext has not been initialized
Pls help me this. Thank you so much

**Comment by apex39** [comment]
What if I would like to calculate e.g. some route between two points without displaying a map?

**Comment by NazarKacharaba** [comment]
There is `MapEngine` that you can use to initialize SDK. See example below:
```
if (!MapEngine.isInitialized()) {
    MapEngine.getInstance().init(new ApplicationContext(this), new OnEngineInitListener() {
        @Override public void onEngineInitializationCompleted(Error error) {
            if (error != Error.NONE) throw new RuntimeException(error.getDetails(), error.getThrowable());
            calcRoute();
        }
    });
} else {
    calcRoute();
}
```

**Comment by NazarKacharaba** [comment]
You must be using Starter Edition. Indeed, there is no such method. In that case you can always call `MapEngine.getInstance().init(...)` and do your stuff after callback is triggered. In case `MapEngine` is already initialized, `onEngineInitializationCompleted` will be triggered immediately.

**Comment by apex39** [comment]
Thank you, now I can delete the hidden map :)
