### ISSUE TITLE
need example with new ui kit

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#86]
can you make an example with with MSDKUI kit ?

**Comment by Xgamefactory** [comment]
reading https://developer.here.com/blog/build-beautiful-interfaces-with-the-here-mobile-sdk-ui-kit-for-android-and-ios it sounds that you made a nice ui kit.
But unfortunately there is only a simple text file called guickstart prepared in a hurry.

It would be nice to have a tutorial or and example as you provided here in your example github repo.

**Comment by Xgamefactory** [comment]
thanks. you should update url in your official blog article.
There is no way to find this new link on your web site.

**Comment by Xgamefactory** [comment]
also it would be more usefull if you share a demo on java instead of  kotlin language.

**Comment by artemnikitin** [comment]
> There is no way to find this new link on your web site.

We will open source UI kit very very soon...

**Comment by Xgamefactory** [comment]
we hope you will update demo in java too.
