### ISSUE TITLE
Voice instruction onDownloadDone has error NONE still catalog is empty 

### ISSUE THREAD

**Issue by chin87** [heremaps/here-android-sdk-examples#91]
I followed voice navigation enable instructions from here: 
https://developer.here.com/documentation/android-premium/topics/map-voice-instructions.html
In onDownloadDone() I get Error.NONE, still VoiceCatalog getCatalogList return empty list.
This used to work some days back, we have shifted from trial version to paid version.
Even after pushing 'voices' folder onto device, the catalog is empty.

**Comment by artemnikitin** [comment]
Please, contact technical support regarding this issue.

**Comment by starand** [comment]
@chin87 was your issue solved? Can we resole it?
