### ISSUE TITLE
need examples for new features like electronic horizon etc.

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-android-sdk-examples#97]
so many new features. looks like part of your dev team works really hard
but github team just hanging out )

**Comment by starand** [comment]
@datasun is there any updates?

**Comment by datasun** [comment]
There have been plenty of updates. Meanwhile, SDK 3.9 was released. If you are looking for Electronic Horizon, you can find more here:


- iOS: https://developer.here.com/documentation/ios-premium/dev_guide/topics/electronic-horizon.html


- Android: https://developer.here.com/documentation/android-premium/dev_guide/topics/electronic-horizon.html

________________________________
Von: starand <notifications@github.com>
Gesendet: Freitag, 23. November 2018 10:56:17
An: heremaps/here-android-sdk-examples
Cc: Lucka, Thomas; Mention
Betreff: Re: [heremaps/here-android-sdk-examples] need examples for new features like electronic horizon etc. (#97)


@datasun<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdatasun&data=01%7C01%7C%7C1024d758006b41cd38d108d65129ea06%7C6d4034cd72254f72b85391feaea64919%7C1&sdata=I7bMuJGJEyEz2LfgkvLpRAWFA2ZhQ9GQ7IxAtKQ8bnw%3D&reserved=0> is there any updates?

**Comment by Xgamefactory** [comment]
thanks we wil check it. Hope you have complete docs this time. )

**Comment by datasun** [comment]
Done. Thanks for your interest!
